import {useEffect,useMemo,useState} from "react";
import {CreditCard,KeyRound,Laptop,MapPin,ReceiptText,Shield,Smartphone,Trash2,WalletCards} from "lucide-react";
import {toast} from "sonner";
import {api,downloadBlob} from "./client";

type Overview={preferences:any;addresses:any[];billingMethods:any[];sessions:any[];devices:any[];orders:any[];refunds:any[];subscriptions:any[];giftCards:any[];storeCredit:any[];securityEvents:any[];deletion:any};
type Security={email:string;provider:string;aal:{current:string|null;next:string|null};factors:{all:any[];totp:any[];phone:any[]};passkeys:any[];passkeysExperimental:boolean};
const money=(minor:number,currency:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency:currency||"USD"}).format(Number(minor||0)/100);
function b64urlToBytes(value:string){const b64=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=");const raw=atob(b64);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function webauthnCreationOptions(raw:any):PublicKeyCredentialCreationOptions{const o=structuredClone(raw);o.challenge=b64urlToBytes(o.challenge);o.user={...o.user,id:b64urlToBytes(o.user.id)};o.excludeCredentials=(o.excludeCredentials||[]).map((c:any)=>({...c,id:b64urlToBytes(c.id)}));return o;}
function credentialJson(c:PublicKeyCredential){if((c as any).toJSON)return (c as any).toJSON();const enc=(b:ArrayBuffer)=>{let s="";for(const n of new Uint8Array(b))s+=String.fromCharCode(n);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");};const r:any=c.response;return{id:c.id,rawId:enc(c.rawId),type:c.type,response:{clientDataJSON:enc(r.clientDataJSON),attestationObject:r.attestationObject?enc(r.attestationObject):undefined,authenticatorData:r.authenticatorData?enc(r.authenticatorData):undefined,signature:r.signature?enc(r.signature):undefined,userHandle:r.userHandle?enc(r.userHandle):null,transports:r.getTransports?.()||undefined},clientExtensionResults:c.getClientExtensionResults(),authenticatorAttachment:(c as any).authenticatorAttachment};}

export function AccountManagementPanel(){
  const [overview,setOverview]=useState<Overview|null>(null),[security,setSecurity]=useState<Security|null>(null),[busy,setBusy]=useState("");
  const refresh=async()=>{const [a,s]=await Promise.all([api<Overview>("/account/management"),api<Security>("/auth/security")]);setOverview(a);setSecurity(s);};
  useEffect(()=>{refresh().catch(()=>{});},[]);
  const activeFactors=useMemo(()=>security?.factors?.totp?.filter((f:any)=>f.status==="verified")||[],[security]);
  const run=async(key:string,fn:()=>Promise<any>,success?:string)=>{setBusy(key);try{const r=await fn();if(success)toast.success(success);await refresh();return r;}catch(e){toast.error((e as Error).message);throw e;}finally{setBusy("");}};
  if(!overview||!security)return <section className="recommendation-privacy-panel"><h3>Account & security</h3><p className="muted">Loading your commercial account settings…</p></section>;
  return <div className="account-management-stack">
    <section className="recommendation-privacy-panel"><div><span className="small-label">SECURITY</span><h3><Shield size={18}/> Account security</h3><p className="muted">Provider-backed credentials, MFA, passkeys, and session controls. Cove does not store your password or card number.</p></div>
      <div className="recommendation-privacy-controls">
        <p><strong>{security.email}</strong> · {security.provider} · assurance {security.aal.current||"unknown"}{security.aal.next==="aal2"&&security.aal.current!=="aal2"?" · MFA verification required":""}</p>
        <form className="fore-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run("email",()=>api("/auth/email","POST",{email:f.get("email")}),"Email-change verification sent");}}><label>Change email<input name="email" type="email" required placeholder="new@example.com"/></label><button className="button outline" disabled={!!busy}>Send verification</button></form>
        <form className="fore-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await run("password",()=>api("/auth/change-password","POST",{currentPassword:f.get("current"),newPassword:f.get("next")}),"Password changed");if(r?.signedOut)location.assign("/?auth=login");}}><label>Current password<input name="current" type="password" autoComplete="current-password" required/></label><label>New password<input name="next" type="password" autoComplete="new-password" minLength={12} required/></label><button className="button outline" disabled={!!busy}><KeyRound size={16}/>Change password</button></form>
        <div className="inline-actions"><button className="button outline" disabled={!!busy} onClick={async()=>{const r=await run("mfa",()=>api("/auth/mfa/enroll","POST",{friendlyName:"Cove authenticator"}));const secret=r?.totp?.secret||"";const uri=r?.totp?.uri||"";const code=prompt(`Add this TOTP secret to your authenticator:\n${secret}\n\nURI:\n${uri}\n\nThen enter the 6-digit code:`);if(code)await run("mfa-verify",()=>api("/auth/mfa/verify","POST",{factorId:r.id,code}),"MFA enabled");}}>Enable authenticator MFA</button>{activeFactors.map((f:any)=><button key={f.id} className="text-link" disabled={!!busy} onClick={async()=>{const code=prompt("Enter a current authenticator code to verify this session:");if(code)await run("mfa-session",()=>api("/auth/mfa/verify","POST",{factorId:f.id,code}),"MFA verified for this session");}}>Verify MFA</button>)}</div>
        <div><strong>Passkeys</strong><p className="small muted">Phishing-resistant sign-in using your device, password manager, PIN, biometric, or security key. This provider feature is currently experimental.</p><div className="inline-actions"><button className="button outline" disabled={!!busy||!(window.PublicKeyCredential)} onClick={async()=>{await run("passkey",async()=>{const start=await api<any>("/auth/passkey/registration/start","POST",{});const credential=await navigator.credentials.create({publicKey:webauthnCreationOptions(start.options)}) as PublicKeyCredential|null;if(!credential)throw Error("Passkey registration was canceled.");return api("/auth/passkey/registration/verify","POST",{challengeId:start.challenge_id,credential:credentialJson(credential)});},"Passkey registered");}}>Add passkey</button>{security.passkeys?.map((p:any)=><button key={p.id} className="text-link" onClick={()=>run("passkey-delete",()=>api("/auth/passkey/delete","POST",{passkeyId:p.id}),"Passkey removed")}>Remove {p.friendly_name||"passkey"}</button>)}</div></div>
        <button className="button outline" disabled={!!busy} onClick={()=>run("sessions",()=>api("/auth/sessions/signout-others","POST",{}),"Other sessions signed out")}>Sign out other sessions</button>
      </div>
    </section>

    <section className="recommendation-privacy-panel"><div><span className="small-label">SESSIONS & DEVICES</span><h3><Laptop size={18}/> Active access</h3></div><div className="recommendation-privacy-controls">
      <button className="button outline" onClick={()=>run("device-register",async()=>{let key=localStorage.getItem("fore.device.key");if(!key){key=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem("fore.device.key",key);}return api("/account/device/register","POST",{deviceKey:key,name:`${navigator.platform||"Web"} browser`,platform:navigator.platform||"Web"});},"This device registered")}>Register this device for offline licenses</button>
      {overview.sessions.map(s=><div className="profile-info" key={s.id}><Smartphone size={17}/><p><strong>{s.user_agent_summary||"Session"}</strong><br/><span className="small muted">{s.ip_country||"—"} · last seen {new Date(s.last_seen_at).toLocaleString()} {s.revoked_at?"· revoked":""}</span></p>{!s.revoked_at&&<button className="text-link" onClick={()=>run("revoke-session",()=>api("/account/session/revoke","POST",{sessionId:s.id}),"Session revoked")}>Revoke</button>}</div>)}
      {overview.devices.map(d=><div className="profile-info" key={d.id}><Smartphone size={17}/><p><strong>{d.name||"Device"}</strong><br/><span className="small muted">{d.platform} · {d.revoked_at?"revoked":"active"}</span></p>{!d.revoked_at&&<button className="text-link" onClick={()=>run("revoke-device",()=>api("/account/device/revoke","POST",{deviceId:d.id}),"Device and offline licenses revoked")}>Revoke</button>}</div>)}
    </div></section>

    <section className="recommendation-privacy-panel"><div><span className="small-label">BILLING & ORDERS</span><h3><CreditCard size={18}/> Commerce</h3></div><div className="recommendation-privacy-controls">
      <div className="inline-actions"><button className="button outline" onClick={async()=>{const r=await run("billing",()=>api<any>("/account/billing-portal","POST",{}));if(r?.url)location.href=r.url;}}>Manage payment methods</button><button className="text-link" onClick={()=>run("billing-refresh",()=>api("/account/billing-methods/refresh","POST",{}),"Payment methods refreshed")}>Refresh</button></div>
      {overview.billingMethods.map(m=><p className="small" key={m.id}><WalletCards size={15}/> {m.brand||"Card"} •••• {m.last4} {m.exp_month&&m.exp_year?`· ${m.exp_month}/${m.exp_year}`:""} {m.is_default?"· default":""}</p>)}
      <h4>Orders</h4>{overview.orders.slice(0,20).map(o=><a className="profile-info" href={`/orders/${o.id}`} key={o.id}><ReceiptText size={17}/><p><strong>{o.invoice_number||o.id}</strong><br/><span className="small muted">{money(o.total_minor,o.currency)} · {o.status} · {new Date(o.created_at).toLocaleDateString()}</span></p></a>)}
      {!!overview.refunds.length&&<><h4>Refunds</h4>{overview.refunds.slice(0,10).map(r=><p className="small" key={r.id}>{money(r.amount_minor,r.currency)} · {r.status} · {r.reason}</p>)}</>}
      {!!overview.subscriptions.length&&<><h4>Subscriptions</h4>{overview.subscriptions.map(s=><p className="small" key={s.id}>{s.plan_code} · {s.status} · through {new Date(s.current_period_end).toLocaleDateString()}</p>)}</>}
      {(overview.giftCards.length>0||overview.storeCredit.length>0)&&<><h4>Balances</h4>{overview.giftCards.map(g=><p className="small" key={g.code_hash}>Gift •••• {g.last4}: {money(g.balance_minor,g.currency)} · {g.status}</p>)}{overview.storeCredit.map(c=><p className="small" key={c.currency}>Store credit: {money(c.balance_minor,c.currency)}</p>)}</>}
    </div></section>

    <section className="recommendation-privacy-panel"><div><span className="small-label">PREFERENCES & ADDRESSES</span><h3><MapPin size={18}/> Storefront preferences</h3></div><div className="recommendation-privacy-controls">
      <label>Storefront country<input maxLength={2} value={overview.preferences.storefrontCountry||"US"} onChange={e=>setOverview({...overview,preferences:{...overview.preferences,storefrontCountry:e.target.value.toUpperCase()}})}/></label>
      {[["privacy","analytics","Allow operational analytics"],["privacy","personalization","Allow personalization"],["marketing","email","Marketing email"],["marketing","deals","Deal alerts"],["marketing","authorReleases","Author-release marketing"],["notifications","orders","Order notifications"],["notifications","security","Security notifications"],["notifications","preorders","Preorder notifications"],["notifications","authorReleases","Author release alerts"],["notifications","priceDrops","Price-drop alerts"]].map(([group,key,label])=><label key={group+key}><input type="checkbox" checked={!!overview.preferences[group]?.[key]} onChange={e=>setOverview({...overview,preferences:{...overview.preferences,[group]:{...overview.preferences[group],[key]:e.target.checked}}})}/>{label}</label>)}
      <button className="button outline" onClick={()=>run("prefs",()=>api("/account/preferences","POST",overview.preferences),"Preferences saved")}>Save preferences</button>
      <h4>Saved addresses</h4>{overview.addresses.map(a=><div className="profile-info" key={a.id}><MapPin size={16}/><p><strong>{a.address_type}{a.is_default?" · default":""}</strong><br/><span className="small muted">{a.recipient_name} · {a.line1}, {a.city}, {a.region} {a.postal_code}, {a.country_code}</span></p><button className="text-link" onClick={()=>run("address-delete",()=>api(`/account/address/${encodeURIComponent(a.id)}`,"DELETE"),"Address deleted")}>Delete</button></div>)}
      <form className="fore-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run("address",()=>api("/account/address","POST",{addressType:f.get("type"),recipientName:f.get("name"),line1:f.get("line1"),line2:f.get("line2"),city:f.get("city"),region:f.get("region"),postalCode:f.get("postal"),countryCode:String(f.get("country")||"").toUpperCase(),isDefault:f.get("default")==="on"}),"Address saved");e.currentTarget.reset();}}><label>Type<select name="type" defaultValue="billing"><option value="billing">Billing</option><option value="shipping">Shipping</option><option value="tax">Tax</option></select></label><label>Name<input name="name" maxLength={160}/></label><label>Address line 1<input name="line1" required/></label><label>Address line 2<input name="line2"/></label><label>City<input name="city" required/></label><label>State / region<input name="region"/></label><label>Postal code<input name="postal" required/></label><label>Country code<input name="country" defaultValue={overview.preferences.storefrontCountry||"US"} pattern="[A-Za-z]{2}" maxLength={2} required/></label><label><input type="checkbox" name="default"/>Default for this type</label><button className="button outline">Add address</button></form>
    </div></section>

    <section className="recommendation-privacy-panel"><div><span className="small-label">DATA & ACCOUNT</span><h3>Export or delete</h3></div><div className="recommendation-privacy-controls"><button className="button outline" onClick={async()=>{try{const r=await fetch("/api/fore/account/export",{credentials:"same-origin",headers:{Accept:"application/json"}});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||"Account export failed.");}await downloadBlob(await r.blob(),`fore-account-export-${new Date().toISOString().slice(0,10)}.json`);}catch(e){toast.error((e as Error).message);}}}>Export account data</button>{overview.deletion?.status&&!["completed","canceled"].includes(overview.deletion.status)?<><p className="notice">Deletion status: {overview.deletion.status}. {overview.deletion.execute_after?`Scheduled after ${new Date(overview.deletion.execute_after).toLocaleString()}.`:""} {overview.deletion.legal_hold_reason||""}</p>{["requested","cooling_off","queued"].includes(overview.deletion.status)&&<button className="button outline" onClick={()=>run("delete-cancel",()=>api("/account/delete/cancel","POST",{}),"Account deletion canceled")}>Cancel deletion</button>}</>:<button className="text-link signout" onClick={async()=>{if(!confirm("Schedule permanent account deletion after a 7-day cooling-off period? Commerce/legal records that Cove must retain will be pseudonymized or retained only where required."))return;const confirmation=prompt('Type DELETE MY ACCOUNT to continue');if(confirmation==="DELETE MY ACCOUNT")await run("delete",()=>api("/account/delete","POST",{confirmation}),"Account deletion scheduled");}}><Trash2 size={16}/>Delete account</button>}</div></section>
  </div>;
}
