import {useEffect,useState} from 'react';
import {Eye,EyeOff,Mail,ArrowRight,BookOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from './client';
export type AuthMode='login'|'signup'|'verify'|'reset'|'new-password';
function b64urlBytes(value:string){const b64=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=");const raw=atob(b64);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function requestOptions(raw:any):PublicKeyCredentialRequestOptions{const o=structuredClone(raw);o.challenge=b64urlBytes(o.challenge);o.allowCredentials=(o.allowCredentials||[]).map((c:any)=>({...c,id:b64urlBytes(c.id)}));return o;}
function credentialJson(c:PublicKeyCredential){if((c as any).toJSON)return (c as any).toJSON();const enc=(b:ArrayBuffer)=>{let x="";for(const n of new Uint8Array(b))x+=String.fromCharCode(n);return btoa(x).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");};const r:any=c.response;return{id:c.id,rawId:enc(c.rawId),type:c.type,response:{clientDataJSON:enc(r.clientDataJSON),authenticatorData:r.authenticatorData?enc(r.authenticatorData):undefined,signature:r.signature?enc(r.signature):undefined,userHandle:r.userHandle?enc(r.userHandle):null},clientExtensionResults:c.getClientExtensionResults(),authenticatorAttachment:(c as any).authenticatorAttachment};}
export function AuthDialog({mode,onChange,onSuccess}:{mode:AuthMode|null;onChange:(v:AuthMode|null)=>void;onSuccess:()=>Promise<void>}){
  const [username,setUsername]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[options,setOptions]=useState({available:false,google:false}),[loading,setLoading]=useState(true);
  useEffect(()=>{if(!mode)return;setError('');setMessage('');setPassword('');setVisible(false);setLoading(true);api('/auth/options').then(setOptions).catch(()=>setOptions({available:false,google:false})).finally(()=>setLoading(false));},[mode]);
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');
    try{
      if(mode==='signup'){await api('/auth/signup','POST',{username,email,password});onChange('verify');}
      else if(mode==='verify'){await api('/auth/verify','POST',{email,code});await onSuccess();onChange(null);}
      else if(mode==='login'){const result=await api('/auth/login','POST',{login:username,password});if(result?.mfaRequired){const sec=await api<any>('/auth/security');const factor=sec?.factors?.totp?.find((f:any)=>f.status==='verified');if(!factor)throw Error('This account requires MFA, but no verified authenticator factor is available. Use account recovery or contact support.');const otp=prompt('Enter the current code from your authenticator app:');if(!otp)throw Error('MFA verification is required to continue.');await api('/auth/mfa/verify','POST',{factorId:factor.id,code:otp});}await onSuccess();onChange(null);}
      else if(mode==='reset'){const r=await api('/auth/reset','POST',{email});setMessage(r.message);}
      else if(mode==='new-password'){await api('/auth/password','POST',{password});onChange('login');}
    }catch(err){setError((err as Error).message);}finally{setBusy(false);}
  }
  const title=mode==='signup'?'A reading life of your own.':mode==='verify'?'Check your inbox.':mode==='reset'?'Find your way back.':mode==='new-password'?'Choose a new password.':'Welcome back.';
  return <Dialog open={!!mode} onOpenChange={v=>!v&&onChange(null)}><DialogContent className="fore-dialog auth-dialog">
    <span className="brand-icon"><BookOpen size={29}/></span><DialogTitle>{title}</DialogTitle>
    <DialogDescription>{mode==='verify'?`We sent a verification link to ${email||'your email address'}. Open it to verify your account, then sign in. You can also enter the email code below if one is included.`:mode==='signup'?'Keep your books, notes, and reading progress together. Verify your email to finish creating your account.':mode==='reset'?'Enter your verified email address for a password-reset link.':'Your next chapter is waiting.'}</DialogDescription>
    {!loading&&!options.available&&<p className="notice" role="status">Account sign-in is being set up. You can still browse and read.</p>}
    {(mode==='signup'||mode==='login')&&<><a className={'button outline google-signin'+(!options.google?' is-disabled':'')} aria-disabled={!options.google} href={options.google?'/api/fore/auth/google':undefined} onClick={e=>{if(!options.google)e.preventDefault();}}><span className="google-g" aria-hidden="true">G</span> Continue with Google</a>{mode==='login'&&typeof window!=='undefined'&&'PublicKeyCredential' in window&&<button type="button" className="button outline" disabled={busy||!options.available} onClick={async()=>{setBusy(true);setError('');try{const start=await api<any>('/auth/passkey/authentication/start','POST',{});const credential=await navigator.credentials.get({publicKey:requestOptions(start.options)}) as PublicKeyCredential|null;if(!credential)throw Error('Passkey sign-in was canceled.');await api('/auth/passkey/authentication/verify','POST',{challengeId:start.challenge_id,credential:credentialJson(credential)});await onSuccess();onChange(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Use a passkey</button>}<div className="auth-divider"><span>or use your {mode==='signup'?'email':'password'}</span></div></>}
    <form className="fore-form auth-form" onSubmit={submit}>
      {(mode==='signup'||mode==='login')&&<label>{mode==='signup'?'Username':'Username or email'}<input autoComplete={mode==='signup'?'username':'username'} required value={username} onChange={e=>setUsername(e.target.value)} minLength={mode==='signup'?3:1} maxLength={mode==='signup'?30:254} pattern={mode==='signup'?'[a-zA-Z][a-zA-Z0-9_]{2,29}':undefined} placeholder={mode==='signup'?'your_reading_name':'Username or email'}/></label>}
      {(mode==='signup'||mode==='reset'||mode==='verify')&&<label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>}
      {(mode==='signup'||mode==='login'||mode==='new-password')&&<label>Password<div className="password-input"><input type={visible?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'Your password':'At least 12 characters'}/><button type="button" className="icon-button" aria-label={visible?'Hide password':'Show password'} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}
      {mode==='verify'&&<label>Verification code<input inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6,10}" value={code} onChange={e=>setCode(e.target.value)} placeholder="Code from your email"/></label>}
      {error&&<p className="notice" role="alert">{error}</p>}{message&&<p className="small" role="status">{message}</p>}
      <button className="button gold" disabled={busy||!options.available}>{busy?'Please wait…':mode==='signup'?'Create account':mode==='verify'?'Verify email':mode==='reset'?'Send reset link':mode==='new-password'?'Save new password':'Log in'}<ArrowRight size={17}/></button>
    </form>
    {mode==='verify'&&<button className="text-link" disabled={busy||!options.available} onClick={async()=>{setBusy(true);try{const r=await api('/auth/resend','POST',{email});setMessage(r.message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Mail size={15}/> Resend verification email</button>}
    {mode==='login'&&<button className="text-link" onClick={()=>onChange('reset')}>Forgot your password?</button>}
    <p className="small muted">{mode==='signup'?'Already have an account? ':mode==='login'?'New to Cove? ':''}<button className="text-link" onClick={()=>onChange(mode==='login'?'signup':'login')}>{mode==='login'?'Create account':'Back to log in'}</button></p>
  </DialogContent></Dialog>;
}
