import { z } from "zod";
import { ApiError } from "./service";
import type { CatalogDB } from "./catalog-model.server";
import { accrueSaleRoyaltiesForOrder, createRoyaltyContractVersion } from "./royalty-engine.server";
import { emitNotification } from "./notifications.server";
import { assessPayoutRisk } from "./risk-tax.server";

const now=()=>new Date().toISOString();
const uid=(p:string)=>`${p}_${crypto.randomUUID()}`;

async function postLedger(db:CatalogDB,orderId:string|null,userId:string|null,type:string,account:string,amount:number,currency:string,external:string,metadata:any={}){
  const exists=await db.prepare("SELECT 1 ok FROM commerce_ledger_entries WHERE COALESCE(order_id,'')=COALESCE(?,'') AND entry_type=? AND account_code=? AND external_reference=? LIMIT 1").bind(orderId,type,account,external).first<any>();
  if(exists)return;
  await db.prepare("INSERT OR IGNORE INTO commerce_ledger_entries(id,order_id,user_id,entry_type,account_code,amount_minor,currency,external_reference,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(uid("led"),orderId,userId,type,account,amount,currency,external,JSON.stringify(metadata),now()).run();
}

export async function accrueRoyaltiesForOrder(db:CatalogDB,orderId:string){return accrueSaleRoyaltiesForOrder(db,orderId);}

async function reversalFromCalculation(db:CatalogDB,sourceType:"refund"|"chargeback",sourceId:string,original:any,ratio:number,order:any,refundId:string|null){
  const reversalSource=`${sourceId}:${original.id}`;
  const exists=await db.prepare("SELECT id FROM finance_royalty_calculations WHERE source_type=? AND source_id=? AND product_id=?").bind(sourceType,reversalSource,original.product_id).first<any>();
  if(exists)return;
  const calcId=uid("roycalc"),at=now(),scale=(n:any)=>-Math.min(Math.abs(Number(n||0)),Math.round(Math.abs(Number(n||0))*ratio));
  await db.prepare(`INSERT INTO finance_royalty_calculations(id,source_type,source_id,order_id,order_item_id,product_id,contract_id,contract_version_id,contract_version_hash,rule_id,territory_code,format,sales_channel,currency,quantity,list_price_minor,customer_price_minor,tax_minor,processor_fee_minor,promotion_discount_minor,fore_funded_discount_minor,publisher_funded_discount_minor,distributor_fee_minor,net_receipts_minor,basis_minor,fore_commission_minor,royalty_pool_minor,rule_trace_json,input_snapshot_json,calculated_at)
    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(calcId,sourceType,reversalSource,original.order_id,original.order_item_id,original.product_id,original.contract_id,original.contract_version_id,original.contract_version_hash,original.rule_id,original.territory_code,original.format,original.sales_channel,original.currency,original.quantity,scale(original.list_price_minor),scale(original.customer_price_minor),scale(original.tax_minor),scale(original.processor_fee_minor),scale(original.promotion_discount_minor),scale(original.fore_funded_discount_minor),scale(original.publisher_funded_discount_minor),scale(original.distributor_fee_minor),scale(original.net_receipts_minor),scale(original.basis_minor),scale(original.fore_commission_minor),scale(original.royalty_pool_minor),JSON.stringify([`reversal:${sourceType}`,`original:${original.id}`,`ratio:${ratio}`]),JSON.stringify({reversalOf:original.id,ratio,sourceId}),at).run();
  const allocations=(await db.prepare("SELECT * FROM finance_royalty_allocations WHERE calculation_id=? ORDER BY party_id").bind(original.id).all<any>()).results;
  for(const a of allocations){
    const royalty=scale(a.royalty_minor),withholding=scale(a.withholding_minor),reserve=scale(a.reserve_minor),payable=scale(a.payable_minor),legacyId=uid("roy");
    if(original.order_id&&original.order_item_id){
      await db.prepare(`INSERT OR IGNORE INTO finance_royalty_events(id,order_id,order_item_id,refund_id,contract_version_id,party_id,event_type,basis_minor,royalty_minor,withholding_minor,reserve_minor,payable_minor,currency,status,available_at,external_reference,created_at,royalty_calculation_id,sales_channel,territory_code,product_id)
        VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(legacyId,original.order_id,original.order_item_id,refundId,original.contract_version_id,a.party_id,sourceType,scale(original.basis_minor),royalty,withholding,reserve,payable,original.currency,"accrued",at,reversalSource,at,calcId,original.sales_channel,original.territory_code,original.product_id).run();
    }
    await db.prepare("INSERT INTO finance_royalty_allocations(id,calculation_id,party_id,share_bps,royalty_minor,withholding_minor,reserve_minor,payable_minor,currency,status,available_at,legacy_royalty_event_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,'accrued',?,?,?)").bind(uid("royalloc"),calcId,a.party_id,a.share_bps,royalty,withholding,reserve,payable,original.currency,at,original.order_id?legacyId:null,at).run();
    const ref=`${calcId}:${a.party_id}`;
    await postLedger(db,original.order_id,order?.user_id||null,`royalty_${sourceType}`,"royalty_expense",royalty,original.currency,ref,{reversalOf:original.id,sourceId});
    await postLedger(db,original.order_id,order?.user_id||null,`royalty_${sourceType}`,`royalty_payable:${a.party_id}`,-payable,original.currency,ref,{reversalOf:original.id,sourceId});
    if(withholding)await postLedger(db,original.order_id,order?.user_id||null,`royalty_${sourceType}`,"withholding_payable",-withholding,original.currency,ref,{reversalOf:original.id});
    if(reserve)await postLedger(db,original.order_id,order?.user_id||null,`royalty_${sourceType}`,"royalty_reserve_liability",-reserve,original.currency,ref,{reversalOf:original.id});
  }
}

export async function reverseRoyaltiesForRefund(db:CatalogDB,refundId:string){
  const refund=await db.prepare("SELECT * FROM commerce_refunds WHERE id=?").bind(refundId).first<any>();if(!refund)return;
  const order=await db.prepare("SELECT * FROM commerce_orders WHERE id=?").bind(refund.order_id).first<any>();if(!order)return;
  const ratio=Math.min(1,Number(refund.amount_minor)/Math.max(1,Number(order.total_minor)));
  const calculations=(await db.prepare("SELECT * FROM finance_royalty_calculations WHERE order_id=? AND source_type='sale'").bind(order.id).all<any>()).results;
  for(const c of calculations)await reversalFromCalculation(db,"refund",refund.id,c,ratio,order,refund.id);
}

export async function createRoyaltyContract(db:CatalogDB,raw:unknown){
  const x=z.object({name:z.string().min(1),publisherId:z.string().nullable().optional(),productId:z.string().nullable().optional(),editionId:z.string().nullable().optional(),territory:z.string().length(2).nullable().optional(),format:z.string().nullable().optional(),salesChannel:z.enum(["retail","subscription","library","wholesale","agency"]).default("retail"),effectiveFrom:z.string().datetime(),effectiveTo:z.string().datetime().nullable().optional(),basis:z.enum(["list_price","customer_price","net_revenue"]).default("net_revenue"),foreCommissionBps:z.number().int().min(0).max(10000).default(3000),defaultRoyaltyRateBps:z.number().int().min(0).max(10000).nullable().optional(),paymentTermsDays:z.number().int().min(0).max(730).default(60),reserveBps:z.number().int().min(0).max(10000).default(0),notes:z.string().max(2000).default(""),splits:z.array(z.object({partyId:z.string(),shareBps:z.number().int().min(0).max(10000)})).min(1),rules:z.array(z.any()).default([])}).parse(raw);
  if(x.splits.reduce((s,r)=>s+r.shareBps,0)!==10000)throw new ApiError(400,"Royalty splits must allocate exactly 100%.");
  const at=now(),id=uid("rc");
  await db.prepare("INSERT INTO finance_royalty_contracts(id,name,publisher_id,product_id,edition_id,territory_code,format,sales_channel,effective_from,effective_to,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'active',?,?)").bind(id,x.name,x.publisherId||null,x.productId||null,x.editionId||null,x.territory?.toUpperCase()||null,x.format||null,x.salesChannel,x.effectiveFrom,x.effectiveTo||null,at,at).run();
  const version=await createRoyaltyContractVersion(db,{contractId:id,effectiveFrom:x.effectiveFrom,effectiveTo:x.effectiveTo,basis:x.basis,foreCommissionBps:x.foreCommissionBps,defaultRoyaltyRateBps:x.defaultRoyaltyRateBps,paymentTermsDays:x.paymentTermsDays,reserveBps:x.reserveBps,notes:x.notes,splits:x.splits,rules:x.rules});
  return{id,versionId:version.versionId,version:version.version,rulesVersionHash:version.rulesVersionHash};
}

export async function createFinanceParty(db:CatalogDB,raw:unknown){const x=z.object({type:z.enum(["publisher","author","agent","narrator","distributor","other"]),displayName:z.string().min(1),publisherId:z.string().nullable().optional(),contributorId:z.string().nullable().optional(),taxCountry:z.string().length(2).nullable().optional(),withholdingBps:z.number().int().min(0).max(10000).default(0),payoutCurrency:z.string().length(3).default("USD")}).parse(raw),at=now(),id=uid("party");await db.prepare("INSERT INTO finance_parties(id,party_type,display_name,publisher_id,contributor_id,tax_country,withholding_bps,payout_currency,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?, 'active',?,?)").bind(id,x.type,x.displayName,x.publisherId||null,x.contributorId||null,x.taxCountry?.toUpperCase()||null,x.withholdingBps,x.payoutCurrency.toUpperCase(),at,at).run();return{id};}

export async function createPayoutBatch(db:CatalogDB,raw:unknown){
  const x=z.object({currency:z.string().length(3),periodStart:z.string().datetime(),periodEnd:z.string().datetime()}).parse(raw),at=now(),id=uid("paybatch"),currency=x.currency.toUpperCase();
  const eligible=await db.prepare(`SELECT party_id,SUM(royalty_minor) gross,SUM(withholding_minor) withholding,SUM(payable_minor) net FROM finance_royalty_allocations WHERE currency=? AND status='accrued' AND available_at<=? AND created_at>=? AND created_at<? GROUP BY party_id HAVING SUM(payable_minor)<>0`).bind(currency,at,x.periodStart,x.periodEnd).all<any>();
  let gross=0,withholding=0,net=0;await db.prepare("INSERT INTO payout_batches(id,currency,period_start,period_end,status,created_at) VALUES(?,?,?,?,'draft',?)").bind(id,currency,x.periodStart,x.periodEnd,at).run();
  for(const r of eligible.results){const pi=uid("payi");await db.prepare("INSERT INTO payout_items(id,batch_id,party_id,currency,gross_minor,withholding_minor,net_minor,status,created_at) VALUES(?,?,?,?,?,?,?,'pending',?)").bind(pi,id,r.party_id,currency,r.gross,r.withholding,r.net,at).run();const allocations=await db.prepare("SELECT id,legacy_royalty_event_id,tax_profile_id FROM finance_royalty_allocations WHERE party_id=? AND currency=? AND status='accrued' AND available_at<=? AND created_at>=? AND created_at<?").bind(r.party_id,currency,at,x.periodStart,x.periodEnd).all<any>();for(const a of allocations.results){await db.prepare("INSERT OR IGNORE INTO payout_allocation_links(payout_item_id,royalty_allocation_id) VALUES(?,?)").bind(pi,a.id).run();if(a.legacy_royalty_event_id)await db.prepare("INSERT OR IGNORE INTO payout_event_links(payout_item_id,royalty_event_id) VALUES(?,?)").bind(pi,a.legacy_royalty_event_id).run();}const taxProfile=allocations.results.find((a:any)=>a.tax_profile_id)?.tax_profile_id||null;if(taxProfile)await db.prepare("UPDATE payout_items SET tax_profile_id=? WHERE id=?").bind(taxProfile,pi).run();await assessPayoutRisk(db,pi);gross+=Number(r.gross);withholding+=Number(r.withholding);net+=Number(r.net);}
  await db.prepare("UPDATE payout_batches SET gross_minor=?,withholding_minor=?,net_minor=? WHERE id=?").bind(gross,withholding,net,id).run();return{id,grossMinor:gross,withholdingMinor:withholding,netMinor:net,parties:eligible.results.length};
}

export async function approvePayoutBatch(db:CatalogDB,batchId:string){const b=await db.prepare("SELECT * FROM payout_batches WHERE id=?").bind(batchId).first<any>();if(!b||b.status!=="draft")throw new ApiError(409,"Payout batch is not in draft status.");const at=now(),held=Number((await db.prepare("SELECT COUNT(*) n FROM payout_items WHERE batch_id=? AND status='held'").bind(batchId).first<any>())?.n||0);await db.prepare("UPDATE payout_batches SET status='approved',approved_at=? WHERE id=?").bind(at,batchId).run();await db.prepare("UPDATE finance_royalty_allocations SET status='payable' WHERE id IN (SELECT royalty_allocation_id FROM payout_allocation_links WHERE payout_item_id IN (SELECT id FROM payout_items WHERE batch_id=? AND status='pending')) AND status='accrued'").bind(batchId).run();await db.prepare("UPDATE finance_royalty_events SET status='payable' WHERE id IN (SELECT royalty_event_id FROM payout_event_links WHERE payout_item_id IN (SELECT id FROM payout_items WHERE batch_id=? AND status='pending')) AND status='accrued'").bind(batchId).run();return{id:batchId,status:"approved",heldItems:held};}

export async function reverseRoyaltiesForChargeback(db:CatalogDB,orderId:string,disputeId:string){const order=await db.prepare("SELECT * FROM commerce_orders WHERE id=?").bind(orderId).first<any>();if(!order)return;const calculations=(await db.prepare("SELECT * FROM finance_royalty_calculations WHERE order_id=? AND source_type='sale'").bind(orderId).all<any>()).results;for(const c of calculations)await reversalFromCalculation(db,"chargeback",disputeId,c,1,order,null);}

export async function settlePayoutBatch(db:CatalogDB,raw:unknown){
  const x=z.object({batchId:z.string().min(1),settlements:z.array(z.object({payoutItemId:z.string().min(1),externalPayoutId:z.string().min(3).max(180)})).min(1)}).parse(raw),batch=await db.prepare("SELECT * FROM payout_batches WHERE id=?").bind(x.batchId).first<any>();if(!batch||!["approved","processing"].includes(batch.status))throw new ApiError(409,"Payout batch is not approved for settlement.");const at=now();
  for(const settlement of x.settlements){const item=await db.prepare("SELECT * FROM payout_items WHERE id=? AND batch_id=?").bind(settlement.payoutItemId,x.batchId).first<any>();if(!item)throw new ApiError(404,"Payout item not found.");if(item.status==="paid")continue;if(item.status==="held")throw new ApiError(409,`Payout item is held by rights, fraud, or tax compliance (${item.hold_reason_code||"ACTIVE_HOLD"}).`);const held=await db.prepare("SELECT 1 ok FROM finance_royalty_allocations WHERE status='held' AND id IN (SELECT royalty_allocation_id FROM payout_allocation_links WHERE payout_item_id=?) LIMIT 1").bind(item.id).first<any>();if(held)throw new ApiError(409,"Payout item contains royalties frozen by an active rights dispute.");await db.prepare("UPDATE payout_items SET status='paid',external_payout_id=? WHERE id=?").bind(settlement.externalPayoutId,item.id).run();await db.prepare("UPDATE finance_royalty_allocations SET status='paid' WHERE id IN (SELECT royalty_allocation_id FROM payout_allocation_links WHERE payout_item_id=?)").bind(item.id).run();await db.prepare("UPDATE finance_royalty_events SET status='paid' WHERE id IN (SELECT royalty_event_id FROM payout_event_links WHERE payout_item_id=?)").bind(item.id).run();await postLedger(db,null,null,"royalty_payout",`royalty_payable:${item.party_id}`,Number(item.net_minor),item.currency,settlement.externalPayoutId,{payoutItemId:item.id});await postLedger(db,null,null,"royalty_payout","cash",-Number(item.net_minor),item.currency,settlement.externalPayoutId,{payoutItemId:item.id});try{const accounts=(await db.prepare("SELECT id FROM publishing_accounts WHERE finance_party_id=?").bind(item.party_id).all<any>()).results;for(const a of accounts){const members=(await db.prepare("SELECT user_id FROM publishing_account_members WHERE account_id=? AND status='active' AND role IN ('owner','admin','analyst')").bind(a.id).all<any>()).results;for(const m of members)await emitNotification(db,{userId:String(m.user_id),eventType:"payout_sent",dedupeKey:`payout:${item.id}:${m.user_id}`,title:"Payout sent",body:`Cove sent your ${String(item.currency)} payout of ${(Number(item.net_minor||0)/100).toFixed(2)}.`,subjectType:"payout_item",subjectId:String(item.id),actionUrl:"/publishing",payload:{batchId:x.batchId,payoutItemId:item.id,externalPayoutId:settlement.externalPayoutId,currency:item.currency,netMinor:Number(item.net_minor||0)}});}}catch(e){console.error("Payout notification enqueue failed",e);}}
  const remaining=Number((await db.prepare("SELECT COUNT(*) n FROM payout_items WHERE batch_id=? AND status<>'paid'").bind(x.batchId).first<any>())?.n||0);await db.prepare("UPDATE payout_batches SET status=?,paid_at=CASE WHEN ?=0 THEN ? ELSE paid_at END WHERE id=?").bind(remaining===0?"paid":"processing",remaining,at,x.batchId).run();return{batchId:x.batchId,status:remaining===0?"paid":"processing",remaining};
}

export async function financeAdminSnapshot(db:CatalogDB){
  const [parties,contracts,events,calculations,batches,statements]=await Promise.all([
    db.prepare("SELECT * FROM finance_parties ORDER BY updated_at DESC LIMIT 200").all<any>(),
    db.prepare(`SELECT rc.*,rcv.id version_id,rcv.version,rcv.calculation_basis,rcv.fore_commission_bps,rcv.default_royalty_rate_bps,rcv.payment_terms_days,rcv.reserve_bps,rcv.rules_version_hash,rcv.effective_from version_effective_from,rcv.effective_to version_effective_to,(SELECT COUNT(*) FROM finance_royalty_rules rr WHERE rr.contract_version_id=rcv.id) rule_count FROM finance_royalty_contracts rc LEFT JOIN finance_royalty_contract_versions rcv ON rcv.contract_id=rc.id WHERE rc.status<>'retired' ORDER BY rc.updated_at DESC,rcv.version DESC LIMIT 500`).all<any>(),
    db.prepare("SELECT * FROM finance_royalty_events ORDER BY created_at DESC LIMIT 300").all<any>(),
    db.prepare("SELECT * FROM finance_royalty_calculations ORDER BY calculated_at DESC LIMIT 300").all<any>(),
    db.prepare("SELECT * FROM payout_batches ORDER BY created_at DESC LIMIT 100").all<any>(),
    db.prepare("SELECT * FROM finance_statements ORDER BY generated_at DESC LIMIT 100").all<any>(),
  ]);return{parties:parties.results,contracts:contracts.results,royaltyEvents:events.results,royaltyCalculations:calculations.results,payoutBatches:batches.results,statements:statements.results};
}
