import {useEffect,useState} from "react";
import {Bell,CheckCheck,Mail,ShieldAlert,Smartphone,Webcam} from "lucide-react";
import {toast} from "sonner";
import {api} from "./client";

type Item={id:string;event_type:string;topic:string;urgency:string;title:string;body:string;action_url:string;created_at:string;read_at?:string|null;payload?:Record<string,unknown>};
type Inbox={items:Item[];unread:number};
type Prefs={email:boolean;inApp:boolean;webPush:boolean;mobilePush:boolean;topics:Record<string,boolean>;quietHours:Record<string,unknown>;timezone:string};
const labels:Record<string,string>={orders:"Purchase receipts",preorders:"Preorder releases",authorReleases:"Followed-author releases",priceDrops:"Wishlist price drops",billing:"Billing & payment",publishing:"Publishing decisions",royalties:"Royalty statements",payouts:"Payouts",reviews:"Review moderation",security:"Security alerts"};
function b64ToBytes(value:string){const b64=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=");const raw=atob(b64);return Uint8Array.from(raw,c=>c.charCodeAt(0));}

export function NotificationsPage(){
  const [inbox,setInbox]=useState<Inbox|null>(null),[prefs,setPrefs]=useState<Prefs|null>(null),[busy,setBusy]=useState(false);
  const reload=async()=>{const [i,p]=await Promise.all([api<Inbox>("/notifications"),api<Prefs>("/notifications/preferences")]);setInbox(i);setPrefs(p);};
  useEffect(()=>{reload().catch(e=>toast.error((e as Error).message));},[]);
  const save=async(next:Prefs)=>{setBusy(true);try{const p=await api<Prefs>("/notifications/preferences","POST",next);setPrefs(p);toast.success("Notification preferences saved");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
  const enableWebPush=async()=>{if(!prefs)return;if(!("serviceWorker" in navigator)||!("PushManager" in window)){toast.error("Web Push is not supported in this browser.");return;}setBusy(true);try{const cfg=await api<{webPushPublicKey:string|null}>("/notifications/config");if(!cfg.webPushPublicKey)throw Error("Web Push is not configured on this Cove deployment.");const reg=await navigator.serviceWorker.ready;const permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Browser notification permission was not granted.");let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToBytes(cfg.webPushPublicKey) as BufferSource});const j=sub.toJSON();await api("/notifications/push/register","POST",{channel:"web_push",platform:"web",endpoint:j.endpoint,p256dh:j.keys?.p256dh||"",auth:j.keys?.auth||""});await save({...prefs,webPush:true});}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
  if(!inbox||!prefs)return <section className="store-section"><span className="page-eyebrow">NOTIFICATIONS</span><h1>Inbox</h1><p className="muted">Loading notifications…</p></section>;
  return <div className="notifications-page">
    <section className="store-section"><div className="section-heading"><div><span className="page-eyebrow">IN-APP INBOX</span><h1><Bell size={25}/> Notifications</h1><p className="muted">Transactional, publishing, royalty, moderation, and security notices in one durable inbox.</p></div><button className="button outline" disabled={!inbox.unread||busy} onClick={async()=>{setBusy(true);try{setInbox(await api<Inbox>("/notifications/mark","POST",{all:true}));}finally{setBusy(false);}}}><CheckCheck size={16}/>Mark all read</button></div>
      <p className="small muted">{inbox.unread} unread · {inbox.items.length} recent</p>
      <div className="notification-list">{inbox.items.length?inbox.items.map(n=><article key={n.id} className={`notification-card ${n.read_at?"":"unread"}`}><div className="notification-dot"/><div><div className="notification-meta"><span>{labels[n.topic]||n.topic}</span><span>{new Date(n.created_at).toLocaleString()}</span>{n.urgency!=="normal"&&<span className="notification-urgency">{n.urgency}</span>}</div><h3>{n.title}</h3><p>{n.body}</p><div className="inline-actions">{n.action_url&&<a className="text-link" href={n.action_url} onClick={()=>{if(!n.read_at)api("/notifications/mark","POST",{ids:[n.id]}).catch(()=>{});}}>Open</a>}{!n.read_at&&<button className="text-link" onClick={async()=>setInbox(await api<Inbox>("/notifications/mark","POST",{ids:[n.id]}))}>Mark read</button>}</div></div></article>):<div className="empty-state"><Bell size={30}/><h3>No notifications yet</h3><p>Receipts, releases, billing notices, publishing decisions, payouts, moderation updates, and security alerts will appear here.</p></div>}</div>
    </section>
    <section className="store-section notification-settings"><span className="page-eyebrow">CHANNELS & TOPICS</span><h2>Delivery preferences</h2><p className="muted">Security alerts remain enabled in the in-app inbox even if optional topics are disabled.</p>
      <div className="notification-channel-grid"><label><input type="checkbox" checked={prefs.inApp} onChange={e=>save({...prefs,inApp:e.target.checked})}/><Bell size={17}/>In-app inbox</label><label><input type="checkbox" checked={prefs.email} onChange={e=>save({...prefs,email:e.target.checked})}/><Mail size={17}/>Email</label><button className="button outline" disabled={busy||prefs.webPush} onClick={enableWebPush}><Webcam size={17}/>{prefs.webPush?"Web Push enabled":"Enable Web Push"}</button><div className="muted small"><Smartphone size={15}/> Mobile push is modeled and ready for an APNs/FCM provider bridge when native apps ship.</div></div>
      <div className="notification-topic-grid">{Object.entries(labels).map(([key,label])=><label key={key} className={key==="security"?"required-topic":""}><input type="checkbox" disabled={key==="security"||busy} checked={key==="security"?true:prefs.topics[key]!==false} onChange={e=>save({...prefs,topics:{...prefs.topics,[key]:e.target.checked}})}/>{key==="security"?<ShieldAlert size={16}/>:<Bell size={16}/>}<span>{label}{key==="security"&&<small>Required</small>}</span></label>)}</div>
    </section>
  </div>;
}
