import { z } from "zod";
import type { CatalogDB } from "./catalog-model.server";
import { ApiError } from "./service";
import { promotionPermitted, resolveProductRights } from "./rights.server";
import { updatePreorderLowestPrice } from "./preorder.server";
import { recordRetailEvent } from "./retail-intelligence.server";

const now = () => new Date().toISOString();
const uid = (p: string) => `${p}_${crypto.randomUUID()}`;
async function sha256(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}
const campaignType = z.enum(["scheduled_price_drop","daily_deal","genre_sale","publisher_sale","coupon","free_promotion","first_in_series","bundle","launch_pricing","seasonal","countdown"]);

async function membership(db: CatalogDB, userId: string, accountId: string) {
  const row = await db.prepare("SELECT role FROM publishing_account_members WHERE user_id=? AND account_id=? AND status='active'").bind(userId, accountId).first<any>();
  if (!row) throw new ApiError(403, "You do not have access to this publishing account.");
  return row;
}
async function activePromotionPolicy(db:CatalogDB){const p=await db.prepare("SELECT * FROM promotion_policy_versions WHERE status='active' ORDER BY version DESC LIMIT 1").first<any>();if(!p)throw new ApiError(503,"No active promotion policy is configured.");return p;}
async function campaignEvent(db: CatalogDB, campaignId: string, type: string, actorType: string, actorId: string | null, payload: Record<string, unknown> = {}) {
  await db.prepare("INSERT INTO promotion_campaign_events(id,campaign_id,event_type,actor_type,actor_id,event_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(uid("promoevt"),campaignId,type,actorType,actorId,JSON.stringify(payload),now()).run();
}
async function ownedProduct(db: CatalogDB, accountId: string, productId: string) {
  return db.prepare(`SELECT pp.product_id,pp.offer_id,e.title,p.format FROM publishing_publications pp JOIN products p ON p.id=pp.product_id JOIN editions e ON e.id=p.edition_id WHERE pp.publishing_account_id=? AND pp.product_id=? LIMIT 1`).bind(accountId,productId).first<any>();
}

export async function savePromotionCampaign(db: CatalogDB, userId: string, raw: unknown) {
  const x = z.object({
    id: z.string().nullable().optional(), accountId: z.string().min(1), name: z.string().trim().min(2).max(160), type: campaignType,
    fundingSource: z.enum(["publisher","fore","shared"]).default("publisher"), publisherFundingBps: z.number().int().min(0).max(10000).default(10000),
    currency: z.string().regex(/^[A-Za-z]{3}$/).nullable().optional(), territory: z.string().regex(/^[A-Za-z]{2}$/).nullable().optional(),
    startsAt: z.string().datetime(), endsAt: z.string().datetime(), budgetMinor: z.number().int().min(0).nullable().optional(), maxRedemptions: z.number().int().positive().nullable().optional(),
    stackable: z.boolean().default(false), merchandisingSubmission: z.boolean().default(false), eligibility: z.record(z.unknown()).default({}),
    products: z.array(z.object({ productId: z.string().min(1), promotionalPriceMinor: z.number().int().min(0).nullable().optional(), publisherFundingBps: z.number().int().min(0).max(10000).nullable().optional(), role: z.string().min(1).max(40).default("featured") })).min(1).max(500),
  }).parse(raw);
  await membership(db,userId,x.accountId);
  if (x.endsAt <= x.startsAt) throw new ApiError(400,"Promotion end must be after its start.");
  if (x.fundingSource === "publisher" && x.publisherFundingBps !== 10000) throw new ApiError(400,"Publisher-funded campaigns must allocate 100% of the discount to the publisher.");
  if (x.fundingSource === "fore" && x.publisherFundingBps !== 0) throw new ApiError(400,"Cove-funded campaigns cannot allocate discount funding to the publisher.");
  const policy=await activePromotionPolicy(db);if(x.products.length>Number(policy.max_products))throw new ApiError(400,`This campaign exceeds the ${policy.max_products}-product policy limit.`);if(Date.parse(x.endsAt)-Date.parse(x.startsAt)>Number(policy.max_duration_days)*86400000)throw new ApiError(400,`This campaign exceeds the ${policy.max_duration_days}-day policy limit.`);
  const at=now(), id=x.id||uid("campaign");
  const existing=x.id?await db.prepare("SELECT * FROM promotion_campaigns WHERE id=?").bind(id).first<any>():null;
  if(existing && existing.publishing_account_id!==x.accountId)throw new ApiError(404,"Campaign not found.");
  if(existing && !["draft","rejected"].includes(existing.status))throw new ApiError(409,"Only draft or rejected campaigns can be edited.");
  for(const p of x.products){const owned=await ownedProduct(db,x.accountId,p.productId);if(!owned)throw new ApiError(403,`Product ${p.productId} is not owned by this publishing account.`);const rights=await resolveProductRights(db,p.productId,(x.territory||"US").toUpperCase(),{salesChannel:"retail",at:x.startsAt});if(!rights.allowed)throw new ApiError(409,`${owned.title} is not licensed for the selected campaign territory.`);const current=await db.prepare("SELECT amount_minor FROM offers WHERE id=COALESCE(?,?)").bind(owned.offer_id,owned.offer_id).first<any>();const proposed=p.promotionalPriceMinor==null?Number(current?.amount_minor||0):p.promotionalPriceMinor;const allowed=promotionPermitted(rights.promotionRestrictions,{type:x.type,baseAmountMinor:Number(current?.amount_minor||0),proposedAmountMinor:proposed,rightsholderApproved:x.fundingSource==="publisher"});if(!allowed.allowed)throw new ApiError(409,`${owned.title} cannot participate in this promotion (${allowed.reasonCode}).`);}
  if(existing){await db.prepare(`UPDATE promotion_campaigns SET name=?,campaign_type=?,funding_source=?,publisher_funding_bps=?,currency=?,territory_code=?,starts_at=?,ends_at=?,budget_minor=?,max_redemptions=?,stackable=?,eligibility_json=?,merchandising_submission=?,policy_version=?,status='draft',submitted_at=NULL,approved_at=NULL,updated_at=? WHERE id=?`).bind(x.name,x.type,x.fundingSource,x.publisherFundingBps,x.currency?.toUpperCase()||null,x.territory?.toUpperCase()||null,x.startsAt,x.endsAt,x.budgetMinor??null,x.maxRedemptions??null,x.stackable?1:0,JSON.stringify(x.eligibility),x.merchandisingSubmission?1:0,policy.id,at,id).run();await db.prepare("DELETE FROM promotion_campaign_products WHERE campaign_id=?").bind(id).run();}
  else await db.prepare(`INSERT INTO promotion_campaigns(id,publishing_account_id,name,campaign_type,status,funding_source,publisher_funding_bps,currency,territory_code,starts_at,ends_at,budget_minor,max_redemptions,stackable,eligibility_json,merchandising_submission,created_by_user_id,created_at,updated_at,policy_version) VALUES(?,?,?,?,'draft',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,x.accountId,x.name,x.type,x.fundingSource,x.publisherFundingBps,x.currency?.toUpperCase()||null,x.territory?.toUpperCase()||null,x.startsAt,x.endsAt,x.budgetMinor??null,x.maxRedemptions??null,x.stackable?1:0,JSON.stringify(x.eligibility),x.merchandisingSubmission?1:0,userId,at,at,policy.id).run();
  for(const p of x.products){const owned=await ownedProduct(db,x.accountId,p.productId);const offer=await db.prepare("SELECT id,amount_minor FROM offers WHERE product_id=? AND sales_channel='retail' ORDER BY created_at DESC LIMIT 1").bind(p.productId).first<any>();await db.prepare("INSERT INTO promotion_campaign_products(campaign_id,product_id,offer_id,role,original_price_minor,promotional_price_minor,publisher_funding_bps,metadata_json) VALUES(?,?,?,?,?,?,?, '{}')").bind(id,p.productId,offer?.id||owned?.offer_id||null,p.role,offer?.amount_minor??null,p.promotionalPriceMinor??null,p.publisherFundingBps??null).run();}
  await campaignEvent(db,id,existing?"draft_updated":"draft_created","publisher",userId,{productCount:x.products.length});
  return {id,status:"draft"};
}

export async function submitPromotionCampaign(db: CatalogDB,userId:string,raw:unknown){const x=z.object({accountId:z.string().min(1),campaignId:z.string().min(1)}).parse(raw);await membership(db,userId,x.accountId);const c=await db.prepare("SELECT * FROM promotion_campaigns WHERE id=? AND publishing_account_id=?").bind(x.campaignId,x.accountId).first<any>();if(!c)throw new ApiError(404,"Campaign not found.");if(!["draft","rejected"].includes(c.status))throw new ApiError(409,"Campaign is not submittable.");const count=Number((await db.prepare("SELECT COUNT(*) n FROM promotion_campaign_products WHERE campaign_id=?").bind(c.id).first<any>())?.n||0);if(!count)throw new ApiError(409,"Campaign must contain at least one product.");const at=now();await db.prepare("UPDATE promotion_campaigns SET status='submitted',submitted_at=?,updated_at=? WHERE id=?").bind(at,at,c.id).run();await campaignEvent(db,c.id,"submitted","publisher",userId,{});return{id:c.id,status:"submitted"};}

export async function reviewPromotionCampaign(db: CatalogDB,staffUserId:string,raw:unknown){const x=z.object({campaignId:z.string().min(1),decision:z.enum(["approve","reject"]),notes:z.string().max(2000).default("")}).parse(raw);const c=await db.prepare("SELECT * FROM promotion_campaigns WHERE id=?").bind(x.campaignId).first<any>();if(!c)throw new ApiError(404,"Campaign not found.");if(c.status!=="submitted")throw new ApiError(409,"Campaign is not awaiting review.");const at=now(),status=x.decision==="approve"?(c.starts_at<=at?(c.ends_at>at?"live":"ended"):"scheduled"):"rejected";await db.prepare("UPDATE promotion_campaigns SET status=?,approved_at=CASE WHEN ?='approve' THEN ? ELSE approved_at END,updated_at=? WHERE id=?").bind(status,x.decision,at,at,c.id).run();await campaignEvent(db,c.id,x.decision==="approve"?"approved":"rejected","staff",staffUserId,{notes:x.notes});if(x.decision==="approve")await materializeCampaign(db,c.id);return{id:c.id,status};}

async function materializeCampaign(db: CatalogDB,campaignId:string){const c=await db.prepare("SELECT * FROM promotion_campaigns WHERE id=?").bind(campaignId).first<any>();if(!c||!["approved","scheduled","live"].includes(c.status))return;const products=(await db.prepare("SELECT * FROM promotion_campaign_products WHERE campaign_id=?").bind(c.id).all<any>()).results;const at=now();for(const p of products){const offer=p.offer_id?await db.prepare("SELECT * FROM offers WHERE id=?").bind(p.offer_id).first<any>():await db.prepare("SELECT * FROM offers WHERE product_id=? AND sales_channel='retail' ORDER BY created_at DESC LIMIT 1").bind(p.product_id).first<any>();if(!offer)continue;const price=p.promotional_price_minor==null?(c.campaign_type==="free_promotion"?0:Number(offer.amount_minor)):Number(p.promotional_price_minor);const promoId=`promo_campaign_${c.id}_${p.product_id}`;await db.prepare(`INSERT INTO promotions(id,offer_id,name,promotion_type,amount_minor,starts_at,ends_at,active,funding_source,publisher_funding_bps,campaign_id,metadata_json) VALUES(?,?,?,?,?,?,?,1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,amount_minor=excluded.amount_minor,starts_at=excluded.starts_at,ends_at=excluded.ends_at,active=1,funding_source=excluded.funding_source,publisher_funding_bps=excluded.publisher_funding_bps,campaign_id=excluded.campaign_id,metadata_json=excluded.metadata_json`).bind(promoId,offer.id,c.name,"sale-price",price,c.starts_at,c.ends_at,c.funding_source,p.publisher_funding_bps??c.publisher_funding_bps,c.id,JSON.stringify({campaignType:c.campaign_type})).run();if(c.campaign_type==="coupon"){/* Coupon campaigns are materialized only when a code is explicitly created; no guessable code is generated. */}if(c.status==="live"||c.starts_at<=at)await updatePreorderLowestPrice(db,p.product_id,"campaign_price_drop");await db.prepare("INSERT INTO publishing_outbox(id,event_type,aggregate_type,aggregate_id,payload_json,status,attempts,available_at,created_at) VALUES(?, 'promotion.price_changed','promotion_campaign',?,?,'pending',0,?,?)").bind(uid("out"),c.id,JSON.stringify({campaignId:c.id,productId:p.product_id,startsAt:c.starts_at,endsAt:c.ends_at,promotionalPriceMinor:price}),at,at).run();}
}

export async function advancePromotionCampaigns(db:CatalogDB){const at=now();let started=0,ended=0;const due=(await db.prepare("SELECT * FROM promotion_campaigns WHERE status IN ('approved','scheduled','live') ORDER BY starts_at LIMIT 500").all<any>()).results;for(const c of due){if(["approved","scheduled"].includes(c.status)&&c.starts_at<=at&&c.ends_at>at){await db.prepare("UPDATE promotion_campaigns SET status='live',updated_at=? WHERE id=?").bind(at,c.id).run();await db.prepare("UPDATE promotions SET active=1 WHERE campaign_id=?").bind(c.id).run();await campaignEvent(db,c.id,"started","automation",null,{});await materializeCampaign(db,c.id);started++;}if(c.ends_at<=at&&c.status!=="ended"){await db.prepare("UPDATE promotion_campaigns SET status='ended',updated_at=? WHERE id=?").bind(at,c.id).run();await db.prepare("UPDATE promotions SET active=0 WHERE campaign_id=?").bind(c.id).run();await campaignEvent(db,c.id,"ended","automation",null,{});ended++;}}return{started,ended};}

export async function cancelPromotionCampaign(db:CatalogDB,userId:string,raw:unknown){const x=z.object({accountId:z.string().min(1),campaignId:z.string().min(1),reason:z.string().max(1000).default("publisher canceled")}).parse(raw);await membership(db,userId,x.accountId);const c=await db.prepare("SELECT * FROM promotion_campaigns WHERE id=? AND publishing_account_id=?").bind(x.campaignId,x.accountId).first<any>();if(!c)throw new ApiError(404,"Campaign not found.");if(["ended","canceled"].includes(c.status))return{id:c.id,status:c.status};const at=now();await db.prepare("UPDATE promotion_campaigns SET status='canceled',updated_at=? WHERE id=?").bind(at,c.id).run();await db.prepare("UPDATE promotions SET active=0 WHERE campaign_id=?").bind(c.id).run();await campaignEvent(db,c.id,"canceled","publisher",userId,{reason:x.reason});return{id:c.id,status:"canceled"};}

export async function recordPromotionAttribution(db:CatalogDB,input:{campaignId:string;productId?:string|null;userId?:string|null;visitorId?:string|null;eventType:"impression"|"click"|"wishlist"|"cart"|"order"|"refund";orderId?:string|null;orderItemId?:string|null;amountMinor?:number;fundingMinor?:number;currency?:string|null;sourceSurface?:string;dedupeKey?:string|null}){const c=await db.prepare("SELECT id,budget_minor,currency,status FROM promotion_campaigns WHERE id=?").bind(input.campaignId).first<any>();if(!c)return null;const result:any=await db.prepare("INSERT OR IGNORE INTO promotion_attribution_events(id,campaign_id,product_id,user_id,visitor_id,event_type,order_id,order_item_id,amount_minor,currency,source_surface,created_at,funding_minor,dedupe_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(uid("pattrib"),c.id,input.productId||null,input.userId||null,input.visitorId||null,input.eventType,input.orderId||null,input.orderItemId||null,Math.round(input.amountMinor||0),input.currency?.toUpperCase()||c.currency||null,input.sourceSurface||"",now(),Math.round(input.fundingMinor||0),input.dedupeKey||null).run();return{recorded:Number(result?.meta?.changes??result?.changes??0)===1};}

export async function recordStorefrontPromotionEvent(db:CatalogDB,userId:string|null,raw:unknown){
  const x=z.object({campaignId:z.string().min(1).max(180),productId:z.string().min(1).max(180),eventType:z.enum(["impression","click","wishlist","cart"]),visitorId:z.string().trim().min(1).max(180),eventId:z.string().trim().min(8).max(180),sourceSurface:z.string().trim().max(120).default("storefront")}).parse(raw);
  const c=await db.prepare("SELECT * FROM promotion_campaigns WHERE id=?").bind(x.campaignId).first<any>();if(!c)throw new ApiError(404,"Promotion campaign not found.");
  const at=now();if(!["approved","scheduled","live"].includes(String(c.status))||String(c.starts_at)>at||String(c.ends_at)<=at)throw new ApiError(409,"This promotion is not currently active.");
  const product=await db.prepare("SELECT 1 ok FROM promotion_campaign_products WHERE campaign_id=? AND product_id=?").bind(c.id,x.productId).first<any>();if(!product)throw new ApiError(400,"This product is not part of the promotion.");
  const attribution=await recordPromotionAttribution(db,{campaignId:c.id,productId:x.productId,userId,visitorId:x.visitorId,eventType:x.eventType,sourceSurface:x.sourceSurface,dedupeKey:`storefront:${x.eventId}`});
  if(x.eventType==="impression"||x.eventType==="click") await recordRetailEvent(db,userId,{eventType:x.eventType==="impression"?"promotion_impression":"promotion_clicked",anonymousId:x.visitorId,productId:x.productId,campaignId:c.id,sourceSurface:x.sourceSurface,dedupeKey:`promotion:${x.eventId}`});
  return attribution;
}

export async function createCampaignCoupon(db:CatalogDB,userId:string,raw:unknown){const x=z.object({accountId:z.string().min(1),campaignId:z.string().min(1),code:z.string().trim().min(3).max(80),kind:z.enum(["percent","amount"]),value:z.number().int().positive(),minimumSubtotalMinor:z.number().int().min(0).default(0),maxPerUser:z.number().int().min(1).max(100).default(1)}).parse(raw);await membership(db,userId,x.accountId);const c=await db.prepare("SELECT * FROM promotion_campaigns WHERE id=? AND publishing_account_id=?").bind(x.campaignId,x.accountId).first<any>();if(!c||c.campaign_type!=="coupon")throw new ApiError(404,"Coupon campaign not found.");if(!["scheduled","live"].includes(c.status))throw new ApiError(409,"Coupon codes can be issued only for approved campaigns.");if(x.kind==="percent"&&x.value>100)throw new ApiError(400,"Percentage coupons cannot exceed 100%.");const products=(await db.prepare("SELECT product_id FROM promotion_campaign_products WHERE campaign_id=?").bind(c.id).all<any>()).results.map((r:any)=>String(r.product_id));const code=x.code.toUpperCase().replace(/\s+/g,""),hash=await sha256(code),at=now();await db.prepare(`INSERT INTO commerce_promo_codes(code_hash,code_label,kind,value,currency,minimum_subtotal_minor,max_redemptions,max_per_user,redemptions,active,starts_at,ends_at,created_at,updated_at,campaign_id,funding_source,publisher_funding_bps,eligible_products_json,stackable) VALUES(?,?,?,?,?,?,?,?,0,1,?,?,?,?,?,?,?,?,?) ON CONFLICT(code_hash) DO UPDATE SET campaign_id=excluded.campaign_id,kind=excluded.kind,value=excluded.value,currency=excluded.currency,minimum_subtotal_minor=excluded.minimum_subtotal_minor,max_redemptions=excluded.max_redemptions,max_per_user=excluded.max_per_user,active=excluded.active,starts_at=excluded.starts_at,ends_at=excluded.ends_at,updated_at=excluded.updated_at,funding_source=excluded.funding_source,publisher_funding_bps=excluded.publisher_funding_bps,eligible_products_json=excluded.eligible_products_json,stackable=excluded.stackable`).bind(hash,code,x.kind,x.value,c.currency||null,x.minimumSubtotalMinor,c.max_redemptions||null,x.maxPerUser,c.starts_at,c.ends_at,at,at,c.id,c.funding_source,c.publisher_funding_bps,JSON.stringify(products),c.stackable).run();await campaignEvent(db,c.id,"coupon_issued","publisher",userId,{codeLabel:code,maxPerUser:x.maxPerUser});return{campaignId:c.id,codeLabel:code};}

export async function publisherPromotionDashboard(db:CatalogDB,userId:string,accountId:string){await membership(db,userId,accountId);const campaigns=(await db.prepare(`SELECT c.*,(SELECT COUNT(*) FROM promotion_campaign_products p WHERE p.campaign_id=c.id) product_count,(SELECT COUNT(*) FROM promotion_attribution_events a WHERE a.campaign_id=c.id AND a.event_type='impression') impressions,(SELECT COUNT(*) FROM promotion_attribution_events a WHERE a.campaign_id=c.id AND a.event_type='click') clicks,(SELECT COUNT(*) FROM promotion_attribution_events a WHERE a.campaign_id=c.id AND a.event_type='order') orders,(SELECT COALESCE(SUM(amount_minor),0) FROM promotion_attribution_events a WHERE a.campaign_id=c.id AND a.event_type='order') attributed_revenue_minor FROM promotion_campaigns c WHERE c.publishing_account_id=? ORDER BY c.created_at DESC`).bind(accountId).all<any>()).results;return{campaigns};}

export async function promotionOperationsDashboard(db:CatalogDB){const campaigns=(await db.prepare(`SELECT c.*,a.display_name publisher_name,(SELECT COUNT(*) FROM promotion_campaign_products p WHERE p.campaign_id=c.id) product_count FROM promotion_campaigns c LEFT JOIN publishing_accounts a ON a.id=c.publishing_account_id ORDER BY CASE c.status WHEN 'submitted' THEN 0 WHEN 'live' THEN 1 ELSE 2 END,c.updated_at DESC LIMIT 500`).all<any>()).results;return{campaigns};}
