import { z } from "zod";
import { ApiError, now } from "./service";
import type { CatalogDB } from "./catalog-model.server";
import { canonicalBooksByProductIds, resolveProduct } from "./catalog-model.server";
import { resolveEntityId } from "./discovery.server";
import { createModerationCase, type StaffContext } from "./moderation.server";
import { emitNotification } from "./notifications.server";
import { assessCommunityReviewRisk } from "./risk-tax.server";

const uid = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;
const clean = (value: unknown, max = 4000) => String(value ?? "").trim().slice(0, max);
async function sha256Text(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("");}
const allowedLinkKinds = ["website","instagram","facebook","x","tiktok","youtube","bluesky","mastodon","other"] as const;
const socialHosts: Partial<Record<(typeof allowedLinkKinds)[number], string[]>> = {
  instagram: ["instagram.com", "www.instagram.com"],
  facebook: ["facebook.com", "www.facebook.com", "fb.com", "www.fb.com"],
  x: ["x.com", "www.x.com", "twitter.com", "www.twitter.com"],
  tiktok: ["tiktok.com", "www.tiktok.com"],
  youtube: ["youtube.com", "www.youtube.com", "youtu.be"],
  bluesky: ["bsky.app", "www.bsky.app"],
};
const provenanceWeights: Record<string, number> = {
  verified_purchase: 1,
  subscription_reader: 0.9,
  gifted: 0.8,
  free_promotional_copy: 0.65,
  sideloaded_unverified: 0.35,
  publisher_author_copy: 0.2,
};

function blockedPublicHost(host:string){
  host=host.toLowerCase().replace(/^\[|\]$/g,"");if(host==="localhost"||host.endsWith(".localhost")||host.endsWith(".local")||host.endsWith(".internal")||host==="::1"||host.startsWith("fe80:")||host.startsWith("fc")||host.startsWith("fd"))return true;
  const p=host.split(".").map(Number);if(p.length===4&&p.every(n=>Number.isInteger(n)&&n>=0&&n<=255)){return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===192&&p[1]===168)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===100&&p[1]>=64&&p[1]<=127);}
  return false;
}
function publicHttps(raw:string,label:string){const url=new URL(raw);if(url.protocol!=="https:")throw new ApiError(400,`${label} must use HTTPS.`);if(blockedPublicHost(url.hostname))throw new ApiError(400,`${label} cannot target a private network.`);url.username="";url.password="";url.hash="";return url;}
function parseLinks(raw: unknown) {
  return z.array(z.object({ type:z.enum(allowedLinkKinds), label:z.string().trim().max(80).default(""), url:z.string().url().max(500), position:z.number().int().min(0).max(50).default(0) })).max(12).parse(raw ?? []).map(link => {
    const url=publicHttps(link.url,"Author links"),host=url.hostname.toLowerCase(),allowed=socialHosts[link.type];
    if(allowed && !allowed.includes(host)) throw new ApiError(400,`${link.type} links must point to the official ${link.type} domain.`);
    return { ...link, url:url.toString(), host };
  });
}

async function requirePublisherAuthor(db: CatalogDB, userId: string, accountId: string, penNameId: string) {
  const member=await db.prepare("SELECT role FROM publishing_account_members WHERE account_id=? AND user_id=? AND status='active'").bind(accountId,userId).first<any>();
  if(!member || !["admin","editor"].includes(String(member.role))) throw new ApiError(403,"Publisher editor access is required.");
  const pen=await db.prepare("SELECT * FROM publishing_pen_names WHERE id=? AND account_id=? AND status='active'").bind(penNameId,accountId).first<any>();
  if(!pen) throw new ApiError(404,"Pen name not found for this publishing account.");
  let contributorId=pen.contributor_id?String(pen.contributor_id):"";
  if(!contributorId){
    contributorId=`con_author_${penNameId}`;
    const at=now();
    await db.batch([
      db.prepare("INSERT OR IGNORE INTO contributors(id,name,sort_name,bio,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(contributorId,pen.display_name,pen.sort_name||pen.display_name,"",at,at),
      db.prepare("UPDATE publishing_pen_names SET contributor_id=?,updated_at=? WHERE id=? AND contributor_id IS NULL").bind(contributorId,at,penNameId),
    ]);
  }
  return { pen, contributorId };
}

export async function saveAuthorProfile(db: CatalogDB,userId:string,raw:unknown){
  const x=z.object({
    accountId:z.string().min(1).max(180),penNameId:z.string().min(1).max(180),biography:z.string().trim().max(10000).default(""),photoUrl:z.string().url().or(z.literal("")).default(""),publisherId:z.string().max(180).nullable().optional(),imprintId:z.string().max(180).nullable().optional(),locale:z.string().regex(/^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})?$/).default("en"),links:z.unknown().default([]),submit:z.boolean().default(false)
  }).parse(raw),links=parseLinks(x.links),{pen,contributorId}=await requirePublisherAuthor(db,userId,x.accountId,x.penNameId),at=now();
  if(x.photoUrl)publicHttps(x.photoUrl,"Author photos");
  if(x.publisherId){const p=await db.prepare("SELECT id FROM publishers WHERE id=?").bind(x.publisherId).first<any>();if(!p)throw new ApiError(400,"Publisher entity not found.");}
  if(x.imprintId){const i=await db.prepare("SELECT id,publisher_id FROM imprints WHERE id=?").bind(x.imprintId).first<any>();if(!i)throw new ApiError(400,"Imprint entity not found.");if(x.publisherId&&String(i.publisher_id)!==x.publisherId)throw new ApiError(400,"The selected imprint does not belong to the selected publisher.");}
  const existing=await db.prepare("SELECT * FROM author_profiles WHERE contributor_id=?").bind(contributorId).first<any>(),pending=await db.prepare("SELECT id FROM author_profile_revisions WHERE contributor_id=? AND status='submitted' ORDER BY revision_number DESC LIMIT 1").bind(contributorId).first<any>();
  if(pending)throw new ApiError(409,"An author-profile revision is already awaiting review.");
  await db.batch([
    db.prepare(`INSERT INTO author_profiles(contributor_id,publishing_account_id,pen_name_id,profile_status,verification_status,biography,photo_url,locale,created_at,updated_at) VALUES(?,?,?,'draft','unverified','','',?,?,?) ON CONFLICT(contributor_id) DO UPDATE SET publishing_account_id=excluded.publishing_account_id,pen_name_id=excluded.pen_name_id,updated_at=excluded.updated_at`).bind(contributorId,x.accountId,x.penNameId,x.locale,at,at),
    db.prepare("UPDATE contributors SET name=?,sort_name=?,updated_at=? WHERE id=?").bind(pen.display_name,pen.sort_name||pen.display_name,at,contributorId),
  ]);
  let revision=await db.prepare("SELECT * FROM author_profile_revisions WHERE contributor_id=? AND status='draft' ORDER BY revision_number DESC LIMIT 1").bind(contributorId).first<any>();
  const linksPayload=links.map(({type,label,url,host,position})=>({type,label,url,host,position})),content=JSON.stringify({biography:x.biography,photoUrl:x.photoUrl,publisherId:x.publisherId||null,imprintId:x.imprintId||null,locale:x.locale,links:linksPayload}),hash=await sha256Text(content);
  if(revision){await db.prepare("UPDATE author_profile_revisions SET biography=?,photo_url=?,publisher_id=?,imprint_id=?,locale=?,links_json=?,content_sha256=?,updated_at=? WHERE id=? AND status='draft'").bind(x.biography,x.photoUrl,x.publisherId||null,x.imprintId||null,x.locale,JSON.stringify(linksPayload),hash,at,revision.id).run();}
  else {const next=await db.prepare("SELECT COALESCE(MAX(revision_number),0)+1 n FROM author_profile_revisions WHERE contributor_id=?").bind(contributorId).first<any>(),id=uid("authorrev");await db.prepare("INSERT INTO author_profile_revisions(id,contributor_id,revision_number,publishing_account_id,pen_name_id,status,biography,photo_url,publisher_id,imprint_id,locale,links_json,content_sha256,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,'draft',?,?,?,?,?,?,?,?,?,?)").bind(id,contributorId,Number(next?.n||1),x.accountId,x.penNameId,x.biography,x.photoUrl,x.publisherId||null,x.imprintId||null,x.locale,JSON.stringify(linksPayload),hash,userId,at,at).run();revision={id,revision_number:Number(next?.n||1)};}
  if(x.submit){await db.prepare("UPDATE author_profile_revisions SET status='submitted',submitted_at=?,updated_at=? WHERE id=? AND status='draft'").bind(at,at,revision.id).run();const hasApproved=String(existing?.profile_status||"")==="active"&&String(existing?.verification_status||"")==="verified";await db.prepare("UPDATE author_profiles SET profile_status=?,verification_status=?,updated_at=? WHERE contributor_id=?").bind(hasApproved?"active":"submitted",hasApproved?"verified":"pending",at,contributorId).run();await createModerationCase(db as any,{subjectType:"author",subjectId:contributorId,publishingAccountId:x.accountId,category:"author_verification",queue:"authors",priority:"normal",sourceType:"author_profile_revision",sourceRef:String(revision.id),riskScore:15,summary:`Verify author profile: ${pen.display_name}`,details:hasApproved?"Publisher submitted changes to an already verified commercial author profile. The previously approved revision remains public until review.":"Publisher submitted a commercial author profile for identity and content verification.",evidence:{revisionId:revision.id,revisionNumber:revision.revision_number,contentSha256:hash}});}
  await db.prepare("INSERT INTO author_profile_events(id,contributor_id,event_type,actor_type,actor_user_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(uid("authorevt"),contributorId,x.submit?"submitted":existing?"updated":"created","publisher",userId,JSON.stringify({accountId:x.accountId,penNameId:x.penNameId,revisionId:revision.id,revisionNumber:revision.revision_number,contentSha256:hash,linkCount:links.length}),at).run();
  const profile=await db.prepare("SELECT profile_status,verification_status FROM author_profiles WHERE contributor_id=?").bind(contributorId).first<any>();return{contributorId,revisionId:revision.id,revisionNumber:revision.revision_number,revisionStatus:x.submit?"submitted":"draft",status:profile?.profile_status||"draft",verificationStatus:profile?.verification_status||"unverified"};
}

export async function reviewAuthorVerification(db:CatalogDB,staff:StaffContext,raw:unknown){
  const x=z.object({contributorId:z.string().min(1).max(180),revisionId:z.string().min(1).max(180).optional(),decision:z.enum(["verified","rejected","revoked","suspended","restored"]),method:z.string().trim().max(120).default("manual"),reference:z.string().max(240).default(""),reasonCode:z.string().max(120).default(""),notes:z.string().trim().max(2000).default("")}).parse(raw),at=now();
  const profile=await db.prepare("SELECT * FROM author_profiles WHERE contributor_id=?").bind(x.contributorId).first<any>();if(!profile)throw new ApiError(404,"Author profile not found.");
  let revision:any=null;if(["verified","rejected"].includes(x.decision)){revision=x.revisionId?await db.prepare("SELECT * FROM author_profile_revisions WHERE id=? AND contributor_id=? AND status='submitted'").bind(x.revisionId,x.contributorId).first<any>():await db.prepare("SELECT * FROM author_profile_revisions WHERE contributor_id=? AND status='submitted' ORDER BY revision_number DESC LIMIT 1").bind(x.contributorId).first<any>();if(!revision)throw new ApiError(409,"No submitted author-profile revision is awaiting review.");}
  if(x.decision==="verified"&&revision){let links:any[]=[];try{const parsed=JSON.parse(String(revision.links_json||"[]"));if(Array.isArray(parsed))links=parsed;}catch{}await db.prepare("UPDATE author_profile_revisions SET status='superseded',reviewed_at=?,reviewed_by_user_id=? WHERE contributor_id=? AND status='approved'").bind(at,staff.userId,x.contributorId).run();await db.prepare("UPDATE author_profile_revisions SET status='approved',reviewed_by_user_id=?,reviewed_at=?,review_notes=?,updated_at=? WHERE id=? AND status='submitted'").bind(staff.userId,at,x.notes,at,revision.id).run();const statements:any[]=[db.prepare("UPDATE author_profiles SET publishing_account_id=?,pen_name_id=?,profile_status='active',verification_status='verified',verification_method=?,verification_reference=?,verified_by_user_id=?,verified_at=COALESCE(verified_at,?),biography=?,photo_url=?,publisher_id=?,imprint_id=?,locale=?,updated_at=? WHERE contributor_id=?").bind(revision.publishing_account_id,revision.pen_name_id,x.method,x.reference,staff.userId,at,revision.biography,revision.photo_url,revision.publisher_id,revision.imprint_id,revision.locale,at,x.contributorId),db.prepare("DELETE FROM author_profile_links WHERE contributor_id=?").bind(x.contributorId),db.prepare("UPDATE contributors SET bio=?,image_url=?,updated_at=? WHERE id=?").bind(revision.biography||"",revision.photo_url||"",at,x.contributorId)];for(const link of links)statements.push(db.prepare("INSERT INTO author_profile_links(id,contributor_id,link_type,label,url,normalized_host,status,position,created_at,updated_at) VALUES(?,?,?,?,?,?,'active',?,?,?)").bind(uid("authorlink"),x.contributorId,link.type,link.label||"",link.url,link.host||new URL(link.url).hostname.toLowerCase(),Number(link.position||0),at,at));await db.batch(statements);}
  else if(x.decision==="rejected"&&revision){await db.prepare("UPDATE author_profile_revisions SET status='rejected',reviewed_by_user_id=?,reviewed_at=?,review_notes=?,updated_at=? WHERE id=? AND status='submitted'").bind(staff.userId,at,x.notes,at,revision.id).run();const preserve=String(profile.profile_status)==="active"&&String(profile.verification_status)==="verified";await db.prepare("UPDATE author_profiles SET profile_status=?,verification_status=?,updated_at=? WHERE contributor_id=?").bind(preserve?"active":"draft",preserve?"verified":"rejected",at,x.contributorId).run();}
  else if(x.decision==="suspended")await db.prepare("UPDATE author_profiles SET profile_status='suspended',updated_at=? WHERE contributor_id=?").bind(at,x.contributorId).run();
  else if(x.decision==="revoked")await db.prepare("UPDATE author_profiles SET verification_status='revoked',updated_at=? WHERE contributor_id=?").bind(at,x.contributorId).run();
  else if(x.decision==="restored")await db.prepare("UPDATE author_profiles SET profile_status='active',verification_status='verified',verification_method=?,verification_reference=?,verified_by_user_id=?,verified_at=COALESCE(verified_at,?),updated_at=? WHERE contributor_id=?").bind(x.method,x.reference,staff.userId,at,at,x.contributorId).run();
  await db.prepare("INSERT INTO author_profile_events(id,contributor_id,event_type,actor_type,actor_user_id,reason_code,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(uid("authorevt"),x.contributorId,x.decision,"staff",staff.userId,x.reasonCode,JSON.stringify({method:x.method,reference:x.reference,revisionId:revision?.id||null,revisionNumber:revision?.revision_number||null,notes:x.notes}),at).run();
  const updated=await db.prepare("SELECT profile_status,verification_status FROM author_profiles WHERE contributor_id=?").bind(x.contributorId).first<any>();return{contributorId:x.contributorId,revisionId:revision?.id||null,status:updated?.profile_status,verificationStatus:updated?.verification_status};
}

export async function authorProfile(db:CatalogDB,ref:string,userId:string|null,territory="US"){
  const contributorId=await resolveEntityId(db,"author",ref), author=await db.prepare(`SELECT c.id,c.name,c.slug,CASE WHEN ap.contributor_id IS NULL THEN c.bio WHEN ap.profile_status='active' THEN ap.biography ELSE '' END public_bio,CASE WHEN ap.contributor_id IS NULL THEN c.image_url WHEN ap.profile_status='active' THEN ap.photo_url ELSE '' END public_photo,ap.profile_status,ap.verification_status,ap.badge_label,CASE WHEN ap.profile_status='active' THEN p.name END publisher_name,CASE WHEN ap.profile_status='active' THEN p.slug END publisher_slug,CASE WHEN ap.profile_status='active' THEN i.name END imprint_name,CASE WHEN ap.profile_status='active' THEN i.slug END imprint_slug FROM contributors c LEFT JOIN author_profiles ap ON ap.contributor_id=c.id LEFT JOIN publishers p ON p.id=ap.publisher_id LEFT JOIN imprints i ON i.id=ap.imprint_id WHERE c.id=?`).bind(contributorId).first<any>();
  if(!author)throw new ApiError(404,"Author not found.");
  const [links,seriesRows,productRows,follow,affiliation]=await Promise.all([
    db.prepare("SELECT l.link_type,l.label,l.url FROM author_profile_links l JOIN author_profiles ap ON ap.contributor_id=l.contributor_id WHERE l.contributor_id=? AND l.status='active' AND ap.profile_status='active' ORDER BY l.position,l.id").bind(contributorId).all<any>(),
    db.prepare(`SELECT DISTINCT s.id,s.slug,s.name,s.description,s.series_type,s.hero_image_url,COUNT(sm.edition_id) books FROM series s JOIN series_memberships sm ON sm.series_id=s.id JOIN edition_contributors ec ON ec.edition_id=sm.edition_id WHERE ec.contributor_id=? AND ec.role='author' AND s.status='active' GROUP BY s.id ORDER BY MIN(COALESCE(sm.reading_order,sm.position,999999)),s.name LIMIT 50`).bind(contributorId).all<any>(),
    db.prepare(`SELECT p.id product_id,e.release_date,e.preorder_date,e.release_status FROM edition_contributors ec JOIN editions e ON e.id=ec.edition_id JOIN products p ON p.edition_id=e.id WHERE ec.contributor_id=? AND ec.role='author' AND p.storefront_status='active' AND p.source_name<>'upload' ORDER BY COALESCE(e.release_date,e.publication_date,p.created_at) DESC LIMIT 200`).bind(contributorId).all<any>(),
    userId?db.prepare("SELECT f.created_at,COALESCE(fp.release_alerts,1) release_alerts,COALESCE(fp.preorder_alerts,1) preorder_alerts,COALESCE(fp.in_app,1) in_app,COALESCE(fp.email,0) email FROM author_follows f LEFT JOIN author_follow_preferences fp ON fp.user_id=f.user_id AND fp.contributor_id=f.contributor_id WHERE f.user_id=? AND f.contributor_id=?").bind(userId,contributorId).first<any>():Promise.resolve(null),
    db.prepare(`SELECT pub.name publisher_name,pub.slug publisher_slug,imp.name imprint_name,imp.slug imprint_slug,COUNT(*) editions FROM edition_contributors ec JOIN editions e ON e.id=ec.edition_id JOIN products p ON p.edition_id=e.id LEFT JOIN publishers pub ON pub.id=e.publisher_id LEFT JOIN imprints imp ON imp.id=e.imprint_id WHERE ec.contributor_id=? AND ec.role='author' AND p.storefront_status='active' AND e.publisher_id IS NOT NULL GROUP BY e.publisher_id,e.imprint_id ORDER BY editions DESC,MAX(COALESCE(e.release_date,e.publication_date,p.created_at)) DESC LIMIT 1`).bind(contributorId).first<any>(),
  ]);
  const productIds=productRows.results.map((r:any)=>String(r.product_id)), books=await canonicalBooksByProductIds(db,productIds), byId=new Map(books.map((b:any)=>[String(b.productId),b]));
  const nowMs=Date.now(),upcoming:any[]=[],bibliography:any[]=[];
  for(const row of productRows.results){const book=byId.get(String(row.product_id));if(!book)continue;const release=row.release_date?Date.parse(String(row.release_date)):0;const entry={...book,releaseStatus:row.release_status,releaseDate:row.release_date,preorderDate:row.preorder_date};if(release>nowMs||row.release_status==="preorder")upcoming.push(entry);else bibliography.push(entry);}
  return {author:{id:String(author.id),slug:String(author.slug||author.id),name:String(author.name),verified:author.verification_status==="verified"&&author.profile_status==="active",badgeLabel:String(author.badge_label||"Verified Author"),biography:String(author.public_bio||""),photoUrl:String(author.public_photo||""),publisher:(author.publisher_name||affiliation?.publisher_name)?{name:String(author.publisher_name||affiliation?.publisher_name),slug:String(author.publisher_slug||affiliation?.publisher_slug||"")}:null,imprint:(author.imprint_name||affiliation?.imprint_name)?{name:String(author.imprint_name||affiliation?.imprint_name),slug:String(author.imprint_slug||affiliation?.imprint_slug||"")}:null,links:links.results.map((x:any)=>({type:x.link_type,label:x.label,url:x.url})),series:seriesRows.results.map((x:any)=>({id:String(x.id),slug:String(x.slug||x.id),name:String(x.name),description:String(x.description||""),seriesType:String(x.series_type||"ordered"),heroImageUrl:String(x.hero_image_url||""),books:Number(x.books||0)})),followers:Number((await db.prepare("SELECT COUNT(*) n FROM author_follows WHERE contributor_id=?").bind(contributorId).first<any>())?.n||0),following:!!follow,alertPreferences:follow?{release:!!follow.release_alerts,preorder:!!follow.preorder_alerts,inApp:!!follow.in_app,email:!!follow.email}:null},bibliography,upcoming,territory};
}

export async function setAuthorFollow(db:CatalogDB,userId:string,raw:unknown){
  const x=z.object({contributorId:z.string().min(1).max(180),follow:z.boolean(),alerts:z.object({release:z.boolean().default(true),preorder:z.boolean().default(true),inApp:z.boolean().default(true),email:z.boolean().default(false)}).optional()}).parse(raw),author=await db.prepare("SELECT id FROM contributors WHERE id=?").bind(x.contributorId).first<any>();if(!author)throw new ApiError(404,"Author not found.");const at=now();
  if(!x.follow){await db.batch([db.prepare("DELETE FROM author_follows WHERE user_id=? AND contributor_id=?").bind(userId,x.contributorId),db.prepare("DELETE FROM author_follow_preferences WHERE user_id=? AND contributor_id=?").bind(userId,x.contributorId)]);return{following:false};}
  const a=x.alerts||{release:true,preorder:true,inApp:true,email:false};
  await db.batch([db.prepare("INSERT OR IGNORE INTO author_follows(user_id,contributor_id,created_at) VALUES(?,?,?)").bind(userId,x.contributorId,at),db.prepare(`INSERT INTO author_follow_preferences(user_id,contributor_id,release_alerts,preorder_alerts,in_app,email,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,contributor_id) DO UPDATE SET release_alerts=excluded.release_alerts,preorder_alerts=excluded.preorder_alerts,in_app=excluded.in_app,email=excluded.email,updated_at=excluded.updated_at`).bind(userId,x.contributorId,a.release?1:0,a.preorder?1:0,a.inApp?1:0,a.email?1:0,at)]);
  return{following:true,alerts:a};
}

export async function queueAuthorReleaseAlerts(db:CatalogDB){
  const at=now(),state=await db.prepare("SELECT last_scanned_at FROM author_alert_scan_state WHERE id=1").first<any>(),since=String(state?.last_scanned_at||at);
  const [releaseRows,preorderRows]=await Promise.all([
    db.prepare(`SELECT ec.contributor_id,pp.product_id,a.created_at event_at,'release' alert_type FROM publishing_publication_activations a JOIN publishing_publication_versions pv ON pv.id=a.publication_version_id JOIN publishing_publications pp ON pp.id=pv.publication_id JOIN products p ON p.id=pp.product_id JOIN edition_contributors ec ON ec.edition_id=p.edition_id AND ec.role='author' WHERE a.activation_type IN ('initial','schedule') AND a.created_at>? AND a.created_at<=? AND EXISTS(SELECT 1 FROM author_follows f WHERE f.contributor_id=ec.contributor_id)`).bind(since,at).all<any>(),
    db.prepare(`SELECT ec.contributor_id,rp.product_id,rp.opens_at event_at,'preorder_open' alert_type FROM preorder_release_plans rp JOIN products p ON p.id=rp.product_id JOIN edition_contributors ec ON ec.edition_id=p.edition_id AND ec.role='author' WHERE rp.status='open' AND rp.updated_at>? AND rp.updated_at<=? AND EXISTS(SELECT 1 FROM author_follows f WHERE f.contributor_id=ec.contributor_id)`).bind(since,at).all<any>(),
  ]);
  let queued=0;for(const r of [...releaseRows.results,...preorderRows.results]){if(!r.product_id||!r.event_at)continue;const out=await db.prepare("INSERT OR IGNORE INTO author_release_alert_jobs(id,contributor_id,product_id,alert_type,event_at,status,available_at,created_at,updated_at) VALUES(?,?,?,?,?,'pending',?,?,?)").bind(uid("authoralert"),r.contributor_id,r.product_id,r.alert_type,r.event_at,at,at,at).run();queued+=Number((out as any)?.meta?.changes??0);}
  await db.prepare("UPDATE author_alert_scan_state SET last_scanned_at=CASE WHEN last_scanned_at<? THEN ? ELSE last_scanned_at END,updated_at=? WHERE id=1").bind(at,at,at).run();return{queued,scannedFrom:since,scannedThrough:at};
}

export async function processAuthorReleaseAlerts(db:CatalogDB,limit=20){
  const at=now(),jobs=await db.prepare("SELECT * FROM author_release_alert_jobs WHERE status='pending' AND available_at<=? ORDER BY available_at LIMIT ?").bind(at,Math.max(1,Math.min(100,limit))).all<any>();let notifications=0;
  for(const job of jobs.results){await db.prepare("UPDATE author_release_alert_jobs SET status='processing',attempts=attempts+1,updated_at=? WHERE id=? AND status='pending'").bind(at,job.id).run();try{
    const product=await db.prepare("SELECT e.title,p.source_external_id FROM products p JOIN editions e ON e.id=p.edition_id WHERE p.id=?").bind(job.product_id).first<any>();
    const followers=await db.prepare(`SELECT f.user_id,COALESCE(fp.release_alerts,1) release_alerts,COALESCE(fp.preorder_alerts,1) preorder_alerts,COALESCE(fp.in_app,1) in_app,COALESCE(fp.email,0) email FROM author_follows f LEFT JOIN author_follow_preferences fp ON fp.user_id=f.user_id AND fp.contributor_id=f.contributor_id WHERE f.contributor_id=? AND f.user_id>? ORDER BY f.user_id LIMIT 1000`).bind(job.contributor_id,job.cursor_user_id||"").all<any>();
    for(const f of followers.results){const enabled=job.alert_type==="release"?!!f.release_alerts:!!f.preorder_alerts;if(!enabled)continue;const key=`author:${job.contributor_id}:${job.alert_type}:${job.product_id}:${String(job.event_at).slice(0,19)}`,title=job.alert_type==="release"?`New release: ${product?.title||"A followed author"}`:`Preorder open: ${product?.title||"A followed author"}`,message=job.alert_type==="release"?"A book from an author you follow is now available.":"A book from an author you follow is now available for preorder.",allowed=[...(f.in_app?["in_app","web_push","mobile_push"]:[]),...(f.email?["email"]:[])] as any[];if(!allowed.length)continue;await emitNotification(db,{userId:String(f.user_id),eventType:"author_new_book",dedupeKey:key,title,body:message,productId:String(job.product_id),subjectType:"author",subjectId:String(job.contributor_id),actionUrl:product?.source_external_id?`/book/${encodeURIComponent(String(product.source_external_id))}`:"/store",payload:{contributorId:job.contributor_id,productId:job.product_id,eventAt:job.event_at,alertType:job.alert_type},allowedChannels:allowed});notifications++;}
    if(followers.results.length===1000){const cursor=String(followers.results.at(-1)?.user_id||"");await db.prepare("UPDATE author_release_alert_jobs SET status='pending',cursor_user_id=?,available_at=?,updated_at=? WHERE id=?").bind(cursor,at,at,job.id).run();}else await db.prepare("UPDATE author_release_alert_jobs SET status='done',updated_at=? WHERE id=?").bind(at,job.id).run();
  }catch(e){const attempts=Number(job.attempts||0)+1,status=attempts>=5?"dead":"pending",retry=new Date(Date.now()+Math.min(3600,60*Math.pow(2,attempts))*1000).toISOString();await db.prepare("UPDATE author_release_alert_jobs SET status=?,available_at=?,updated_at=? WHERE id=?").bind(status,retry,now(),job.id).run();}}
  return{processed:jobs.results.length,notifications};
}


export async function publisherAuthorProfiles(db:CatalogDB,userId:string,accountId:string){
  const member=await db.prepare("SELECT role FROM publishing_account_members WHERE account_id=? AND user_id=? AND status='active'").bind(accountId,userId).first<any>();if(!member)throw new ApiError(403,"Publisher access is required.");
  const [profiles,links,pens,revisions]=await Promise.all([
    db.prepare(`SELECT ap.*,c.name,c.slug FROM author_profiles ap JOIN contributors c ON c.id=ap.contributor_id WHERE ap.publishing_account_id=? ORDER BY c.name`).bind(accountId).all<any>(),
    db.prepare(`SELECT l.* FROM author_profile_links l JOIN author_profiles ap ON ap.contributor_id=l.contributor_id WHERE ap.publishing_account_id=? AND l.status='active' ORDER BY l.contributor_id,l.position,l.id`).bind(accountId).all<any>(),
    db.prepare("SELECT id,display_name,sort_name,contributor_id,status FROM publishing_pen_names WHERE account_id=? AND status='active' ORDER BY display_name").bind(accountId).all<any>(),
    db.prepare("SELECT * FROM author_profile_revisions WHERE publishing_account_id=? AND status IN ('draft','submitted') ORDER BY contributor_id,revision_number DESC").bind(accountId).all<any>(),
  ]);
  const byContributor=new Map<string,any[]>();for(const l of links.results){const a=byContributor.get(String(l.contributor_id))||[];a.push({type:l.link_type,label:l.label,url:l.url,position:Number(l.position||0)});byContributor.set(String(l.contributor_id),a)}
  const editing=new Map<string,any>();for(const r of revisions.results){const id=String(r.contributor_id);if(editing.has(id))continue;let revLinks:any[]=[];try{const parsed=JSON.parse(String(r.links_json||"[]"));if(Array.isArray(parsed))revLinks=parsed;}catch{}editing.set(id,{...r,links:revLinks});}
  return{penNames:pens.results,profiles:profiles.results.map((x:any)=>({...x,links:byContributor.get(String(x.contributor_id))||[],editingRevision:editing.get(String(x.contributor_id))||null}))};
}

const reviewIntegrityPolicySchema=z.object({
  reviewVelocity:z.object({windowMinutes:z.number().int().min(1).max(1440),count:z.number().int().min(1).max(10000),score:z.number().min(0).max(100)}),
  productBurst:z.object({windowMinutes:z.number().int().min(1).max(1440),distinctUsers:z.number().int().min(2).max(100000),score:z.number().min(0).max(100)}),
  accountCluster:z.object({confidence:z.number().min(0).max(1),score:z.number().min(0).max(100)}),
  publisherCopy:z.object({score:z.number().min(0).max(100)}),
  promotionalCopy:z.object({score:z.number().min(0).max(100)}),
  duplicateText:z.object({minimumCharacters:z.number().int().min(10).max(1000),score:z.number().min(0).max(100)}),
  spam:z.object({urlThreshold:z.number().int().min(1).max(100),hardUrlThreshold:z.number().int().min(1).max(100),score:z.number().min(0).max(100),hardScore:z.number().min(0).max(100)}),
  activeSanction:z.object({score:z.number().min(0).max(100)}),
  voteVelocity:z.object({windowMinutes:z.number().int().min(1).max(1440),count:z.number().int().min(1).max(10000),score:z.number().min(0).max(100)}),
  voteCluster:z.object({confidence:z.number().min(0).max(1),score:z.number().min(0).max(100)}),
  voteReciprocity:z.object({minimumMutualHearts:z.number().int().min(1).max(1000),score:z.number().min(0).max(100)}),
  ranking:z.object({limitedAt:z.number().min(0).max(100),excludedAt:z.number().min(0).max(100),trustDivisor:z.number().positive().max(1000)})
}).strict();
async function activeReviewIntegrityPolicy(db:CatalogDB){const at=now(),row=await db.prepare("SELECT * FROM review_integrity_policy_versions WHERE status='active' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) ORDER BY version DESC LIMIT 1").bind(at,at).first<any>();if(!row)throw new ApiError(503,"Review-integrity policy is not configured.");return{row,policy:reviewIntegrityPolicySchema.parse(JSON.parse(String(row.policy_json||"{}")))};}
export async function createReviewIntegrityPolicyVersion(db:CatalogDB,staff:StaffContext,raw:unknown){const x=z.object({policy:reviewIntegrityPolicySchema,effectiveFrom:z.string().datetime().optional()}).parse(raw),at=now(),effective=x.effectiveFrom||at,canonical=JSON.stringify(x.policy),hash=await sha256Text(canonical),dupe=await db.prepare("SELECT id,version FROM review_integrity_policy_versions WHERE policy_hash=?").bind(hash).first<any>();if(dupe)throw new ApiError(409,`An identical review-integrity policy already exists as ${dupe.id}.`);const next=await db.prepare("SELECT COALESCE(MAX(version),0)+1 n FROM review_integrity_policy_versions").first<any>(),version=Number(next?.n||1),id=`fore-review-integrity-v${version}`;await db.prepare("INSERT INTO review_integrity_policy_versions(id,version,status,policy_json,policy_hash,effective_from,created_by_user_id,created_at) VALUES(?,?,'active',?,?,?,?,?)").bind(id,version,canonical,hash,effective,staff.userId,at).run();return{id,version,policyHash:hash,effectiveFrom:effective};}

export async function resolveReviewIntegritySignal(db:CatalogDB,staff:StaffContext,raw:unknown){
  const x=z.object({signalId:z.string().min(1).max(180),disposition:z.enum(["confirmed","dismissed","mitigated"]),notes:z.string().trim().max(2000).default("")}).parse(raw),at=now();
  const signal=await db.prepare("SELECT * FROM review_abuse_signals WHERE id=?").bind(x.signalId).first<any>();if(!signal)throw new ApiError(404,"Review-integrity signal not found.");
  await db.prepare("UPDATE review_abuse_signals SET disposition=?,reviewed_by_user_id=?,reviewed_at=?,review_notes=?,resolved_at=? WHERE id=?").bind(x.disposition,staff.userId,at,x.notes,at,x.signalId).run();
  if(signal.signal_type==="vote_manipulation"){try{const evidence=JSON.parse(String(signal.evidence_json||"{}"));for(const id of Array.isArray(evidence.voteSignalIds)?evidence.voteSignalIds:[])await db.prepare("UPDATE review_vote_signals SET disposition=?,reviewed_by_user_id=?,reviewed_at=?,review_notes=?,resolved_at=? WHERE id=?").bind(x.disposition,staff.userId,at,x.notes,at,id).run();}catch{}}
  const review=await db.prepare("SELECT id FROM reviews WHERE id=?").bind(signal.review_id).first<any>();
  if(review){
    const {policy}=await activeReviewIntegrityPolicy(db),open=await db.prepare("SELECT MAX(score) max_score FROM review_abuse_signals WHERE review_id=? AND disposition IN ('open','confirmed')").bind(signal.review_id).first<any>();
    const max=Number(open?.max_score||0),status=max>=policy.ranking.excludedAt?"excluded":max>=policy.ranking.limitedAt?"limited":"eligible",trust=Math.max(.05,Math.min(1,1-max/policy.ranking.trustDivisor));
    await db.prepare("UPDATE reviews SET ranking_status=?,trust_score=? WHERE id=?").bind(status,trust,signal.review_id).run();
  }
  const c=await db.prepare("SELECT id FROM moderation_cases WHERE subject_type='review' AND subject_id=? ORDER BY created_at DESC LIMIT 1").bind(signal.review_id).first<any>();
  if(c)await db.prepare("INSERT INTO moderation_notes(id,case_id,staff_user_id,visibility,note,created_at) VALUES(?,?,?,'internal',?,?)").bind(uid("modnote"),c.id,staff.userId,`Integrity signal ${signal.signal_type} ${x.disposition}. ${x.notes}`.trim(),at).run();
  return{signalId:x.signalId,disposition:x.disposition};
}

export async function upsertRetailRiskLink(db:CatalogDB,staff:StaffContext,raw:unknown){
  const x=z.object({userId:z.string().min(1).max(180),linkedUserId:z.string().min(1).max(180),linkType:z.enum(["device","network","payment","household","behavioral","manual"]),confidence:z.number().min(0).max(1),evidenceHash:z.string().regex(/^[a-f0-9]{32,128}$/i).or(z.literal("")),status:z.enum(["active","dismissed","confirmed_abuse"]).default("active")}).parse(raw);
  if(x.userId===x.linkedUserId)throw new ApiError(400,"An account cannot be linked to itself.");const at=now(),pairs=[[x.userId,x.linkedUserId],[x.linkedUserId,x.userId]];
  for(const [a,b] of pairs)await db.prepare(`INSERT INTO retail_account_risk_links(id,user_id,linked_user_id,link_type,confidence,evidence_hash,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,linked_user_id,link_type) DO UPDATE SET confidence=excluded.confidence,evidence_hash=excluded.evidence_hash,status=excluded.status,updated_at=excluded.updated_at`).bind(uid("risklink"),a,b,x.linkType,x.confidence,x.evidenceHash,x.status,at,at).run();
  return{saved:true,userId:x.userId,linkedUserId:x.linkedUserId,status:x.status,reviewedBy:staff.userId};
}

export async function deriveReviewProvenance(db:CatalogDB,userId:string,externalBookId:string){
  let product:any=null;try{product=await resolveProduct(db,externalBookId,userId);}catch{return{type:"sideloaded_unverified",weight:provenanceWeights.sideloaded_unverified,productId:null,entitlementId:null,orderItemId:null,evidence:{reason:"no-commercial-product"}};}
  const at=now(),ent=await db.prepare(`SELECT e.* FROM entitlements e WHERE e.user_id=? AND e.product_id=? AND e.status='active' AND (e.starts_at IS NULL OR e.starts_at<=?) AND (e.ends_at IS NULL OR e.ends_at>?) ORDER BY e.granted_at DESC LIMIT 1`).bind(userId,product.id,at,at).first<any>();
  if(!ent)return{type:"sideloaded_unverified",weight:provenanceWeights.sideloaded_unverified,productId:product.id,entitlementId:null,orderItemId:null,evidence:{reason:"no-entitlement"}};
  const source=String(ent.source||"").toLowerCase(),kind=String(ent.entitlement_type||"").toLowerCase();let type="verified_purchase";
  if(source.includes("author_copy")||source.includes("publisher_copy")||kind.includes("author")||kind.includes("publisher"))type="publisher_author_copy";
  else if(source.includes("gift")||kind.includes("gift"))type="gifted";
  else if(source.includes("promo")||source.includes("promotion")||kind.includes("promo"))type="free_promotional_copy";
  else if(source.includes("subscription")||kind.includes("subscription"))type="subscription_reader";
  else if(ent.order_item_id){const order=await db.prepare(`SELECT o.status,oi.total_minor,oi.discount_minor,oi.id FROM commerce_order_items oi JOIN commerce_orders o ON o.id=oi.order_id WHERE oi.id=? AND o.user_id=?`).bind(ent.order_item_id,userId).first<any>();if(!order||!["paid","partially_refunded"].includes(String(order.status)))type="sideloaded_unverified";else if(Number(order.total_minor||0)<=0)type="free_promotional_copy";}
  else if(source==="public-domain"||source==="personal-import")type="sideloaded_unverified";
  return{type,weight:provenanceWeights[type]??0.35,productId:String(product.id),entitlementId:String(ent.id),orderItemId:ent.order_item_id?String(ent.order_item_id):null,evidence:{entitlementType:ent.entitlement_type,source:ent.source,grantedAt:ent.granted_at}};
}

export async function evaluateReviewIntegrity(db:CatalogDB,reviewId:string,userId:string,productId:string|null,body:string,ratingSteps:number|null,provenanceType:string){
  const at=now(),{row:policyRow,policy}=await activeReviewIntegrityPolicy(db),signals:{type:string;score:number;evidence:any}[]=[];
  await db.prepare("UPDATE review_abuse_signals SET disposition='mitigated',resolved_at=? WHERE review_id=? AND disposition='open'").bind(at,reviewId).run();
  const reviewWindow=`-${policy.reviewVelocity.windowMinutes} minutes`,recentUser=await db.prepare("SELECT COUNT(*) n FROM reviews WHERE user_id=? AND created_at>=datetime('now',?)").bind(userId,reviewWindow).first<any>();
  if(Number(recentUser?.n||0)>=policy.reviewVelocity.count)signals.push({type:"brigade_velocity",score:policy.reviewVelocity.score,evidence:{reviewsInWindow:Number(recentUser.n),windowMinutes:policy.reviewVelocity.windowMinutes,policyVersion:policyRow.id}});
  if(productId){const burstWindow=`-${policy.productBurst.windowMinutes} minutes`,burst=await db.prepare("SELECT COUNT(*) n,COUNT(DISTINCT user_id) users FROM reviews WHERE product_id=? AND created_at>=datetime('now',?)").bind(productId,burstWindow).first<any>();if(Number(burst?.users||0)>=policy.productBurst.distinctUsers)signals.push({type:"rating_burst",score:policy.productBurst.score,evidence:{reviewsInWindow:Number(burst.n),users:Number(burst.users),windowMinutes:policy.productBurst.windowMinutes,policyVersion:policyRow.id}});}
  const links=await db.prepare("SELECT COUNT(*) n,MAX(confidence) confidence FROM retail_account_risk_links WHERE user_id=? AND status IN ('active','confirmed_abuse')").bind(userId).first<any>();if(Number(links?.n||0)>0&&Number(links?.confidence||0)>=policy.accountCluster.confidence)signals.push({type:"suspicious_cluster",score:policy.accountCluster.score,evidence:{linkedAccounts:Number(links.n),confidence:Number(links.confidence),policyVersion:policyRow.id}});
  if(provenanceType==="publisher_author_copy")signals.push({type:"publisher_relationship",score:policy.publisherCopy.score,evidence:{provenanceType,policyVersion:policyRow.id}});
  if(provenanceType==="free_promotional_copy")signals.push({type:"promotional_review",score:policy.promotionalCopy.score,evidence:{provenanceType,policyVersion:policyRow.id}});
  if(body.trim().length>=policy.duplicateText.minimumCharacters){const dupe=await db.prepare("SELECT id FROM reviews WHERE user_id<>? AND lower(trim(body))=lower(trim(?)) AND length(body)>=? LIMIT 1").bind(userId,body,policy.duplicateText.minimumCharacters).first<any>();if(dupe)signals.push({type:"duplicate_text",score:policy.duplicateText.score,evidence:{matchedReviewId:dupe.id,policyVersion:policyRow.id}});}
  const urlCount=(body.match(/https?:\/\//gi)||[]).length,repeated=/([^\s])\1{9,}/.test(body),promo=/\b(?:buy now|discount code|promo code|visit my|check out my)\b/i.test(body);if(urlCount>=policy.spam.urlThreshold||repeated||promo)signals.push({type:"spam",score:urlCount>=policy.spam.hardUrlThreshold||repeated?policy.spam.hardScore:policy.spam.score,evidence:{urlCount,repeated,promotionalPhrase:promo,policyVersion:policyRow.id}});
  const sanction=await db.prepare("SELECT COUNT(*) n FROM moderation_sanctions WHERE user_id=? AND status='active' AND (ends_at IS NULL OR ends_at>?)").bind(userId,at).first<any>();if(Number(sanction?.n||0)>0)signals.push({type:"sanctioned_account",score:policy.activeSanction.score,evidence:{activeSanctions:Number(sanction.n),policyVersion:policyRow.id}});
  for(const sig of signals)await db.prepare("INSERT INTO review_abuse_signals(id,review_id,user_id,product_id,signal_type,score,model_version,evidence_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(uid("reviewsig"),reviewId,userId,productId,sig.type,sig.score,policyRow.id,JSON.stringify(sig.evidence),at).run();
  const persisted=await db.prepare("SELECT MAX(score) max_score FROM review_abuse_signals WHERE review_id=? AND disposition IN ('open','confirmed')").bind(reviewId).first<any>(),max=Math.max(signals.reduce((m,s)=>Math.max(m,s.score),0),Number(persisted?.max_score||0)),trust=Math.max(.05,Math.min(1,1-max/policy.ranking.trustDivisor)),rankingStatus=max>=policy.ranking.excludedAt?"excluded":max>=policy.ranking.limitedAt?"limited":"eligible";
  await db.prepare("UPDATE reviews SET trust_score=?,ranking_status=? WHERE id=?").bind(trust,rankingStatus,reviewId).run();
  if(max>=policy.ranking.limitedAt)await createModerationCase(db as any,{subjectType:"review",subjectId:reviewId,category:"review_integrity",queue:"reviews",priority:max>=policy.ranking.excludedAt?"high":"normal",sourceType:"automated_review_integrity",sourceRef:reviewId,riskScore:max,summary:`Review integrity signals (${signals.map(s=>s.type).join(", ")})`,details:"Automated signals affect ranking weight only; human review is required for enforcement.",evidence:{signals,ratingSteps,policyVersion:policyRow.id,policyHash:policyRow.policy_hash}});
  const communityRisk=await assessCommunityReviewRisk(db,reviewId,"review_integrity");
  return{trustScore:trust,rankingStatus,signals,policyVersion:policyRow.id,communityRisk:{score:communityRisk.score,level:communityRisk.level,action:communityRisk.action}};
}

export async function evaluateReviewHeart(db:CatalogDB,reviewId:string,voterUserId:string){
  const at=now(),{row:policyRow,policy}=await activeReviewIntegrityPolicy(db),signals:{type:string;score:number;evidence:any}[]=[];
  const velocityWindow=`-${policy.voteVelocity.windowMinutes} minutes`,velocity=await db.prepare("SELECT COUNT(*) n FROM review_hearts WHERE user_id=? AND created_at>=datetime('now',?)").bind(voterUserId,velocityWindow).first<any>();if(Number(velocity?.n||0)>=policy.voteVelocity.count)signals.push({type:"velocity",score:policy.voteVelocity.score,evidence:{heartsInWindow:Number(velocity.n),windowMinutes:policy.voteVelocity.windowMinutes,policyVersion:policyRow.id}});
  const review=await db.prepare("SELECT user_id,product_id FROM reviews WHERE id=?").bind(reviewId).first<any>();if(review){const cluster=await db.prepare("SELECT MAX(confidence) confidence FROM retail_account_risk_links WHERE user_id=? AND linked_user_id=? AND status IN ('active','confirmed_abuse')").bind(voterUserId,review.user_id).first<any>();if(Number(cluster?.confidence||0)>=policy.voteCluster.confidence)signals.push({type:"cluster",score:policy.voteCluster.score,evidence:{confidence:Number(cluster.confidence),policyVersion:policyRow.id}});
    const mutual=await db.prepare(`SELECT COUNT(*) n FROM review_hearts h JOIN reviews r ON r.id=h.review_id WHERE h.user_id=? AND r.user_id=?`).bind(review.user_id,voterUserId).first<any>();if(Number(mutual?.n||0)>=policy.voteReciprocity.minimumMutualHearts)signals.push({type:"reciprocity",score:policy.voteReciprocity.score,evidence:{mutualHearts:Number(mutual.n),policyVersion:policyRow.id}});
  }
  const voteSignalIds:string[]=[];for(const sig of signals){const id=uid("votesig");voteSignalIds.push(id);await db.prepare("INSERT INTO review_vote_signals(id,review_id,voter_user_id,signal_type,score,evidence_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(id,reviewId,voterUserId,sig.type,sig.score,JSON.stringify(sig.evidence),at).run();}
  const max=signals.reduce((m,s)=>Math.max(m,s.score),0);if(max>=policy.ranking.limitedAt&&review){const existing=await db.prepare("SELECT id FROM review_abuse_signals WHERE review_id=? AND signal_type='vote_manipulation' AND disposition='open' AND json_extract(evidence_json,'$.voterUserId')=? LIMIT 1").bind(reviewId,voterUserId).first<any>();if(!existing){const sid=uid("reviewsig");await db.prepare("INSERT INTO review_abuse_signals(id,review_id,user_id,product_id,signal_type,score,model_version,evidence_json,created_at) VALUES(?,?,?,?, 'vote_manipulation',?,?,?,?)").bind(sid,reviewId,review.user_id,review.product_id||null,max,policyRow.id,JSON.stringify({voterUserId,voteSignalIds,signals,policyVersion:policyRow.id}),at).run();await createModerationCase(db as any,{subjectType:"review",subjectId:reviewId,category:"review_integrity",queue:"reviews",priority:max>=policy.ranking.excludedAt?"high":"normal",sourceType:"review_vote_integrity",sourceRef:sid,riskScore:max,summary:"Review vote-manipulation signal",details:"Suspicious hearts are excluded from ranking while this signal is open. Human review is required for enforcement.",evidence:{voterUserId,voteSignalIds,signals,policyVersion:policyRow.id,policyHash:policyRow.policy_hash}});}}
  if(signals.length)await assessCommunityReviewRisk(db,reviewId,"review_heart_integrity");
  return signals;
}

const retailPropertyValue=z.union([z.string().max(500),z.number().finite(),z.boolean(),z.null()]);
const retailEventInput=z.object({eventType:z.enum(["search_performed","search_result_clicked","product_viewed","sample_started","sample_completed","wishlist_added","wishlist_removed","cart_added","cart_removed","checkout_started","purchase_completed","refund_completed","book_opened","book_finished","review_submitted","review_hearted","promotion_impression","promotion_clicked"]),anonymousId:z.string().max(120).nullable().optional(),sessionId:z.string().max(120).nullable().optional(),productId:z.string().max(180).nullable().optional(),externalBookId:z.string().max(180).nullable().optional(),queryId:z.string().max(180).nullable().optional(),campaignId:z.string().max(180).nullable().optional(),sourceSurface:z.string().max(100).default(""),sourceRequestId:z.string().max(180).nullable().optional(),territory:z.string().regex(/^[A-Z]{2}$/).default("US"),currency:z.string().regex(/^[A-Z]{3}$/).nullable().optional(),amountMinor:z.number().int().min(-1000000000).max(1000000000).nullable().optional(),quantity:z.number().min(-1000000).max(1000000).default(1),properties:z.record(z.string().max(80),retailPropertyValue).default({}),occurredAt:z.string().datetime().optional(),dedupeKey:z.string().max(240).nullable().optional()});
async function classifyRetailEvent(db:CatalogDB,userId:string|null,x:z.infer<typeof retailEventInput>,origin:"client"|"server"|"worker"){
  const productRequired=new Set(["search_result_clicked","product_viewed","sample_started","sample_completed","wishlist_added","wishlist_removed","cart_added","cart_removed","checkout_started","purchase_completed","refund_completed","book_opened","book_finished","review_submitted","review_hearted","promotion_impression","promotion_clicked"]);
  if(productRequired.has(x.eventType)&&!x.productId)throw new ApiError(400,"This retail event requires a product ID.");
  if(x.productId){const product=await db.prepare("SELECT id,source_external_id,storefront_status FROM products WHERE id=?").bind(x.productId).first<any>();if(!product)throw new ApiError(400,"Retail event product not found.");if(origin==="client"&&String(product.storefront_status)!=="active")throw new ApiError(409,"Retail events cannot target an inactive storefront product.");if(x.externalBookId&&String(product.source_external_id)!==String(x.externalBookId))throw new ApiError(400,"Retail event book/product identity mismatch.");}
  if(origin!=="client")return{eligible:true,weight:1,reason:"server_authoritative"};
  if(!["search_performed","search_result_clicked","product_viewed"].includes(x.eventType))throw new ApiError(403,"That retail event must be emitted by a trusted Cove service.");
  const occurredMs=x.occurredAt?Date.parse(x.occurredAt):Date.now(),skew=occurredMs-Date.now();if(!Number.isFinite(occurredMs)||skew>10*60*1000||skew<-(24*60*60*1000))throw new ApiError(400,"Client retail events must be recent.");
  if(x.eventType==="search_result_clicked"&&!x.queryId)throw new ApiError(400,"Search-result clicks require a query ID.");
  const actor=userId?`u:${userId}`:`a:${x.anonymousId}`,day=new Date(occurredMs).toISOString().slice(0,10),baseWeight=x.eventType==="product_viewed"?.35:x.eventType==="search_result_clicked"?.5:.2,cap=x.eventType==="product_viewed"?4:x.eventType==="search_result_clicked"?12:20;
  const count=await db.prepare(`SELECT COUNT(*) n FROM retail_events WHERE event_origin='client' AND event_type=? AND substr(occurred_at,1,10)=? AND COALESCE('u:'||user_id,'a:'||anonymous_id)=? AND COALESCE(product_id,'')=COALESCE(?, '')`).bind(x.eventType,day,actor,x.productId||null).first<any>();
  if(Number(count?.n||0)>=cap)return{eligible:false,weight:0,reason:"actor_daily_cap"};
  return{eligible:true,weight:baseWeight,reason:"client_capped"};
}

export async function recordRetailEvent(db:CatalogDB,userId:string|null,raw:unknown,origin:"client"|"server"|"worker"="server"){
  const x=retailEventInput.parse(raw);if(!userId&&!x.anonymousId&&!['purchase_completed','refund_completed'].includes(x.eventType))throw new ApiError(400,"Anonymous retail events require an anonymous ID.");
  const forbidden=/pass(word)?|secret|token|email|phone|address|card|ssn|tax/i;for(const key of Object.keys(x.properties))if(forbidden.test(key))throw new ApiError(400,"Sensitive fields are not allowed in retail analytics properties.");
  const id=uid("retevt"),at=now(),occurred=x.occurredAt||at,quality=await classifyRetailEvent(db,userId,x,origin);
  await db.batch([
    db.prepare("INSERT OR IGNORE INTO retail_events(id,event_type,user_id,anonymous_id,session_id,product_id,external_book_id,query_id,campaign_id,source_surface,source_request_id,territory_code,currency,amount_minor,quantity,properties_json,occurred_at,received_at,dedupe_key,event_origin,ranking_eligible,ranking_weight,quality_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,x.eventType,userId,x.anonymousId||null,x.sessionId||null,x.productId||null,x.externalBookId||null,x.queryId||null,x.campaignId||null,x.sourceSurface,x.sourceRequestId||null,x.territory,x.currency||null,x.amountMinor??null,x.quantity,JSON.stringify(x.properties||{}),occurred,at,x.dedupeKey||null,origin,quality.eligible?1:0,quality.weight,quality.reason),
    db.prepare("INSERT OR IGNORE INTO retail_event_outbox(id,event_id,destination,status,available_at,created_at,updated_at) SELECT ?,?,'warehouse','pending',?,?,? WHERE EXISTS(SELECT 1 FROM retail_events WHERE id=?)").bind(uid("retout"),id,at,at,at,id)
  ]);
  const saved=await db.prepare("SELECT id,ranking_eligible FROM retail_events WHERE id=? OR (? IS NOT NULL AND dedupe_key=?) ORDER BY CASE WHEN id=? THEN 0 ELSE 1 END LIMIT 1").bind(id,x.dedupeKey||null,x.dedupeKey||null,id).first<any>();
  return{id:String(saved?.id||id),accepted:true,deduplicated:String(saved?.id||id)!==id,rankingEligible:!!Number(saved?.ranking_eligible??(quality.eligible?1:0))};
}

export async function leaseRetailEventOutbox(db:CatalogDB,raw:unknown){const x=z.object({workerId:z.string().min(1).max(120),limit:z.number().int().min(1).max(500).default(100),leaseSeconds:z.number().int().min(30).max(3600).default(300)}).parse(raw),at=now(),lease=new Date(Date.now()+x.leaseSeconds*1000).toISOString();await db.prepare("UPDATE retail_event_outbox SET status='pending',lease_owner=NULL,lease_expires_at=NULL WHERE status='leased' AND lease_expires_at<=?").bind(at).run();const candidates=await db.prepare("SELECT id FROM retail_event_outbox WHERE status='pending' AND available_at<=? ORDER BY created_at LIMIT ?").bind(at,x.limit).all<any>();for(const row of candidates.results)await db.prepare("UPDATE retail_event_outbox SET status='leased',lease_owner=?,lease_expires_at=?,attempts=attempts+1,updated_at=? WHERE id=? AND status='pending'").bind(x.workerId,lease,at,row.id).run();const acquired=await db.prepare("SELECT o.*,e.* FROM retail_event_outbox o JOIN retail_events e ON e.id=o.event_id WHERE o.status='leased' AND o.lease_owner=? AND o.lease_expires_at=? ORDER BY o.created_at LIMIT ?").bind(x.workerId,lease,x.limit).all<any>();return{events:acquired.results,leaseExpiresAt:lease};}
export async function completeRetailEventOutbox(db:CatalogDB,raw:unknown){const x=z.object({id:z.string().min(1),workerId:z.string().min(1),ok:z.boolean(),error:z.string().max(1000).default("")}).parse(raw),at=now(),row=await db.prepare("SELECT * FROM retail_event_outbox WHERE id=? AND status='leased' AND lease_owner=? AND lease_expires_at>?").bind(x.id,x.workerId,at).first<any>();if(!row)throw new ApiError(409,"Analytics lease is no longer valid.");const dead=!x.ok&&Number(row.attempts||0)>=8,status=x.ok?"delivered":dead?"dead":"pending",available=x.ok?row.available_at:new Date(Date.now()+Math.min(3600,Math.pow(2,Number(row.attempts||1))*30)*1000).toISOString();await db.prepare("UPDATE retail_event_outbox SET status=?,available_at=?,lease_owner=NULL,lease_expires_at=NULL,last_error=?,updated_at=? WHERE id=?").bind(status,available,x.error,at,x.id).run();return{id:x.id,status};}

export async function refreshRetailDailyMetrics(db:CatalogDB,days=90){
  const n=Math.max(1,Math.min(365,Math.floor(days))),from=new Date(Date.now()-(n-1)*86400000).toISOString().slice(0,10),at=now();
  await db.prepare("DELETE FROM retail_daily_product_metrics WHERE metric_date>=?").bind(from).run();
  await db.prepare(`INSERT INTO retail_daily_product_metrics(
    metric_date,territory_code,product_id,product_views,search_clicks,sample_starts,sample_completions,wishlist_adds,wishlist_removes,cart_adds,checkout_starts,purchases,units,gross_revenue_minor,refunds,refund_minor,book_opens,completions,review_count,verified_review_count,weighted_rating_sum,weighted_rating_weight,subscription_units,
    unique_viewers,unique_search_clickers,unique_sample_readers,unique_wishlisters,unique_wishlist_removers,unique_buyers,unique_readers,unique_finishers,trusted_event_count,suppressed_event_count,updated_at)
  SELECT substr(occurred_at,1,10),territory_code,product_id,
    SUM(CASE WHEN event_type='product_viewed' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='search_result_clicked' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='sample_started' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='sample_completed' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='wishlist_added' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='wishlist_removed' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='cart_added' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='checkout_started' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='purchase_completed' AND ranking_eligible=1 THEN 1 ELSE 0 END),
    SUM(CASE WHEN event_type='purchase_completed' AND ranking_eligible=1 THEN quantity ELSE 0 END),
    SUM(CASE WHEN event_type='purchase_completed' AND ranking_eligible=1 THEN COALESCE(amount_minor,0) ELSE 0 END),
    SUM(CASE WHEN event_type='refund_completed' AND ranking_eligible=1 THEN 1 ELSE 0 END),
    SUM(CASE WHEN event_type='refund_completed' AND ranking_eligible=1 THEN ABS(COALESCE(amount_minor,0)) ELSE 0 END),
    SUM(CASE WHEN event_type='book_opened' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='book_finished' AND ranking_eligible=1 THEN ranking_weight ELSE 0 END),
    SUM(CASE WHEN event_type='review_submitted' AND ranking_eligible=1 THEN 1 ELSE 0 END),
    SUM(CASE WHEN event_type='review_submitted' AND ranking_eligible=1 AND json_extract(properties_json,'$.provenanceType') IN ('verified_purchase','subscription_reader') THEN 1 ELSE 0 END),
    SUM(CASE WHEN event_type='review_submitted' AND ranking_eligible=1 THEN COALESCE(json_extract(properties_json,'$.rating'),0)*COALESCE(json_extract(properties_json,'$.weight'),0) ELSE 0 END),
    SUM(CASE WHEN event_type='review_submitted' AND ranking_eligible=1 THEN COALESCE(json_extract(properties_json,'$.weight'),0) ELSE 0 END),0,
    COUNT(DISTINCT CASE WHEN event_type='product_viewed' AND ranking_eligible=1 THEN COALESCE('u:'||user_id,'a:'||anonymous_id) END),
    COUNT(DISTINCT CASE WHEN event_type='search_result_clicked' AND ranking_eligible=1 THEN COALESCE('u:'||user_id,'a:'||anonymous_id) END),
    COUNT(DISTINCT CASE WHEN event_type IN ('sample_started','sample_completed') AND ranking_eligible=1 THEN COALESCE('u:'||user_id,'a:'||anonymous_id) END),
    COUNT(DISTINCT CASE WHEN event_type='wishlist_added' AND ranking_eligible=1 THEN user_id END),
    COUNT(DISTINCT CASE WHEN event_type='wishlist_removed' AND ranking_eligible=1 THEN user_id END),
    COUNT(DISTINCT CASE WHEN event_type='purchase_completed' AND ranking_eligible=1 THEN user_id END),
    COUNT(DISTINCT CASE WHEN event_type='book_opened' AND ranking_eligible=1 THEN user_id END),
    COUNT(DISTINCT CASE WHEN event_type='book_finished' AND ranking_eligible=1 THEN user_id END),
    SUM(CASE WHEN ranking_eligible=1 AND event_origin IN ('server','worker') THEN 1 ELSE 0 END),
    SUM(CASE WHEN ranking_eligible=0 THEN 1 ELSE 0 END),?
  FROM retail_events WHERE product_id IS NOT NULL AND substr(occurred_at,1,10)>=?
  GROUP BY substr(occurred_at,1,10),territory_code,product_id`).bind(at,from).run();
  await db.prepare(`INSERT INTO retail_daily_product_metrics(metric_date,territory_code,product_id,subscription_units,updated_at)
    SELECT substr(occurred_at,1,10),COALESCE(NULLIF(territory_code,''),'US'),product_id,SUM(quantity),?
    FROM finance_usage_events WHERE product_id IS NOT NULL AND source_type IN ('subscription_read','subscription_listen') AND substr(occurred_at,1,10)>=?
    GROUP BY substr(occurred_at,1,10),COALESCE(NULLIF(territory_code,''),'US'),product_id
    ON CONFLICT(metric_date,territory_code,product_id) DO UPDATE SET subscription_units=excluded.subscription_units,updated_at=excluded.updated_at`).bind(at,from).run();
  return{days:n,from};
}

function decay(ageDays:number,halfLife:number){return Math.pow(.5,ageDays/Math.max(.25,halfLife));}
const num=(v:unknown,fallback=0)=>Number.isFinite(Number(v))?Number(v):fallback;
const rankingWeight=z.number().finite().min(-1000).max(1000),rankingHalfLife=z.number().finite().positive().max(365);
const rankingPolicySchema=z.object({
  bestselling:z.object({purchase:rankingWeight,revenueLog:rankingWeight,refund:rankingWeight,decayHalfLifeDays:rankingHalfLife}),
  trending:z.object({purchase:rankingWeight,wishlist:rankingWeight,sampleComplete:rankingWeight,searchClick:rankingWeight,conversion:rankingWeight,refund:rankingWeight,decayHalfLifeDays:rankingHalfLife,minUniqueViewersForConversion:z.number().int().min(1).max(10000).default(3)}),
  mostRead:z.object({open:rankingWeight,completion:rankingWeight,subscription:rankingWeight,decayHalfLifeDays:rankingHalfLife}),
  mostWishlisted:z.object({wishlist:rankingWeight,removal:rankingWeight,decayHalfLifeDays:rankingHalfLife}),
  topRated:z.object({priorMean:z.number().finite().min(1).max(5),priorWeight:z.number().finite().min(0).max(100000),verifiedWeight:z.number().finite().min(0).max(10),subscriptionWeight:z.number().finite().min(0).max(10),promoWeight:z.number().finite().min(0).max(10),unverifiedWeight:z.number().finite().min(0).max(10),minReviews:z.number().int().min(1).max(100000)}),
  newNoteworthy:z.object({trending:rankingWeight,rating:rankingWeight,completion:rankingWeight,maxAgeDays:z.number().finite().positive().max(3650)})
}).strict();
export async function createRetailRankingPolicyVersion(db:CatalogDB,staff:StaffContext,raw:unknown){
  const x=z.object({policy:rankingPolicySchema,effectiveFrom:z.string().datetime().optional()}).parse(raw),at=now(),effective=x.effectiveFrom||at,canonical=JSON.stringify(x.policy),digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(canonical)),hash=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("");
  const duplicate=await db.prepare("SELECT id,version FROM retail_ranking_policy_versions WHERE policy_hash=?").bind(hash).first<any>();if(duplicate)throw new ApiError(409,`An identical ranking policy already exists as ${duplicate.id}.`);
  const row=await db.prepare("SELECT COALESCE(MAX(version),0)+1 next_version FROM retail_ranking_policy_versions").first<any>(),version=Number(row?.next_version||1),id=`fore-ranking-v${version}`;
  await db.prepare("INSERT INTO retail_ranking_policy_versions(id,version,status,policy_json,policy_hash,effective_from,created_by_user_id,created_at) VALUES(?,?,'active',?,?,?,?,?)").bind(id,version,canonical,hash,effective,staff.userId,at).run();
  return{id,version,policyHash:hash,effectiveFrom:effective};
}
export async function refreshRetailRankings(db:CatalogDB,territory="US"){
  territory=territory.toUpperCase();const at=now(),policyRow=await db.prepare("SELECT * FROM retail_ranking_policy_versions WHERE status='active' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) ORDER BY version DESC LIMIT 1").bind(at,at).first<any>();
  if(!policyRow)throw new ApiError(503,"No active Cove ranking policy.");
  let policy:any;try{policy=rankingPolicySchema.parse(JSON.parse(String(policyRow.policy_json||"{}")));}catch{throw new ApiError(503,"Active Cove ranking policy is invalid.");}
  const b=policy.bestselling||{},t=policy.trending||{},mr=policy.mostRead||{},mw=policy.mostWishlisted||{},tr=policy.topRated||{},nn=policy.newNoteworthy||{};
  const rows=await db.prepare(`SELECT m.*,CASE WHEN p.source_name='fore_publishing' THEN COALESCE((SELECT MIN(a.created_at) FROM publishing_publication_activations a JOIN publishing_publication_versions pv ON pv.id=a.publication_version_id JOIN publishing_publications pp ON pp.id=pv.publication_id WHERE pp.product_id=p.id),(SELECT MIN(pp.published_at) FROM publishing_publications pp WHERE pp.product_id=p.id),p.created_at) ELSE COALESCE(e.publication_date,p.created_at) END first_live_at FROM retail_daily_product_metrics m JOIN products p ON p.id=m.product_id JOIN editions e ON e.id=p.edition_id WHERE m.territory_code=? AND m.metric_date>=date('now','-90 days') AND p.storefront_status='active' AND p.source_name<>'upload'`).bind(territory).all<any>(),map=new Map<string,any>();
  for(const r of rows.results){
    const id=String(r.product_id),x=map.get(id)||{productId:id,bestselling:0,trending:0,read:0,wishlist:0,completions:0,views:0,purchases:0,releaseDate:r.first_live_at};
    const age=Math.max(0,(Date.now()-Date.parse(String(r.metric_date)+"T12:00:00Z"))/86400000),purchases=num(r.purchases),views=num(r.unique_viewers),buyers=num(r.unique_buyers),refunds=num(r.refunds),conversion=views>=num(t.minUniqueViewersForConversion,3)?Math.min(1,buyers/views):0,wishlisters=num(r.unique_wishlisters),wishlistRemovers=num(r.unique_wishlist_removers),sampleReaders=num(r.unique_sample_readers),searchClickers=num(r.unique_search_clickers),readers=num(r.unique_readers),finishers=num(r.unique_finishers);
    x.bestselling+=(purchases*num(b.purchase,8)+Math.log1p(Math.max(0,num(r.gross_revenue_minor))/100)*num(b.revenueLog,2.5)+refunds*num(b.refund,-10))*decay(age,num(b.decayHalfLifeDays,7));
    x.trending+=(purchases*num(t.purchase,6)+wishlisters*num(t.wishlist,2)+sampleReaders*num(t.sampleComplete,1.5)+searchClickers*num(t.searchClick,.5)+conversion*num(t.conversion,4)+refunds*num(t.refund,-8))*decay(age,num(t.decayHalfLifeDays,2));
    x.read+=(readers*num(mr.open,.2)+finishers*num(mr.completion,5)+num(r.subscription_units)*num(mr.subscription,2))*decay(age,num(mr.decayHalfLifeDays,14));
    x.wishlist+=(wishlisters*num(mw.wishlist,1)+wishlistRemovers*num(mw.removal,-1))*decay(age,num(mw.decayHalfLifeDays,14));x.completions+=finishers;x.views+=views;x.purchases+=purchases;map.set(id,x);
  }
  const reviewRows=await db.prepare(`SELECT p.id product_id,r.rating_steps,r.provenance_type,r.provenance_weight,r.trust_score FROM reviews r JOIN products p ON p.source_external_id=r.book_id WHERE r.visibility='public' AND r.moderation='visible' AND r.ranking_status<>'excluded' AND r.rating_steps IS NOT NULL AND p.storefront_status='active'`).all<any>(),reviewMap=new Map<string,{rating_sum:number;rating_weight:number;reviews:number}>();
  for(const r of reviewRows.results){const type=String(r.provenance_type||"sideloaded_unverified"),policyWeight=type==="verified_purchase"?num(tr.verifiedWeight,1):type==="subscription_reader"?num(tr.subscriptionWeight,.9):type==="free_promotional_copy"?num(tr.promoWeight,.65):type==="sideloaded_unverified"?num(tr.unverifiedWeight,.35):num(r.provenance_weight,.35),weight=Math.max(0,policyWeight)*Math.max(.05,Math.min(1,num(r.trust_score,1))),id=String(r.product_id),agg=reviewMap.get(id)||{rating_sum:0,rating_weight:0,reviews:0};agg.rating_sum+=(num(r.rating_steps)/2)*weight;agg.rating_weight+=weight;agg.reviews+=1;reviewMap.set(id,agg);}
  const allProducts=await db.prepare(`SELECT p.id,CASE WHEN p.source_name='fore_publishing' THEN COALESCE((SELECT MIN(a.created_at) FROM publishing_publication_activations a JOIN publishing_publication_versions pv ON pv.id=a.publication_version_id JOIN publishing_publications pp ON pp.id=pv.publication_id WHERE pp.product_id=p.id),(SELECT MIN(pp.published_at) FROM publishing_publications pp WHERE pp.product_id=p.id),p.created_at) ELSE COALESCE(e.publication_date,p.created_at) END first_live_at FROM products p JOIN editions e ON e.id=p.edition_id WHERE p.storefront_status='active' AND p.source_name<>'upload'`).all<any>();
  for(const p of allProducts.results){const id=String(p.id),x=map.get(id)||{productId:id,bestselling:0,trending:0,read:0,wishlist:0,completions:0,views:0,purchases:0,releaseDate:p.first_live_at},rr=reviewMap.get(id) as any,weight=num(rr?.rating_weight),sum=num(rr?.rating_sum),reviewCount=num(rr?.reviews),priorMean=num(tr.priorMean,3.8),priorWeight=num(tr.priorWeight,10);x.rating=(priorMean*priorWeight+sum)/(priorWeight+weight);x.reviewCount=reviewCount;x.ratingEligible=reviewCount>=Math.max(1,num(tr.minReviews,3));x.ratingScore=x.ratingEligible?x.rating:0;const releaseMs=Date.parse(String(x.releaseDate||"")),ageDays=Number.isFinite(releaseMs)?Math.max(0,(Date.now()-releaseMs)/86400000):9999;const completionSignal=Math.log1p(x.completions);x.noteworthy=ageDays<=num(nn.maxAgeDays,90)?x.trending*num(nn.trending,.5)+x.ratingScore*num(nn.rating,.3)+completionSignal*num(nn.completion,.2):0;x.conversion=x.views>0?x.purchases/x.views:0;map.set(id,x);}
  const values=[...map.values()],charts:{key:string,field:string}[]=[{key:"bestselling",field:"bestselling"},{key:"trending",field:"trending"},{key:"most_read",field:"read"},{key:"most_wishlisted",field:"wishlist"},{key:"new_noteworthy",field:"noteworthy"},{key:"top_rated",field:"ratingScore"}],statements:any[]=[];
  for(const x of values)statements.push(db.prepare("UPDATE catalog_search_documents SET fore_bestseller_score=?,fore_trending_score=?,fore_read_score=?,fore_wishlist_score=?,fore_rating_score=?,fore_noteworthy_score=?,sales_velocity=?,updated_at=updated_at WHERE product_id=?").bind(x.bestselling,x.trending,x.read,x.wishlist,x.ratingScore,x.noteworthy,x.trending,x.productId));if(statements.length)await db.batch(statements);
  for(const chart of charts){const snapshotId=uid("ranksnap"),start=new Date(Date.now()-90*86400000).toISOString();await db.prepare("INSERT INTO retail_ranking_snapshots(id,chart_key,territory_code,category_key,window_start,window_end,policy_version_id,generated_at,source_watermark_at) VALUES(?,?,?,'',?,?,?,?,?)").bind(snapshotId,chart.key,territory,start,at,policyRow.id,at,at).run();const ranked=values.filter(x=>num(x[chart.field])>0).sort((a,b)=>num(b[chart.field])-num(a[chart.field])).slice(0,100);let rank=1;for(const x of ranked){await db.batch([db.prepare("INSERT INTO retail_ranking_entries(snapshot_id,product_id,rank,score,components_json) VALUES(?,?,?,?,?)").bind(snapshotId,x.productId,rank,num(x[chart.field]),JSON.stringify({bestselling:x.bestselling,trending:x.trending,read:x.read,wishlist:x.wishlist,rating:x.rating,ratingScore:x.ratingScore,reviewCount:x.reviewCount,ratingEligible:x.ratingEligible,noteworthy:x.noteworthy,conversion:x.conversion,policyHash:policyRow.policy_hash})),db.prepare("INSERT INTO product_rankings(product_id,ranking_scope,ranking_key,rank,score,window,updated_at) VALUES(?,?, '',?,?,'current',?) ON CONFLICT(product_id,ranking_scope,ranking_key,window) DO UPDATE SET rank=excluded.rank,score=excluded.score,updated_at=excluded.updated_at").bind(x.productId,chart.key,rank,num(x[chart.field]),at)]);rank++;}}
  return{territory,products:values.length,policyVersion:policyRow.id,policyHash:policyRow.policy_hash,generatedAt:at};
}

export async function retailChart(db:CatalogDB,chart:string,territory="US",limit=100){const key=z.enum(["bestselling","trending","most_read","most_wishlisted","new_noteworthy","top_rated"]).parse(chart),snap=await db.prepare("SELECT * FROM retail_ranking_snapshots WHERE chart_key=? AND territory_code=? AND category_key='' ORDER BY generated_at DESC LIMIT 1").bind(key,territory.toUpperCase()).first<any>();if(!snap)return{chart:key,generatedAt:null,books:[]};const entries=await db.prepare("SELECT * FROM retail_ranking_entries WHERE snapshot_id=? ORDER BY rank LIMIT ?").bind(snap.id,Math.min(100,Math.max(1,limit))).all<any>(),books=await canonicalBooksByProductIds(db,entries.results.map((x:any)=>String(x.product_id))),byId=new Map(books.map((b:any)=>[String(b.productId),b]));return{chart:key,generatedAt:snap.generated_at,policyVersion:snap.policy_version_id,books:entries.results.map((e:any)=>({rank:Number(e.rank),score:Number(e.score),book:byId.get(String(e.product_id)),components:JSON.parse(String(e.components_json||"{}"))})).filter((x:any)=>x.book)};}

export async function retailIntelligenceStatus(db:CatalogDB){const [events,pending,snapshots,signals,authors,pendingAuthors,signalRows,activePolicy,activeReviewPolicy]=await Promise.all([db.prepare("SELECT event_type,COUNT(*) count FROM retail_events WHERE occurred_at>=datetime('now','-1 day') GROUP BY event_type ORDER BY event_type").all<any>(),db.prepare("SELECT status,COUNT(*) count FROM retail_event_outbox GROUP BY status").all<any>(),db.prepare("SELECT chart_key,territory_code,MAX(generated_at) generated_at FROM retail_ranking_snapshots GROUP BY chart_key,territory_code ORDER BY chart_key,territory_code").all<any>(),db.prepare("SELECT signal_type,COUNT(*) count,AVG(score) avg_score FROM review_abuse_signals WHERE disposition='open' GROUP BY signal_type ORDER BY count DESC").all<any>(),db.prepare("SELECT verification_status,profile_status,COUNT(*) count FROM author_profiles GROUP BY verification_status,profile_status").all<any>(),db.prepare(`SELECT r.id revision_id,r.contributor_id,c.name,r.publishing_account_id,pa.display_name publisher_name,ap.profile_status,ap.verification_status,r.revision_number,r.biography,r.photo_url,r.links_json,r.content_sha256,r.submitted_at,r.updated_at FROM author_profile_revisions r JOIN author_profiles ap ON ap.contributor_id=r.contributor_id JOIN contributors c ON c.id=r.contributor_id LEFT JOIN publishing_accounts pa ON pa.id=r.publishing_account_id WHERE r.status='submitted' ORDER BY r.submitted_at,r.revision_number LIMIT 100`).all<any>(),db.prepare(`SELECT s.id,s.review_id,s.user_id,s.product_id,s.signal_type,s.score,s.model_version,s.evidence_json,s.created_at,r.body,r.rating_steps,r.provenance_type,u.name reviewer_name FROM review_abuse_signals s JOIN reviews r ON r.id=s.review_id LEFT JOIN profiles u ON u.user_id=s.user_id WHERE s.disposition='open' ORDER BY s.score DESC,s.created_at LIMIT 200`).all<any>(),db.prepare("SELECT id,version,policy_hash,effective_from,created_at FROM retail_ranking_policy_versions WHERE status='active' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) ORDER BY version DESC LIMIT 1").bind(now(),now()).first<any>(),db.prepare("SELECT id,version,policy_hash,effective_from,created_at FROM review_integrity_policy_versions WHERE status='active' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) ORDER BY version DESC LIMIT 1").bind(now(),now()).first<any>()]);return{eventsLast24h:events.results,outbox:pending.results,rankingSnapshots:snapshots.results,openReviewSignals:signals.results,authorProfiles:authors.results,pendingAuthorProfiles:pendingAuthors.results,reviewSignalQueue:signalRows.results,activeRankingPolicy:activePolicy||null,activeReviewIntegrityPolicy:activeReviewPolicy||null};}
