import { FormEvent, useEffect, useState } from "react";
import { api } from "./client";
import { CheckCircle2, FileWarning, Loader2, ShieldCheck } from "lucide-react";

type Policy={policy_key:string;version:string;title:string;summary:string;rules:any;effective_at:string;published_at:string};
type NoticeReceipt={id:string;disputeId:string;caseId:string;status:string;subjectType:string;subjectId:string};
const blank={reportedUrl:"",claimantName:"",claimantEmail:"",claimantPhone:"",line1:"",line2:"",city:"",region:"",postalCode:"",countryCode:"US",representedParty:"",workTitle:"",workAuthor:"",registration:"",workDescription:"",materialDescription:"",rightsBasis:"",signatureName:"",goodFaith:false,accuracy:false,authority:false};

export function CopyrightNoticePage(){
  const [x,setX]=useState(blank),[busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState<NoticeReceipt|null>(null),[contact,setContact]=useState<any>(null);
  useEffect(()=>{void api<any>("/rights/contact").then(r=>setContact(r.designatedAgent||null)).catch(()=>{});},[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await api<NoticeReceipt>("/rights/copyright-notice","POST",{reportedUrl:x.reportedUrl,legalRegime:"us_dmca",claimantName:x.claimantName,claimantEmail:x.claimantEmail,claimantPhone:x.claimantPhone,claimantAddress:{line1:x.line1,line2:x.line2,city:x.city,region:x.region,postalCode:x.postalCode,countryCode:x.countryCode},representedParty:x.representedParty,copyrightedWorks:[{title:x.workTitle,author:x.workAuthor,registrationOrReference:x.registration,description:x.workDescription}],infringingMaterial:[{url:x.reportedUrl,description:x.materialDescription,location:x.reportedUrl}],rightsBasis:x.rightsBasis,goodFaithAttestation:x.goodFaith,accuracyPerjuryAttestation:x.accuracy,authorityAttestation:x.authority,signatureName:x.signatureName});setReceipt(r);}catch(err){setError((err as Error).message);}finally{setBusy(false)}}
  if(receipt)return <div className="publishing-empty publishing-create"><CheckCircle2 size={42}/><h1>Copyright notice received</h1><p>Cove created dispute <strong>{receipt.disputeId}</strong> and moderation case <strong>{receipt.caseId}</strong>. Keep these references for correspondence.</p><p className="muted">Receipt status: {receipt.status}. Submission is not a determination of infringement; staff validate notices before applying the notice-and-takedown workflow.</p><button className="button outline" onClick={()=>{setReceipt(null);setX(blank)}}>Submit another notice</button></div>;
  return <div className="publishing-workspace"><div className="publishing-hero"><div><span className="small-label">RIGHTSHOLDER OPERATIONS</span><h1>Copyright / DMCA notice</h1><p>Use this form to identify specific material on Cove that you believe infringes copyright. Cove records the notice, validates required elements, links it to the affected publication, and tracks any takedown, counter-notice, court-action hold, restoration, and dispute resolution.</p></div><FileWarning size={46}/></div>
    <div className="publishing-modal-card"><p><strong>Before submitting:</strong> provide the exact Cove URL and enough information to identify your copyrighted work. U.S. DMCA notices require good-faith, accuracy/perjury, and authority attestations. This intake is operational tooling, not legal advice.</p>{contact&&(contact.name||contact.email||contact.address)&&<p className="muted"><strong>Designated copyright agent:</strong> {[contact.name,contact.email,contact.phone,contact.address].filter(Boolean).join(" · ")}</p>}</div>
    <form className="publishing-modal-card publishing-editor-form" onSubmit={submit}><div className="publishing-form-grid">
      <label className="wide">Cove URL<input type="url" required placeholder="https://…/book/…" value={x.reportedUrl} onChange={e=>setX({...x,reportedUrl:e.target.value})}/></label>
      <label>Claimant name<input required value={x.claimantName} onChange={e=>setX({...x,claimantName:e.target.value})}/></label><label>Email<input type="email" required value={x.claimantEmail} onChange={e=>setX({...x,claimantEmail:e.target.value})}/></label><label>Phone<input required value={x.claimantPhone} onChange={e=>setX({...x,claimantPhone:e.target.value})}/></label><label>Represented party, if any<input value={x.representedParty} onChange={e=>setX({...x,representedParty:e.target.value})}/></label>
      <label>Address line 1<input required value={x.line1} onChange={e=>setX({...x,line1:e.target.value})}/></label><label>Address line 2<input value={x.line2} onChange={e=>setX({...x,line2:e.target.value})}/></label><label>City<input required value={x.city} onChange={e=>setX({...x,city:e.target.value})}/></label><label>State / region<input value={x.region} onChange={e=>setX({...x,region:e.target.value})}/></label><label>Postal code<input required value={x.postalCode} onChange={e=>setX({...x,postalCode:e.target.value})}/></label><label>Country code<input required maxLength={2} value={x.countryCode} onChange={e=>setX({...x,countryCode:e.target.value.toUpperCase()})}/></label>
      <label>Copyrighted work title<input required value={x.workTitle} onChange={e=>setX({...x,workTitle:e.target.value})}/></label><label>Author / creator<input value={x.workAuthor} onChange={e=>setX({...x,workAuthor:e.target.value})}/></label><label className="wide">Registration or reference<input value={x.registration} onChange={e=>setX({...x,registration:e.target.value})}/></label><label className="wide">Describe the copyrighted work<textarea value={x.workDescription} onChange={e=>setX({...x,workDescription:e.target.value})}/></label><label className="wide">Describe the material you want reviewed<textarea required value={x.materialDescription} onChange={e=>setX({...x,materialDescription:e.target.value})}/></label><label className="wide">Basis for your rights / authority<textarea required value={x.rightsBasis} onChange={e=>setX({...x,rightsBasis:e.target.value})}/></label><label className="wide">Electronic signature<input required value={x.signatureName} onChange={e=>setX({...x,signatureName:e.target.value})}/></label>
    </div><div className="publishing-form"><label className="publishing-check"><input type="checkbox" required checked={x.goodFaith} onChange={e=>setX({...x,goodFaith:e.target.checked})}/> I have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law.</label><label className="publishing-check"><input type="checkbox" required checked={x.accuracy} onChange={e=>setX({...x,accuracy:e.target.checked})}/> I state under penalty of perjury that this notice is accurate.</label><label className="publishing-check"><input type="checkbox" required checked={x.authority} onChange={e=>setX({...x,authority:e.target.checked})}/> I am the copyright owner or authorized to act for the owner.</label></div>{error&&<p className="error-text" role="alert">{error}</p>}<button className="button gold" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<ShieldCheck size={16}/>} Submit copyright notice</button></form>
    <div className="publishing-modal-card"><h2>What happens next</h2><p>Cove staff validate the notice. A compliant notice can disable the affected content and place a scoped royalty hold. Where the U.S. DMCA counter-notice process applies, an eligible publisher can counter-notify; after Cove forwards a compliant counter-notice, restoration is tracked through the applicable 10–14 business-day window unless qualifying court action is recorded.</p></div>
  </div>;
}

export function PublishingPolicyPage(){
  const [policies,setPolicies]=useState<Policy[]>([]);useEffect(()=>{void api<{policies:Policy[]}>("/publishing/policies").then(r=>setPolicies(r.policies||[])).catch(()=>{});},[]);
  const ai=policies.find(p=>p.policy_key==="ai_content"),rights=policies.find(p=>p.policy_key==="publisher_rights"),repeat=policies.find(p=>p.policy_key==="repeat_infringer");
  return <div className="publishing-workspace"><div className="publishing-hero"><div><span className="small-label">FORE PUBLISHING POLICY</span><h1>AI, automated content & publishing integrity</h1><p>Cove uses an explicit, versioned policy so publishers, reviewers, and automated systems are evaluated against the same rules.</p></div><ShieldCheck size={46}/></div>
    <section className="publishing-modal-card"><h2>What Cove permits</h2><p><strong>Human-created content:</strong> permitted, subject to normal rights, quality, and metadata rules.</p><p><strong>AI-assisted content:</strong> permitted. Publishers disclose assistance to Cove, but Cove does not add a customer-facing AI badge solely for assistance.</p><p><strong>AI-generated text, cover art, or translation:</strong> permitted when accurately disclosed, lawfully sourced, meaningfully reviewed by a human, non-misleading, and not part of spammy or low-value derivative flooding. Generated elements are disclosed to customers on the published edition.</p><p><strong>AI-generated narration:</strong> permitted only when the publisher has the required rights and supplies a customer-facing synthetic-voice label.</p></section>
    <section className="publishing-modal-card"><h2>What Cove prohibits</h2><p>Piracy or plagiarism; impersonation; undeclared generated content; misleading author, edition, series, or provenance metadata; mass-produced spam; substantially duplicative or low-value derivative books intended to game discovery; and attempts to evade prior sanctions through linked publisher accounts.</p></section>
    <section className="publishing-modal-card"><h2>How enforcement works</h2><p>Asset hashes, normalized-text fingerprints, similarity matches, identity-name similarity, account-link signals, publishing velocity, customer reports, and other risk signals can route a title or publisher to review. Similarity is evidence for investigation—not by itself a legal finding of infringement. High-risk adverse actions are reviewable by staff and recorded in immutable audit history. Publishers can appeal eligible moderation decisions.</p><p>Copyright disputes are handled separately through Cove's <a href="/copyright">rightsholder notice process</a>, including takedown, counter-notice where applicable, scoped royalty holds, restoration tracking, and repeat-infringer controls.</p></section>
    <section className="publishing-modal-card"><h2>Current machine-readable policy versions</h2>{policies.length?policies.map(p=><div className="publishing-admin-row" key={p.policy_key}><div><strong>{p.title}</strong><span>{p.version} · effective {new Date(p.effective_at).toLocaleDateString()}</span><p>{p.summary}</p></div></div>):<p className="muted">Loading policy registry…</p>}</section>
    {(ai||rights||repeat)&&<p className="muted">Active policy registry: {[rights?.version,ai?.version,repeat?.version].filter(Boolean).join(" · ")}. Published policy text is immutable; Cove issues a new version when rules change.</p>}
  </div>;
}
