import { z } from "zod";
import type { CoveEnv } from "./api.server";
import { ApiError, now } from "./service";

type DB=CoveEnv["DB"];
const uid=(p:string)=>`${p}_${crypto.randomUUID()}`;
const severitySchema=z.enum(["critical","high","medium","low","info"]);

function parseJson(v:any,f:any){try{return JSON.parse(String(v??""));}catch{return f;}}

export async function securityOperationsSnapshot(db:DB){
  const [program,threatModels,threats,edge,headers,secrets,rotations,scans,findings,sboms,provenance,pentests,disclosures,plans,incidents,malware,publisherPolicies]=await Promise.all([
    db.prepare("SELECT * FROM security_program_versions ORDER BY version DESC LIMIT 20").all<any>(),
    db.prepare("SELECT * FROM security_threat_models ORDER BY created_at DESC LIMIT 100").all<any>(),
    db.prepare("SELECT * FROM security_threats ORDER BY CASE status WHEN 'open' THEN 0 ELSE 1 END,risk_score DESC,updated_at DESC LIMIT 500").all<any>(),
    db.prepare("SELECT * FROM security_edge_controls ORDER BY environment,provider").all<any>(),
    db.prepare("SELECT * FROM security_header_policies ORDER BY environment").all<any>(),
    db.prepare("SELECT id,secret_key,owner_team,environment,provider,secret_manager_reference,purpose,rotation_days,last_rotated_at,next_rotation_at,status,created_at,updated_at FROM security_secret_inventory ORDER BY next_rotation_at").all<any>(),
    db.prepare("SELECT * FROM security_key_rotation_events ORDER BY occurred_at DESC LIMIT 200").all<any>(),
    db.prepare("SELECT * FROM security_scans ORDER BY created_at DESC LIMIT 500").all<any>(),
    db.prepare("SELECT * FROM security_findings WHERE status IN ('open','triaged','accepted') ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END,due_at LIMIT 500").all<any>(),
    db.prepare("SELECT * FROM security_sboms ORDER BY generated_at DESC LIMIT 100").all<any>(),
    db.prepare("SELECT * FROM security_build_provenance ORDER BY created_at DESC LIMIT 100").all<any>(),
    db.prepare("SELECT * FROM security_pentest_engagements ORDER BY starts_at DESC LIMIT 100").all<any>(),
    db.prepare("SELECT * FROM security_disclosure_reports ORDER BY created_at DESC LIMIT 200").all<any>(),
    db.prepare("SELECT * FROM security_incident_response_plans ORDER BY version DESC").all<any>(),
    db.prepare("SELECT * FROM security_incidents ORDER BY declared_at DESC LIMIT 200").all<any>(),
    db.prepare(`SELECT s.*,v.original_filename,v.sha256,v.quarantine_status,a.kind,a.edition_id FROM security_scans s JOIN publishing_asset_versions v ON v.id=s.target_id JOIN publishing_assets a ON a.id=v.asset_id WHERE s.scan_type='malware' ORDER BY s.created_at DESC LIMIT 300`).all<any>().catch(()=>({results:[]} as any)),
    db.prepare("SELECT p.*,a.display_name FROM publisher_security_policies p JOIN publishing_accounts a ON a.id=p.account_id ORDER BY a.display_name").all<any>(),
  ]);
  return{program:program.results,threatModels:threatModels.results.map((r:any)=>({...r,trustBoundaries:parseJson(r.trust_boundaries_json,[]),dataFlows:parseJson(r.data_flows_json,[]),assumptions:parseJson(r.assumptions_json,[])})),threats:threats.results.map((r:any)=>({...r,controls:parseJson(r.controls_json,[])})),edgeControls:edge.results,headerPolicies:headers.results,secrets:secrets.results,keyRotations:rotations.results,scans:scans.results,findings:findings.results,sboms:sboms.results,provenance:provenance.results,pentests:pentests.results,disclosures:disclosures.results,incidentResponsePlans:plans.results,incidents:incidents.results,malwareEvidence:malware.results,publisherPolicies:publisherPolicies.results};
}

export async function saveThreatModel(db:DB,actorUserId:string,raw:unknown){
  const x=z.object({systemKey:z.string().min(2).max(120),version:z.number().int().positive(),status:z.enum(["draft","review","approved","superseded"]).default("draft"),trustBoundaries:z.array(z.any()).max(100).default([]),dataFlows:z.array(z.any()).max(300).default([]),assumptions:z.array(z.string().max(1000)).max(100).default([])}).parse(raw),program=await db.prepare("SELECT id FROM security_program_versions WHERE status='active' ORDER BY version DESC LIMIT 1").first<any>();if(!program)throw new ApiError(409,"Activate a security program version first.");const id=`threatmodel_${x.systemKey.replace(/[^a-zA-Z0-9_-]/g,"_")}_${x.version}`,at=now();await db.prepare(`INSERT INTO security_threat_models(id,program_version_id,system_key,version,status,trust_boundaries_json,data_flows_json,assumptions_json,approved_by_user_id,approved_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(system_key,version) DO UPDATE SET status=excluded.status,trust_boundaries_json=excluded.trust_boundaries_json,data_flows_json=excluded.data_flows_json,assumptions_json=excluded.assumptions_json,approved_by_user_id=excluded.approved_by_user_id,approved_at=excluded.approved_at`).bind(id,program.id,x.systemKey,x.version,x.status,JSON.stringify(x.trustBoundaries),JSON.stringify(x.dataFlows),JSON.stringify(x.assumptions),x.status==="approved"?actorUserId:null,x.status==="approved"?at:null,at).run();return{id,status:x.status};
}

export async function saveThreat(db:DB,raw:unknown){const x=z.object({id:z.string().optional(),threatModelId:z.string().min(1),category:z.enum(["spoofing","tampering","repudiation","information_disclosure","denial_of_service","elevation_of_privilege","fraud","supply_chain","privacy"]),title:z.string().min(1).max(300),scenario:z.string().min(1).max(10000),likelihood:z.number().int().min(1).max(5),impact:z.number().int().min(1).max(5),treatment:z.enum(["mitigate","accept","transfer","avoid"]),status:z.enum(["open","mitigated","accepted","closed"]).default("open"),ownerTeam:z.string().min(1).max(120),controls:z.array(z.string().max(200)).max(100).default([])}).parse(raw),at=now(),id=x.id||uid("threat");await db.prepare(`INSERT INTO security_threats(id,threat_model_id,category,title,scenario,likelihood,impact,risk_score,treatment,status,owner_team,controls_json,reviewed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category=excluded.category,title=excluded.title,scenario=excluded.scenario,likelihood=excluded.likelihood,impact=excluded.impact,risk_score=excluded.risk_score,treatment=excluded.treatment,status=excluded.status,owner_team=excluded.owner_team,controls_json=excluded.controls_json,reviewed_at=excluded.reviewed_at,updated_at=excluded.updated_at`).bind(id,x.threatModelId,x.category,x.title,x.scenario,x.likelihood,x.impact,x.likelihood*x.impact,x.treatment,x.status,x.ownerTeam,JSON.stringify(x.controls),at,at,at).run();return{id,riskScore:x.likelihood*x.impact};}


export async function verifySecurityHeaders(db:DB,actorUserId:string|null,raw:unknown){
  const x=z.object({environment:z.enum(["development","staging","production"]),observed:z.object({csp:z.string().max(12000),hsts:z.string().max(2000).default(""),permissionsPolicy:z.string().max(4000),referrerPolicy:z.string().max(1000),crossOriginOpenerPolicy:z.string().max(1000),crossOriginResourcePolicy:z.string().max(1000)}),evidenceReference:z.string().min(1).max(1000),scanner:z.string().max(200).default("external-header-probe")}).parse(raw);
  const expected=await db.prepare("SELECT * FROM security_header_policies WHERE environment=? AND status='active'").bind(x.environment).first<any>();if(!expected)throw new ApiError(404,"No active security-header policy exists for this environment.");
  const norm=(v:string)=>v.toLowerCase().replace(/\s+/g," ").trim(),has=(actual:string,part:string)=>norm(actual).includes(norm(part));
  const failures:string[]=[];for(const required of ["default-src 'self'","object-src 'none'","base-uri 'self'","frame-ancestors 'none'"])if(!has(x.observed.csp,required))failures.push(`csp:${required}`);
  for(const required of ["camera=()","microphone=()","geolocation=()","payment=(self)"])if(!has(x.observed.permissionsPolicy,required))failures.push(`permissions-policy:${required}`);
  if(norm(x.observed.referrerPolicy)!==norm(expected.referrer_policy))failures.push("referrer-policy");
  if(norm(x.observed.crossOriginOpenerPolicy)!==norm(expected.cross_origin_opener_policy))failures.push("cross-origin-opener-policy");
  if(norm(x.observed.crossOriginResourcePolicy)!==norm(expected.cross_origin_resource_policy))failures.push("cross-origin-resource-policy");
  if(x.environment==="production"){const h=norm(x.observed.hsts),m=/max-age=(\d+)/.exec(h);if(!m||Number(m[1])<31536000||!h.includes("includesubdomains"))failures.push("hsts");}
  const at=now(),status=failures.length?"failed":"passed",scanId=uid("secscan");
  await db.prepare(`INSERT INTO security_scans(id,scan_type,environment,target_type,target_id,scanner,scanner_version,status,critical_count,high_count,medium_count,low_count,report_reference,report_sha256,started_at,completed_at,created_at) VALUES(?,'header',?,'deployment','security-headers',?,'1',?,0,?,?,0,?,'',?,?,?)`).bind(scanId,x.environment,x.scanner,status,failures.includes("hsts")&&x.environment==="production"?1:0,failures.length, x.evidenceReference,at,at,at).run();
  if(failures.length)throw Object.assign(new ApiError(409,`Security-header verification failed: ${failures.join(", ")}`),{verification:{failures,scanId}});
  await db.prepare("UPDATE security_header_policies SET last_verified_at=?,evidence_reference=?,updated_at=? WHERE id=?").bind(at,x.evidenceReference,at,expected.id).run();
  return{verified:true,scanId,environment:x.environment,verifiedAt:at};
}
export async function saveEdgeControl(db:DB,actorUserId:string,raw:unknown){const x=z.object({environment:z.enum(["staging","production"]),provider:z.string().min(1).max(120),wafMode:z.enum(["off","monitor","block"]),managedRulesEnabled:z.boolean().default(true),botManagementMode:z.enum(["off","monitor","challenge","block"]),ddosManaged:z.boolean().default(true),rateLimitPolicyRef:z.string().max(500).default(""),configReference:z.string().max(1000).default(""),evidenceReference:z.string().max(1000).default("")}).parse(raw),at=now();if(x.environment==="production"&&(x.wafMode!=="block"||!x.ddosManaged))throw new ApiError(400,"Production must keep managed DDoS protection and WAF blocking enabled; use an approved exception process rather than disabling the control in place.");await db.prepare(`INSERT INTO security_edge_controls(id,environment,provider,waf_mode,managed_rules_enabled,bot_management_mode,ddos_managed,rate_limit_policy_ref,config_reference,evidence_reference,verified_at,verified_by_user_id,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(environment,provider) DO UPDATE SET waf_mode=excluded.waf_mode,managed_rules_enabled=excluded.managed_rules_enabled,bot_management_mode=excluded.bot_management_mode,ddos_managed=excluded.ddos_managed,rate_limit_policy_ref=excluded.rate_limit_policy_ref,config_reference=excluded.config_reference,evidence_reference=excluded.evidence_reference,verified_at=excluded.verified_at,verified_by_user_id=excluded.verified_by_user_id,updated_at=excluded.updated_at`).bind(uid("edge"),x.environment,x.provider,x.wafMode,x.managedRulesEnabled?1:0,x.botManagementMode,x.ddosManaged?1:0,x.rateLimitPolicyRef,x.configReference,x.evidenceReference,x.evidenceReference?at:null,x.evidenceReference?actorUserId:null,at).run();return{saved:true,verified:!!x.evidenceReference};}

export async function registerSecretReference(db:DB,raw:unknown){const x=z.object({secretKey:z.string().regex(/^[A-Z0-9_:-]{2,160}$/),ownerTeam:z.string().min(1).max(120),environment:z.enum(["development","staging","production","shared"]),provider:z.string().min(1).max(120),secretManagerReference:z.string().min(3).max(1000),purpose:z.string().min(1).max(1000),rotationDays:z.number().int().min(1).max(730),lastRotatedAt:z.string().datetime().nullable().optional()}).parse(raw),at=now(),next=x.lastRotatedAt?new Date(new Date(x.lastRotatedAt).getTime()+x.rotationDays*86400000).toISOString():null;if(/(secret|token|key)=/i.test(x.secretManagerReference)||x.secretManagerReference.length>1000)throw new ApiError(400,"Store only a secret-manager reference, never plaintext secret material.");await db.prepare(`INSERT INTO security_secret_inventory(id,secret_key,owner_team,environment,provider,secret_manager_reference,purpose,rotation_days,last_rotated_at,next_rotation_at,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?, ?,?) ON CONFLICT(secret_key) DO UPDATE SET owner_team=excluded.owner_team,environment=excluded.environment,provider=excluded.provider,secret_manager_reference=excluded.secret_manager_reference,purpose=excluded.purpose,rotation_days=excluded.rotation_days,last_rotated_at=excluded.last_rotated_at,next_rotation_at=excluded.next_rotation_at,status=excluded.status,updated_at=excluded.updated_at`).bind(uid("secretref"),x.secretKey,x.ownerTeam,x.environment,x.provider,x.secretManagerReference,x.purpose,x.rotationDays,x.lastRotatedAt||null,next,next&&next<=at?"rotation_due":"active",at,at).run();return{saved:true,nextRotationAt:next};}

export async function recordKeyRotation(db:DB,actorType:"staff"|"service"|"provider"|"system",actorId:string,raw:unknown){const x=z.object({secretKey:z.string().min(1),eventType:z.enum(["rotated","revoked","compromised","tested"]),oldVersionReference:z.string().max(500).nullable().optional(),newVersionReference:z.string().max(500).nullable().optional(),evidenceReference:z.string().max(1000).default("")}).parse(raw),secret=await db.prepare("SELECT * FROM security_secret_inventory WHERE secret_key=?").bind(x.secretKey).first<any>();if(!secret)throw new ApiError(404,"Secret inventory record not found.");const at=now(),next=x.eventType==="rotated"?new Date(Date.now()+Number(secret.rotation_days)*86400000).toISOString():secret.next_rotation_at;await db.batch([db.prepare("INSERT INTO security_key_rotation_events(id,secret_inventory_id,event_type,old_version_reference,new_version_reference,actor_type,actor_id,evidence_reference,occurred_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(uid("keyrot"),secret.id,x.eventType,x.oldVersionReference||null,x.newVersionReference||null,actorType,actorId,x.evidenceReference,at),db.prepare("UPDATE security_secret_inventory SET last_rotated_at=CASE WHEN ?='rotated' THEN ? ELSE last_rotated_at END,next_rotation_at=?,status=?,updated_at=? WHERE id=?").bind(x.eventType,at,next,x.eventType==="revoked"||x.eventType==="compromised"?"revoked":"active",at,secret.id)]);return{recorded:true,nextRotationAt:next};}

export async function recordSecurityScan(db:DB,raw:unknown){const x=z.object({scanType:z.enum(["dependency","sbom","secret","sast","dast","container","provenance","malware","pentest","pci_scope","header","waf","backup_security"]),environment:z.string().max(80).default("ci"),targetType:z.string().min(1).max(100),targetId:z.string().min(1).max(500),scanner:z.string().min(1).max(120),scannerVersion:z.string().max(120).default(""),status:z.enum(["queued","running","passed","warning","failed","blocked"]),reportReference:z.string().max(1000).default(""),reportSha256:z.string().regex(/^[a-fA-F0-9]{64}$/).or(z.literal("")).default(""),findings:z.array(z.object({fingerprint:z.string().min(1).max(300),severity:severitySchema,category:z.string().max(160),title:z.string().max(500),description:z.string().max(10000),component:z.string().max(500).default(""),installedVersion:z.string().max(120).default(""),fixedVersion:z.string().max(120).default(""),cve:z.string().max(80).default(""),ownerTeam:z.string().max(120).default("security")})).max(5000).default([])}).parse(raw),at=now(),scanId=uid("secscan"),counts={critical:0,high:0,medium:0,low:0,info:0} as Record<string,number>;for(const f of x.findings)counts[f.severity]++;const stmts:any[]=[db.prepare("INSERT INTO security_scans(id,scan_type,environment,target_type,target_id,scanner,scanner_version,status,critical_count,high_count,medium_count,low_count,report_reference,report_sha256,started_at,completed_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(scanId,x.scanType,x.environment,x.targetType,x.targetId,x.scanner,x.scannerVersion,x.status,counts.critical,counts.high,counts.medium,counts.low,x.reportReference,x.reportSha256,at,["queued","running"].includes(x.status)?null:at,at)];for(const f of x.findings){const dueDays=f.severity==="critical"?1:f.severity==="high"?7:f.severity==="medium"?30:90, dueAt=new Date(Date.now()+dueDays*86400000).toISOString();stmts.push(db.prepare("INSERT INTO security_findings(id,scan_id,fingerprint,severity,category,title,description,component,installed_version,fixed_version,cve,status,due_at,owner_team,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'open',?,?,?,?)").bind(uid("secfinding"),scanId,f.fingerprint,f.severity,f.category,f.title,f.description,f.component,f.installedVersion,f.fixedVersion,f.cve,dueAt,f.ownerTeam,at,at));}await db.batch(stmts);return{scanId,counts,status:x.status};}

export async function recordSbom(db:DB,raw:unknown){const x=z.object({releaseId:z.string().min(1),format:z.enum(["cyclonedx-json","spdx-json"]),objectReference:z.string().min(1).max(1000),sha256:z.string().regex(/^[a-fA-F0-9]{64}$/),componentCount:z.number().int().min(0),generatedBy:z.string().min(1).max(160)}).parse(raw),id=uid("sbom");await db.prepare("INSERT INTO security_sboms(id,release_id,format,object_reference,sha256,component_count,generated_by,generated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(release_id,format) DO UPDATE SET object_reference=excluded.object_reference,sha256=excluded.sha256,component_count=excluded.component_count,generated_by=excluded.generated_by,generated_at=excluded.generated_at").bind(id,x.releaseId,x.format,x.objectReference,x.sha256.toLowerCase(),x.componentCount,x.generatedBy,now()).run();return{id};}
export async function recordBuildProvenance(db:DB,raw:unknown){const x=z.object({releaseId:z.string().min(1),sourceRevision:z.string().min(7).max(200),builderIdentity:z.string().min(1).max(500),buildSystem:z.string().min(1).max(200),artifactSha256:z.string().regex(/^[a-fA-F0-9]{64}$/),provenanceFormat:z.string().max(120).default("slsa-v1"),provenanceReference:z.string().min(1).max(1000),signatureReference:z.string().max(1000).default(""),verified:z.boolean().default(false)}).parse(raw),at=now(),id=uid("prov");await db.prepare(`INSERT INTO security_build_provenance(id,release_id,source_revision,builder_identity,build_system,artifact_sha256,provenance_format,provenance_reference,signature_reference,verified,verified_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(release_id) DO UPDATE SET source_revision=excluded.source_revision,builder_identity=excluded.builder_identity,build_system=excluded.build_system,artifact_sha256=excluded.artifact_sha256,provenance_format=excluded.provenance_format,provenance_reference=excluded.provenance_reference,signature_reference=excluded.signature_reference,verified=excluded.verified,verified_at=excluded.verified_at`).bind(id,x.releaseId,x.sourceRevision,x.builderIdentity,x.buildSystem,x.artifactSha256.toLowerCase(),x.provenanceFormat,x.provenanceReference,x.signatureReference,x.verified?1:0,x.verified?at:null,at).run();return{id,verified:x.verified};}


export async function updateSecurityFinding(db:DB,actorUserId:string,raw:unknown){
  const x=z.object({id:z.string().min(1),status:z.enum(["open","triaged","accepted","fixed","false_positive"]),ownerTeam:z.string().min(1).max(120),remediationReference:z.string().max(1000).default(""),acceptanceReason:z.string().max(5000).default(""),acceptanceReference:z.string().max(1000).default(""),acceptedUntil:z.string().datetime().nullable().optional()}).parse(raw),at=now();
  const existing=await db.prepare("SELECT * FROM security_findings WHERE id=?").bind(x.id).first<any>();if(!existing)throw new ApiError(404,"Security finding not found.");
  if(x.status==="accepted"){
    if(x.acceptanceReason.trim().length<20||!x.acceptanceReference.trim()||!x.acceptedUntil)throw new ApiError(400,"Risk acceptance requires a reason, evidence/reference, and expiry.");
    const expiry=Date.parse(x.acceptedUntil),nowMs=Date.now();if(!Number.isFinite(expiry)||expiry<=nowMs)throw new ApiError(400,"Risk acceptance expiry must be in the future.");
    if(expiry-nowMs>180*86400000)throw new ApiError(400,"Risk acceptance may not exceed 180 days without renewal.");
  }
  if(x.status==="fixed"&&!x.remediationReference.trim())throw new ApiError(400,"Fixed findings require remediation evidence/reference.");
  const accepted=x.status==="accepted";
  await db.prepare(`UPDATE security_findings SET status=?,owner_team=?,remediation_reference=?,accepted_until=?,accepted_by_user_id=?,acceptance_reason=?,acceptance_reference=?,updated_at=? WHERE id=?`).bind(x.status,x.ownerTeam,x.remediationReference,accepted?x.acceptedUntil:null,accepted?actorUserId:null,accepted?x.acceptanceReason:"",accepted?x.acceptanceReference:"",at,x.id).run();
  return{id:x.id,status:x.status,acceptedUntil:accepted?x.acceptedUntil:null};
}

export async function savePentest(db:DB,raw:unknown){const x=z.object({id:z.string().optional(),provider:z.string().min(1).max(200),scope:z.string().min(1).max(5000),engagementType:z.enum(["external","authenticated","api","mobile","cloud","red_team"]),startsAt:z.string().datetime(),endsAt:z.string().datetime(),status:z.enum(["planned","active","report_received","remediating","closed"]),reportReference:z.string().max(1000).default(""),retestReference:z.string().max(1000).default(""),criticalOpen:z.number().int().min(0).default(0),highOpen:z.number().int().min(0).default(0),ownerUserId:z.string().nullable().optional()}).parse(raw);if(x.endsAt<=x.startsAt)throw new ApiError(400,"Pentest end must be after its start.");if(x.status==="closed"&&(x.criticalOpen||x.highOpen))throw new ApiError(409,"A pentest cannot be closed while critical or high findings remain open.");const id=x.id||uid("pentest"),at=now();await db.prepare(`INSERT INTO security_pentest_engagements(id,provider,scope,engagement_type,starts_at,ends_at,status,report_reference,retest_reference,critical_open,high_open,owner_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET provider=excluded.provider,scope=excluded.scope,engagement_type=excluded.engagement_type,starts_at=excluded.starts_at,ends_at=excluded.ends_at,status=excluded.status,report_reference=excluded.report_reference,retest_reference=excluded.retest_reference,critical_open=excluded.critical_open,high_open=excluded.high_open,owner_user_id=excluded.owner_user_id,updated_at=excluded.updated_at`).bind(id,x.provider,x.scope,x.engagementType,x.startsAt,x.endsAt,x.status,x.reportReference,x.retestReference,x.criticalOpen,x.highOpen,x.ownerUserId||null,at,at).run();return{id,status:x.status};}

export async function submitDisclosureReport(db:DB,raw:unknown){const x=z.object({reporterContactRef:z.string().max(1000).default(""),title:z.string().min(1).max(500),summary:z.string().min(1).max(20000)}).parse(raw),id=uid("vuln"),publicReference=`FORE-VULN-${new Date().getUTCFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`,at=now();await db.prepare("INSERT INTO security_disclosure_reports(id,public_reference,reporter_contact_ref,title,summary,severity,status,safe_harbor_version,created_at,updated_at) VALUES(?,?,?,?,?,'unknown','received','fore-vdp-v1',?,?)").bind(id,publicReference,x.reporterContactRef,x.title,x.summary,at,at).run();return{reference:publicReference,status:"received"};}
export async function manageDisclosureReport(db:DB,raw:unknown){const x=z.object({id:z.string().min(1),status:z.enum(["received","triaged","accepted","duplicate","not_applicable","remediating","resolved"]),severity:z.enum(["unknown","low","medium","high","critical"]),acknowledged:z.boolean().default(false)}).parse(raw),at=now();const r=await db.prepare("UPDATE security_disclosure_reports SET status=?,severity=?,acknowledged_at=CASE WHEN ?=1 AND acknowledged_at IS NULL THEN ? ELSE acknowledged_at END,resolved_at=CASE WHEN ?='resolved' THEN ? ELSE resolved_at END,updated_at=? WHERE id=? RETURNING id").bind(x.status,x.severity,x.acknowledged?1:0,at,x.status,at,at,x.id).first<any>();if(!r)throw new ApiError(404,"Disclosure report not found.");return{updated:true};}

export async function declareSecurityIncident(db:DB,raw:unknown){const x=z.object({severity:z.enum(["sev1","sev2","sev3","sev4"]),title:z.string().min(1).max(500),incidentCommanderUserId:z.string().nullable().optional(),customerImpact:z.string().max(10000).default("")}).parse(raw),plan=await db.prepare("SELECT id FROM security_incident_response_plans WHERE status='active' ORDER BY version DESC LIMIT 1").first<any>();if(!plan)throw new ApiError(409,"No active incident response plan is configured.");const at=now(),id=uid("secinc");await db.prepare("INSERT INTO security_incidents(id,plan_id,severity,status,title,incident_commander_user_id,declared_at,customer_impact,updated_at) VALUES(?,? ,?,'declared',?,?,?,?,?)").bind(id,plan.id,x.severity,x.title,x.incidentCommanderUserId||null,at,x.customerImpact,at).run();return{id,status:"declared"};}
export async function updateSecurityIncident(db:DB,raw:unknown){const x=z.object({id:z.string().min(1),status:z.enum(["declared","contained","eradicated","recovering","resolved","postmortem"]),rootCause:z.string().max(20000).optional(),customerImpact:z.string().max(20000).optional(),notificationStatus:z.string().max(200).optional(),evidenceReference:z.string().max(1000).optional(),postmortemReference:z.string().max(1000).optional()}).parse(raw),at=now();const r=await db.prepare(`UPDATE security_incidents SET status=?,contained_at=CASE WHEN ? IN ('contained','eradicated','recovering','resolved','postmortem') AND contained_at IS NULL THEN ? ELSE contained_at END,resolved_at=CASE WHEN ? IN ('resolved','postmortem') AND resolved_at IS NULL THEN ? ELSE resolved_at END,root_cause=COALESCE(?,root_cause),customer_impact=COALESCE(?,customer_impact),notification_status=COALESCE(?,notification_status),evidence_reference=COALESCE(?,evidence_reference),postmortem_reference=COALESCE(?,postmortem_reference),updated_at=? WHERE id=? RETURNING id`).bind(x.status,x.status,at,x.status,at,x.rootCause??null,x.customerImpact??null,x.notificationStatus??null,x.evidenceReference??null,x.postmortemReference??null,at,x.id).first<any>();if(!r)throw new ApiError(404,"Security incident not found.");return{updated:true,status:x.status};}

export async function setPublisherSecurityPolicy(db:DB,actorUserId:string,raw:unknown){const x=z.object({accountId:z.string().min(1),requireMfa:z.boolean().default(true),requireMfaForReadOnly:z.boolean().default(false),maxSessionAgeMinutes:z.number().int().min(5).max(10080).default(720),approvedDomains:z.array(z.string().max(253)).max(50).default([])}).parse(raw),at=now();await db.prepare(`INSERT INTO publisher_security_policies(account_id,require_mfa,require_mfa_for_read_only,max_session_age_minutes,approved_domains_json,updated_by_user_id,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(account_id) DO UPDATE SET require_mfa=excluded.require_mfa,require_mfa_for_read_only=excluded.require_mfa_for_read_only,max_session_age_minutes=excluded.max_session_age_minutes,approved_domains_json=excluded.approved_domains_json,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at`).bind(x.accountId,x.requireMfa?1:0,x.requireMfaForReadOnly?1:0,x.maxSessionAgeMinutes,JSON.stringify(x.approvedDomains),actorUserId,at).run();return{saved:true};}

export async function assertPublisherMfaPolicy(db:DB,user:{id:string;aal?:string|null;authProvider?:string},accountId?:string|null){
  if(user.authProvider==="openai-host") return; // local/host development identity; production auth must provide AAL.
  let required=true;
  if(accountId){const p=await db.prepare("SELECT require_mfa FROM publisher_security_policies WHERE account_id=?").bind(accountId).first<any>();required=p?!!p.require_mfa:true;}
  if(required&&user.aal!=="aal2")throw new ApiError(403,"Publisher operations require multi-factor authentication (AAL2). Verify a second factor and retry.");
}

export async function mirrorPublishingMalwareResult(db:DB,input:{assetVersionId:string;status:string;validatorName:string;validatorVersion:string;issues:any[];reportObjectKey?:string|null;reportSha256?:string|null}){
  const scanStatus=input.status==="passed"?"passed":input.status==="warning"?"warning":input.status==="failed"?"failed":"blocked",at=now(),critical=input.issues.filter((i:any)=>i.severity==="error").length;
  await db.prepare("INSERT INTO security_scans(id,scan_type,environment,target_type,target_id,scanner,scanner_version,status,critical_count,high_count,medium_count,low_count,report_reference,report_sha256,started_at,completed_at,created_at) VALUES(?,'malware','publishing','publishing_asset_version',?,?,?,?,?,0,0,0,?,?,?, ?,?)")
    .bind(uid("secscan"),input.assetVersionId,input.validatorName,input.validatorVersion,scanStatus,critical,input.reportObjectKey||"",input.reportSha256||"",at,at,at).run();
}
