import {useState} from "react";
import {Search,ShieldCheck,ReceiptText,RefreshCw,RotateCcw,Smartphone,UserRound} from "lucide-react";
import {toast} from "sonner";
import {api,useAccount} from "./client";

const sections=["users","orders","products","publishers","refunds","devices","entitlements","offlineLicenses","payments"] as const;
export function SupportAdminPage(){
  const {data,signIn}=useAccount(),[q,setQ]=useState(""),[results,setResults]=useState<any>(null),[caseData,setCaseData]=useState<any>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>({});
  if(!data.user)return <div className="staff-console"><div className="staff-auth"><ShieldCheck/><h1>Customer support operations</h1><p>Sign in with an individually provisioned staff account. MFA and RBAC are enforced server-side.</p><button className="button gold" onClick={signIn}>Sign in</button></div></div>;
  const search=async()=>{setBusy(true);try{setResults(await api(`/admin/support/search?q=${encodeURIComponent(q)}`));}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
  const openCase=async(id:string)=>{setBusy(true);try{setCaseData(await api(`/admin/support/cases/${encodeURIComponent(id)}`));}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
  const createCase=async()=>{const subject=prompt("Support case subject:");if(!subject)return;const category=(prompt("Category: billing, refund, entitlement, download, account, publication, subscription, device, other","other")||"other");try{const r=await api<any>("/admin/support/cases","POST",{userId:selected.userId||null,orderId:selected.orderId||null,productId:selected.productId||null,publisherAccountId:selected.publisherAccountId||null,category,priority:"normal",subject});await openCase(r.id);toast.success("Support case opened");}catch(e){toast.error((e as Error).message);}};
  const act=async(actionType:string,targetId:string,amountMinor?:number)=>{if(!caseData?.case?.id)return;const reasonCode=prompt("Reason code:","customer_request");const rationale=prompt("Rationale (required for audit; at least 10 characters):");if(!reasonCode||!rationale)return;try{await api("/admin/support/action","POST",{caseId:caseData.case.id,actionType,targetId,reasonCode,rationale,idempotencyKey:`support-ui:${crypto.randomUUID()}`,amountMinor});toast.success("Support action completed and audited");await openCase(caseData.case.id);}catch(e){toast.error((e as Error).message);}};
  if(caseData)return <div className="staff-console"><div className="publishing-section-head"><div><span className="small-label">SUPPORT CASE</span><h1>{caseData.case.subject}</h1><p>{caseData.case.id} · {caseData.case.status} · {caseData.case.priority}</p></div><button className="button outline" onClick={()=>setCaseData(null)}>Back to search</button></div>
    <div className="publishing-onboarding-grid"><section className="publishing-onboard-card"><div><h3>Customer / order</h3>{caseData.account&&<p><UserRound size={15}/> {caseData.account.email||caseData.account.id}</p>}{caseData.order&&<><p><ReceiptText size={15}/> {caseData.order.invoice_number||caseData.order.id} · {caseData.order.status}</p><div className="inline-actions"><button className="button outline compact" onClick={()=>act("resend_receipt",caseData.order.id)}>Resend receipt</button><button className="button outline compact" onClick={()=>{const raw=prompt("Refund amount in cents; blank = maximum refundable");act("refund",caseData.order.id,raw?Number(raw):undefined)}}>Refund</button></div></>}</div></section>
    <section className="publishing-onboard-card"><div><h3>Entitlements</h3>{caseData.entitlements?.map((e:any)=><div key={e.id} className="publishing-admin-row"><span>{e.product_id} · {e.status}</span><div className="inline-actions"><button className="text-link" onClick={()=>act("restore_entitlement",e.id)}><RotateCcw size={14}/>Restore</button><button className="text-link" onClick={()=>act("revoke_entitlement",e.id)}>Revoke</button></div></div>)}</div></section>
    <section className="publishing-onboard-card"><div><h3>Devices & downloads</h3>{caseData.devices?.map((d:any)=><div key={d.id} className="publishing-admin-row"><span><Smartphone size={14}/>{d.name||d.platform||d.id} · {d.revoked_at?"revoked":"active"}</span>{!d.revoked_at&&<button className="text-link" onClick={()=>act("revoke_device",d.id)}>Revoke</button>}</div>)}{caseData.offlineLicenses?.map((l:any)=><div key={l.id} className="publishing-admin-row"><span>{l.product_id} · offline {l.status}</span><button className="text-link" onClick={()=>act("requeue_download",l.id)}><RefreshCw size={14}/>Reissue</button></div>)}{caseData.downloadDiagnostics?.length>0&&<><h4>Download diagnostics</h4>{caseData.downloadDiagnostics.map((d:any)=><div className="publishing-admin-row" key={d.license_id}><div><strong>{d.product_id}</strong><span>{d.device_name||d.device_id} · {d.diagnosis}</span><span>entitlement {d.entitlement_status||"missing"} · license {d.license_status} · storefront {d.storefront_status||"missing"}</span></div></div>)}</>}</div></section></div>
    <section className="publishing-section"><h2>Support timeline</h2><form className="fore-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/admin/support/note","POST",{caseId:caseData.case.id,note:f.get("note"),status:f.get("status")});(e.currentTarget as HTMLFormElement).reset();await openCase(caseData.case.id);}catch(err){toast.error((err as Error).message);}}}><label>Moderator note<textarea name="note" required maxLength={10000}/></label><label>Status<select name="status" defaultValue={caseData.case.status}><option value="open">Open</option><option value="pending_customer">Pending customer</option><option value="pending_internal">Pending internal</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label><button className="button gold">Add note</button></form>{caseData.timeline?.map((e:any)=><div className="publishing-admin-row" key={e.id}><div><strong>{e.event_type}</strong><span>{e.note}</span><span>{new Date(e.created_at).toLocaleString()}</span></div></div>)}</section>
    <section className="publishing-section"><h2>Audited actions</h2>{caseData.actions?.map((a:any)=><div className="publishing-admin-row" key={a.id}><div><strong>{a.action_type}</strong><span>{a.target_type}: {a.target_id}</span><span>{a.reason_code} · {a.rationale}</span><span>{new Date(a.created_at).toLocaleString()}</span></div></div>)}</section>
  </div>;
  return <div className="staff-console"><div className="publishing-section-head"><div><span className="small-label">CUSTOMER SUPPORT</span><h1>Support operations</h1><p className="muted">Search customer and commerce records without exposing raw payment payloads. Every privileged change requires a scoped case and creates immutable audit evidence.</p></div></div><div className="catalog-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="User, order, invoice, transaction, entitlement, book, publisher, refund, device…" onKeyDown={e=>{if(e.key==='Enter')void search();}}/><button className="button gold" disabled={busy||q.trim().length<2} onClick={search}>Search</button></div>
    {results&&<><div className="inline-actions"><button className="button gold" disabled={!Object.keys(selected).length} onClick={createCase}>Open case from selection</button><span className="small muted">Selected: {Object.entries(selected).map(([k,v])=>`${k}=${v}`).join(" · ")||"nothing"}</span></div>{sections.map(name=>results[name]?.length?<section className="publishing-section" key={name}><h2>{name}</h2><div className="publishing-title-list">{results[name].map((r:any)=><button className="publishing-admin-row" key={r.id} onClick={()=>{const next={...selected};if(name==="users")next.userId=r.id;if(name==="orders"){next.orderId=r.id;next.userId=r.user_id;}if(name==="products")next.productId=r.id;if(name==="publishers")next.publisherAccountId=r.id;if(name==="devices")next.userId=r.user_id;if(name==="entitlements"){next.userId=r.user_id;next.productId=r.product_id;}setSelected(next);}}><div><strong>{r.id}</strong><span>{r.email||r.invoice_number||r.title||r.display_name||r.name||r.status||r.product_id||""}</span><span>{r.user_id?`user ${r.user_id}`:""}</span></div></button>)}</div></section>:null)}</>}
  </div>;
}
