import { z } from "zod";
import type { CoveEnv } from "./api.server";
import { ApiError, now } from "./service";
import { refundOrder } from "./commerce.server";
import type { StaffContext } from "./moderation.server";

const id=(p:string)=>`${p}_${crypto.randomUUID()}`;
const parse=(s:any)=>{try{return JSON.parse(String(s||"{}"));}catch{return{};}};
async function sha256(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function event(db:CoveEnv["DB"],caseId:string,type:string,staffUserId:string,note="",payload:any={}){await db.prepare("INSERT INTO support_case_events(id,case_id,event_type,staff_user_id,note,event_json,created_at) VALUES(?,?,?,?,?,?,?)").bind(id("supevt"),caseId,type,staffUserId,note,JSON.stringify(payload),now()).run();}

export async function supportSearch(db:CoveEnv["DB"],query:string,includePaymentDetails=false){
  const q=query.trim();if(q.length<2)throw new ApiError(400,"Enter at least 2 characters.");const like=`%${q.slice(0,160)}%`;
  const [users,orders,products,publishers,refunds,devices,entitlements,offline,payments]=await Promise.all([
    db.prepare("SELECT app_id id,email,username,created_at FROM auth_accounts WHERE app_id LIKE ? OR email LIKE ? OR username LIKE ? ORDER BY created_at DESC LIMIT 25").bind(like,like,like).all<any>(),
    db.prepare("SELECT id,user_id,invoice_number,status,currency,total_minor,refunded_minor,stripe_payment_intent_id,payment_method_summary,created_at FROM commerce_orders WHERE id LIKE ? OR invoice_number LIKE ? OR user_id LIKE ? OR stripe_payment_intent_id LIKE ? ORDER BY created_at DESC LIMIT 25").bind(like,like,like,like).all<any>(),
    db.prepare("SELECT p.id,p.sku,p.format,p.storefront_status,p.source_external_id,e.title,e.publisher_id FROM products p JOIN editions e ON e.id=p.edition_id WHERE p.id LIKE ? OR p.sku LIKE ? OR p.source_external_id LIKE ? OR e.title LIKE ? ORDER BY p.updated_at DESC LIMIT 25").bind(like,like,like,like).all<any>(),
    db.prepare("SELECT id,display_name,legal_name,status,country_code FROM publishing_accounts WHERE id LIKE ? OR display_name LIKE ? OR legal_name LIKE ? ORDER BY updated_at DESC LIMIT 25").bind(like,like,like).all<any>(),
    db.prepare("SELECT r.id,r.order_id,r.amount_minor,r.currency,r.reason,r.status,r.provider_refund_id,r.created_at,o.user_id FROM commerce_refunds r JOIN commerce_orders o ON o.id=r.order_id WHERE r.id LIKE ? OR r.provider_refund_id LIKE ? OR r.order_id LIKE ? ORDER BY r.created_at DESC LIMIT 25").bind(like,like,like).all<any>(),
    db.prepare("SELECT id,user_id,device_key,name,platform,last_seen_at,revoked_at,created_at FROM devices WHERE id LIKE ? OR user_id LIKE ? OR device_key LIKE ? OR name LIKE ? ORDER BY last_seen_at DESC LIMIT 25").bind(like,like,like,like).all<any>(),
    db.prepare("SELECT id,user_id,product_id,entitlement_type,status,source,order_item_id,granted_at,updated_at FROM entitlements WHERE id LIKE ? OR user_id LIKE ? OR product_id LIKE ? OR order_item_id LIKE ? ORDER BY updated_at DESC LIMIT 25").bind(like,like,like,like).all<any>(),
    db.prepare("SELECT id,user_id,product_id,entitlement_id,device_id,status,issued_at,expires_at,revoked_at,revocation_reason FROM audio_offline_licenses WHERE id LIKE ? OR user_id LIKE ? OR product_id LIKE ? OR device_id LIKE ? ORDER BY issued_at DESC LIMIT 25").bind(like,like,like,like).all<any>(),
    includePaymentDetails?db.prepare("SELECT pa.id,pa.order_id,pa.provider,pa.provider_payment_id,pa.status,pa.amount_minor,pa.currency,pa.failure_code,pa.failure_message,pa.created_at,pa.updated_at,o.user_id FROM commerce_payment_attempts pa JOIN commerce_orders o ON o.id=pa.order_id WHERE pa.id LIKE ? OR pa.provider_payment_id LIKE ? OR pa.order_id LIKE ? ORDER BY pa.updated_at DESC LIMIT 25").bind(like,like,like).all<any>():Promise.resolve({results:[]}),
  ]);
  return{users:users.results,orders:orders.results,products:products.results,publishers:publishers.results,refunds:refunds.results,devices:devices.results,entitlements:entitlements.results,offlineLicenses:offline.results,payments:payments.results};
}

export async function createSupportCase(db:CoveEnv["DB"],staff:StaffContext,raw:unknown){
  const x=z.object({userId:z.string().max(240).nullable().optional(),orderId:z.string().max(240).nullable().optional(),productId:z.string().max(240).nullable().optional(),publisherAccountId:z.string().max(240).nullable().optional(),category:z.enum(["billing","refund","entitlement","download","account","publication","subscription","device","other"]),priority:z.enum(["low","normal","high","urgent"]).default("normal"),subject:z.string().trim().min(3).max(500)}).parse(raw),caseId=id("support"),at=now();
  if(x.orderId){const o=await db.prepare("SELECT user_id FROM commerce_orders WHERE id=?").bind(x.orderId).first<any>();if(!o)throw new ApiError(404,"Order not found.");if(x.userId&&o.user_id!==x.userId)throw new ApiError(409,"The order does not belong to the selected customer.");}
  await db.prepare("INSERT INTO support_cases(id,user_id,order_id,product_id,publisher_account_id,category,status,priority,subject,created_by_staff_user_id,assigned_to_staff_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'open',?,?,?,?,?,?)").bind(caseId,x.userId||null,x.orderId||null,x.productId||null,x.publisherAccountId||null,x.category,x.priority,x.subject,staff.userId,staff.userId,at,at).run();
  await event(db,caseId,"case_opened",staff.userId,x.subject,{category:x.category,priority:x.priority});return{id:caseId};
}

export async function supportCaseDetail(db:CoveEnv["DB"],caseId:string,includePaymentDetails=false){
  const c=await db.prepare("SELECT * FROM support_cases WHERE id=?").bind(caseId).first<any>();if(!c)throw new ApiError(404,"Support case not found.");
  const [timeline,actions]=await Promise.all([db.prepare("SELECT * FROM support_case_events WHERE case_id=? ORDER BY created_at,id").bind(caseId).all<any>(),db.prepare("SELECT * FROM support_actions WHERE case_id=? ORDER BY created_at DESC").bind(caseId).all<any>()]);
  let account:any=null,order:any=null,entitlements:any[]=[],payments:any[]=[],devices:any[]=[],offline:any[]=[],downloadDiagnostics:any[]=[],publication:any=null;
  if(c.user_id){account=await db.prepare("SELECT app_id id,email,username,created_at FROM auth_accounts WHERE app_id=?").bind(c.user_id).first<any>();devices=(await db.prepare("SELECT id,name,platform,last_seen_at,revoked_at FROM devices WHERE user_id=? ORDER BY last_seen_at DESC LIMIT 50").bind(c.user_id).all<any>()).results;offline=(await db.prepare("SELECT id,product_id,device_id,status,issued_at,expires_at,revoked_at,revocation_reason FROM audio_offline_licenses WHERE user_id=? ORDER BY issued_at DESC LIMIT 50").bind(c.user_id).all<any>()).results;downloadDiagnostics=(await db.prepare(`SELECT l.id license_id,l.product_id,l.device_id,l.status license_status,l.expires_at,l.revoked_at,l.revocation_reason,d.name device_name,d.platform,d.revoked_at device_revoked_at,e.id entitlement_id,e.status entitlement_status,e.entitlement_type,p.storefront_status,p.sku FROM audio_offline_licenses l LEFT JOIN devices d ON d.id=l.device_id LEFT JOIN entitlements e ON e.id=l.entitlement_id LEFT JOIN products p ON p.id=l.product_id WHERE l.user_id=? ORDER BY l.issued_at DESC LIMIT 50`).bind(c.user_id).all<any>()).results.map((r:any)=>({...r,diagnosis:r.device_revoked_at?"device_revoked":r.entitlement_status!=="active"?"entitlement_inactive":r.license_status!=="active"?"license_inactive":Date.parse(String(r.expires_at||""))<=Date.now()?"license_expired":!["active","preorder"].includes(String(r.storefront_status))?"product_unavailable":"ready"}));}
  if(c.order_id){order=await db.prepare("SELECT * FROM commerce_orders WHERE id=?").bind(c.order_id).first<any>();entitlements=(await db.prepare("SELECT e.* FROM entitlements e JOIN commerce_order_items oi ON oi.id=e.order_item_id WHERE oi.order_id=? ORDER BY e.granted_at").bind(c.order_id).all<any>()).results;if(includePaymentDetails)payments=(await db.prepare("SELECT id,provider,provider_payment_id,status,amount_minor,currency,failure_code,failure_message,created_at,updated_at FROM commerce_payment_attempts WHERE order_id=? ORDER BY created_at DESC").bind(c.order_id).all<any>()).results;}
  if(c.product_id)publication=await db.prepare(`SELECT p.id product_id,p.sku,p.storefront_status,e.title,l.state lifecycle_state,l.state_reason,l.updated_at lifecycle_updated_at FROM products p JOIN editions e ON e.id=p.edition_id LEFT JOIN publishing_edition_drafts ped ON ped.catalog_product_id=p.id LEFT JOIN publishing_release_lifecycles l ON l.publishing_edition_id=ped.id WHERE p.id=? ORDER BY l.updated_at DESC LIMIT 1`).bind(c.product_id).first<any>();
  return{case:c,account,order,entitlements,payments,devices,offlineLicenses:offline,downloadDiagnostics,publication,timeline:timeline.results.map((r:any)=>({...r,event_json:parse(r.event_json)})),actions:actions.results.map((r:any)=>({...r,before_json:parse(r.before_json),after_json:parse(r.after_json)}))};
}

export async function addSupportNote(db:CoveEnv["DB"],staff:StaffContext,raw:unknown){const x=z.object({caseId:z.string().min(1),note:z.string().trim().min(1).max(10000),status:z.enum(["open","pending_customer","pending_internal","resolved","closed"]).optional()}).parse(raw),c=await db.prepare("SELECT * FROM support_cases WHERE id=?").bind(x.caseId).first<any>();if(!c)throw new ApiError(404,"Support case not found.");if(x.status)await db.prepare("UPDATE support_cases SET status=?,resolved_at=CASE WHEN ? IN ('resolved','closed') THEN ? ELSE NULL END,updated_at=? WHERE id=?").bind(x.status,x.status,now(),now(),x.caseId).run();else await db.prepare("UPDATE support_cases SET updated_at=? WHERE id=?").bind(now(),x.caseId).run();await event(db,x.caseId,"note",staff.userId,x.note,x.status?{status:x.status}:{});return{saved:true};}

async function recordAction(db:CoveEnv["DB"],staff:StaffContext,x:{caseId:string;actionType:string;targetType:string;targetId:string;reasonCode:string;rationale:string;idempotencyKey:string},before:any,after:any,providerReference=""){const existing=await db.prepare("SELECT * FROM support_actions WHERE idempotency_key=?").bind(x.idempotencyKey).first<any>();if(existing)return existing;const actionId=id("supact"),at=now();await db.prepare("INSERT INTO support_actions(id,case_id,staff_user_id,action_type,target_type,target_id,reason_code,rationale,idempotency_key,before_json,after_json,provider_reference,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(actionId,x.caseId,staff.userId,x.actionType,x.targetType,x.targetId,x.reasonCode,x.rationale,x.idempotencyKey,JSON.stringify(before||{}),JSON.stringify(after||{}),providerReference,at).run();await event(db,x.caseId,"action",staff.userId,x.rationale,{actionId,actionType:x.actionType,targetType:x.targetType,targetId:x.targetId,reasonCode:x.reasonCode});await db.prepare("UPDATE support_cases SET updated_at=? WHERE id=?").bind(at,x.caseId).run();return{id:actionId};}
function assertScope(c:any,target:any,kind:"user"|"order"|"product"|"publisher"){if(kind==="user"&&c.user_id&&String(target)!==String(c.user_id))throw new ApiError(409,"This action target is outside the support case customer scope.");if(kind==="order"&&c.order_id&&String(target)!==String(c.order_id))throw new ApiError(409,"This action target is outside the support case order scope.");if(kind==="product"&&c.product_id&&String(target)!==String(c.product_id))throw new ApiError(409,"This action target is outside the support case product scope.");if(kind==="publisher"&&c.publisher_account_id&&String(target)!==String(c.publisher_account_id))throw new ApiError(409,"This action target is outside the support case publisher scope.");}

export async function executeSupportAction(env:CoveEnv,staff:StaffContext,permission:(p:string)=>boolean,raw:unknown){
  const x=z.object({caseId:z.string().min(1),actionType:z.enum(["resend_receipt","refund","restore_entitlement","revoke_entitlement","reset_publication","requeue_download","revoke_device","security_recovery","note_only"]),targetId:z.string().min(1),reasonCode:z.string().min(2).max(120),rationale:z.string().trim().min(10).max(5000),idempotencyKey:z.string().min(16).max(200),amountMinor:z.number().int().positive().optional()}).parse(raw),db=env.DB,c=await db.prepare("SELECT * FROM support_cases WHERE id=?").bind(x.caseId).first<any>();if(!c)throw new ApiError(404,"Support case not found.");
  if(x.actionType==='refund'&&!permission('support.refund'))throw new ApiError(403,"Staff permission required: support.refund.");if(x.actionType==='reset_publication'&&!permission('support.publication.manage'))throw new ApiError(403,"Staff permission required: support.publication.manage.");if(x.actionType==='security_recovery'&&!permission('account.recovery.manage'))throw new ApiError(403,"Staff permission required: account.recovery.manage.");if(['restore_entitlement','revoke_entitlement'].includes(x.actionType)&&!permission('support.entitlement.manage'))throw new ApiError(403,"Staff permission required: support.entitlement.manage.");if(['revoke_device','requeue_download'].includes(x.actionType)&&!permission('support.device.manage'))throw new ApiError(403,"Staff permission required: support.device.manage.");if(x.actionType==='resend_receipt'&&!permission('support.receipt.resend'))throw new ApiError(403,"Staff permission required: support.receipt.resend.");
  if(x.actionType==='refund'){const before=await db.prepare("SELECT id,status,total_minor,refunded_minor,currency,user_id FROM commerce_orders WHERE id=?").bind(x.targetId).first<any>();if(!before)throw new ApiError(404,"Order not found.");assertScope(c,before.id,"order");assertScope(c,before.user_id,"user");const result=await refundOrder(env,{orderId:x.targetId,amountMinor:x.amountMinor,reason:x.reasonCode,idempotencyKey:`support:${x.idempotencyKey}`});return recordAction(db,staff,{...x,targetType:'order'},before,result,result.providerRefundId||'');}
  if(x.actionType==='resend_receipt'){const order=await db.prepare("SELECT id,user_id,invoice_number,receipt_url,status FROM commerce_orders WHERE id=?").bind(x.targetId).first<any>();if(!order)throw new ApiError(404,"Order not found.");assertScope(c,order.id,"order");assertScope(c,order.user_id,"user");const at=now(),notificationId=id("notif");await db.prepare("INSERT OR IGNORE INTO commerce_notifications(id,user_id,notification_type,dedupe_key,title,body,payload_json,created_at) VALUES(?,?,'receipt',?,?,?,?,?)").bind(notificationId,order.user_id,`support-receipt:${x.idempotencyKey}`,`Receipt ${order.invoice_number}`,`Your Cove receipt ${order.invoice_number} is ready.`,JSON.stringify({orderId:order.id,receiptUrl:order.receipt_url||null}),at).run();await db.prepare("INSERT INTO publishing_outbox(id,event_type,aggregate_type,aggregate_id,payload_json,status,available_at,created_at) VALUES(?,?,?,?,?,'pending',?,?)").bind(id('outbox'),'support.receipt.resend','order',order.id,JSON.stringify({userId:order.user_id,orderId:order.id,invoiceNumber:order.invoice_number}),at,at).run();return recordAction(db,staff,{...x,targetType:'order'},order,{queued:true,notificationId});}
  if(['restore_entitlement','revoke_entitlement'].includes(x.actionType)){const before=await db.prepare("SELECT * FROM entitlements WHERE id=?").bind(x.targetId).first<any>();if(!before)throw new ApiError(404,"Entitlement not found.");assertScope(c,before.user_id,"user");assertScope(c,before.product_id,"product");if(x.actionType==='restore_entitlement'){const p=await db.prepare("SELECT storefront_status FROM products WHERE id=?").bind(before.product_id).first<any>();const enforcement=await db.prepare(`SELECT l.state FROM publishing_release_lifecycles l JOIN publishing_edition_drafts e ON e.id=l.publishing_edition_id WHERE e.catalog_product_id=? ORDER BY l.updated_at DESC LIMIT 1`).bind(before.product_id).first<any>();if(!p||['suppressed','takedown','retired'].includes(String(enforcement?.state||'')))throw new ApiError(409,"Trust & Safety enforcement prevents entitlement restoration for this product.");if(before.order_item_id){const order=await db.prepare("SELECT o.status FROM commerce_orders o JOIN commerce_order_items oi ON oi.order_id=o.id WHERE oi.id=?").bind(before.order_item_id).first<any>();if(order&&['refunded','canceled','chargeback_lost'].includes(String(order.status)))throw new ApiError(409,"The originating order no longer supports an active sale entitlement. Refund/chargeback state must be resolved through commerce operations.");}}const status=x.actionType==='restore_entitlement'?'active':'revoked';await db.prepare("UPDATE entitlements SET status=?,updated_at=? WHERE id=?").bind(status,now(),x.targetId).run();if(status==='revoked')await db.prepare("UPDATE audio_offline_licenses SET status='revoked',revoked_at=?,revocation_reason='entitlement_revoked' WHERE entitlement_id=? AND status='active'").bind(now(),x.targetId).run();const after=await db.prepare("SELECT * FROM entitlements WHERE id=?").bind(x.targetId).first<any>();return recordAction(db,staff,{...x,targetType:'entitlement'},before,after);}
  if(x.actionType==='revoke_device'){const before=await db.prepare("SELECT * FROM devices WHERE id=?").bind(x.targetId).first<any>();if(!before)throw new ApiError(404,"Device not found.");assertScope(c,before.user_id,"user");await db.prepare("UPDATE devices SET revoked_at=COALESCE(revoked_at,?) WHERE id=?").bind(now(),x.targetId).run();await db.prepare("UPDATE audio_offline_licenses SET status='revoked',revoked_at=?,revocation_reason='support_device_revoke' WHERE device_id=? AND status='active'").bind(now(),x.targetId).run();const after=await db.prepare("SELECT * FROM devices WHERE id=?").bind(x.targetId).first<any>();return recordAction(db,staff,{...x,targetType:'device'},before,after);}
  if(x.actionType==='reset_publication'){const before=await db.prepare(`SELECT l.*,t.account_id,p.product_id FROM publishing_release_lifecycles l JOIN publishing_edition_drafts e ON e.id=l.publishing_edition_id JOIN publishing_titles t ON t.id=e.title_id LEFT JOIN publishing_publication_versions pv ON pv.id=l.current_publication_version_id LEFT JOIN publishing_publications p ON p.id=pv.publication_id WHERE l.publishing_edition_id=?`).bind(x.targetId).first<any>();if(!before)throw new ApiError(404,"Publishing lifecycle not found.");assertScope(c,before.account_id,"publisher");if(before.product_id)assertScope(c,before.product_id,"product");if(['suppressed','takedown','retired'].includes(String(before.state)))throw new ApiError(409,"Trust & Safety enforcement cannot be bypassed through customer support.");if(['live','updated'].includes(String(before.state)))throw new ApiError(409,"Live publications must be changed through Publishing Operations, not Customer Support.");await db.prepare("UPDATE publishing_release_lifecycles SET state='draft',state_reason='support_reset',updated_at=? WHERE publishing_edition_id=?").bind(now(),x.targetId).run();await db.prepare("UPDATE publishing_edition_drafts SET status='draft',updated_at=? WHERE id=?").bind(now(),x.targetId).run();const after=await db.prepare("SELECT * FROM publishing_release_lifecycles WHERE publishing_edition_id=?").bind(x.targetId).first<any>();return recordAction(db,staff,{...x,targetType:'publishing_edition'},before,after);}
  if(x.actionType==='requeue_download'){const before=await db.prepare("SELECT * FROM audio_offline_licenses WHERE id=?").bind(x.targetId).first<any>();if(!before)throw new ApiError(404,"Offline license not found.");assertScope(c,before.user_id,"user");assertScope(c,before.product_id,"product");await db.prepare("UPDATE audio_offline_licenses SET status='revoked',revoked_at=?,revocation_reason='support_reissue' WHERE id=? AND status='active'").bind(now(),x.targetId).run();return recordAction(db,staff,{...x,targetType:'offline_license'},before,{reissueRequired:true});}
  if(x.actionType==='security_recovery'){const account=await db.prepare("SELECT app_id,email FROM auth_accounts WHERE app_id=?").bind(x.targetId).first<any>();if(!account)throw new ApiError(404,"Account not found.");assertScope(c,account.app_id,"user");const emailHash=await sha256(String(account.email||'').trim().toLowerCase());await db.prepare("INSERT INTO account_recovery_events(id,user_id,email_hash,event_type,actor_type,actor_user_id,metadata_json,created_at) VALUES(?,?,?,'staff_escalated','staff',?,?,?)").bind(id('recovery'),account.app_id,emailHash,staff.userId,JSON.stringify({caseId:x.caseId,reasonCode:x.reasonCode}),now()).run();return recordAction(db,staff,{...x,targetType:'user'},{id:account.app_id,emailHash},{recoveryEscalated:true});}
  return recordAction(db,staff,{...x,targetType:'case'},{},{noteOnly:true});
}
