import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Clipboard, KeyRound, Network, RefreshCw, ServerCog, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api } from "./client";

const label=(v:any)=>String(v??"").replaceAll("_"," ");
const date=(v:any)=>v?new Date(String(v)).toLocaleString():"—";
export function TraditionalPublishingPanel({accountId}:{accountId:string}){
  const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[oneTimeSecret,setOneTimeSecret]=useState(""),[webhookSecret,setWebhookSecret]=useState("");
  const [profile,setProfile]=useState({partnerCode:"",partnerType:"publisher",integrationTier:"api",productionStatus:"testing",sandboxEnabled:true,metadataStandard:"onix_3",operationsEmail:"",technicalEmail:"",acknowledgementsUrl:"",webhookUrl:"",notes:""});
  const [cred,setCred]=useState({environment:"sandbox",label:"Catalog integration",ipAllowlist:"",expiresAt:""});
  const [channel,setChannel]=useState({environment:"sandbox",channelType:"api",label:"Primary API",metadataFormat:"onix_3",secretReference:"",config:"{}"});
  const load=async()=>{try{const x=await api<any>(`/publishing/partner?accountId=${encodeURIComponent(accountId)}`);setData(x);if(x.profile)setProfile({partnerCode:x.profile.partner_code||"",partnerType:x.profile.partner_type||"publisher",integrationTier:x.profile.integration_tier||"api",productionStatus:x.profile.production_status||"testing",sandboxEnabled:!!x.profile.sandbox_enabled,metadataStandard:x.profile.metadata_standard||"onix_3",operationsEmail:x.profile.operations_email||"",technicalEmail:x.profile.technical_email||"",acknowledgementsUrl:x.profile.acknowledgements_url||"",webhookUrl:x.profile.webhook_url||"",notes:x.profile.notes||""});}catch(e:any){if(!String(e?.message||"").includes("permission"))console.info("Traditional publisher profile not configured",e)}};
  useEffect(()=>{void load()},[accountId]);
  const counts=useMemo(()=>{const feeds=data?.feeds||[];return{all:feeds.length,accepted:feeds.filter((x:any)=>["accepted","accepted_with_warnings","applied","partially_applied"].includes(x.status)).length,rejected:feeds.filter((x:any)=>["rejected","failed"].includes(x.status)).length};},[data]);
  const saveProfile=async()=>{setBusy(true);try{await api("/publishing/partner/profile","POST",{accountId,...profile,defaultContractId:data?.profile?.default_contract_id||null});toast.success("Partner integration profile saved");await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
  const issue=async()=>{setBusy(true);try{const out=await api<any>("/publishing/partner/credential","POST",{accountId,environment:cred.environment,label:cred.label,scopes:["feeds:write","feeds:read","assets:write","catalog:read"],ipAllowlist:cred.ipAllowlist.split(/[,\n\s]+/).map(x=>x.trim()).filter(Boolean),expiresAt:cred.expiresAt?new Date(cred.expiresAt).toISOString():null});setOneTimeSecret(out.secret);toast.success("Credential issued — copy it now");await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
  const revealWebhookSecret=async()=>{setBusy(true);try{const out=await api<any>("/publishing/partner/webhook-secret","POST",{accountId});setWebhookSecret(out.secret);toast.success("Acknowledgement signing secret revealed")}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
  const saveChannel=async()=>{setBusy(true);try{let config:any={};try{config=JSON.parse(channel.config||"{}")}catch{throw new Error("Channel config must be valid JSON.")}await api("/publishing/partner/channel","POST",{accountId,...channel,config});toast.success("Ingestion channel saved");await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
  return <section className="publishing-section traditional-publishing-panel">
    <div className="publishing-section-head"><div><span className="small-label">B2B DISTRIBUTION</span><h2>Traditional publisher integration</h2><p>ONIX/Cove JSON feeds, bulk assets, delta updates, credentials, signed validation acknowledgements, contracts, and sandbox certification.</p></div><button className="button outline compact" onClick={load}><RefreshCw size={14}/>Refresh</button></div>
    <div className="partner-kpi-grid"><div><ServerCog/><strong>{data?.profile?label(data.profile.production_status):"Not configured"}</strong><span>Production status</span></div><div><Activity/><strong>{counts.all}</strong><span>Recent feeds</span></div><div><CheckCircle2/><strong>{counts.accepted}</strong><span>Accepted / applied</span></div><div><ShieldCheck/><strong>{data?.contracts?.length||0}</strong><span>Assigned contracts</span></div></div>
    <details className="partner-details" open={!data?.profile}><summary><Network size={16}/> Partner profile & certification</summary><div className="publishing-form partner-form">
      <label>Partner code<input value={profile.partnerCode} placeholder="ACME_BOOKS" onChange={e=>setProfile({...profile,partnerCode:e.target.value.toUpperCase()})}/></label>
      <label>Partner type<select value={profile.partnerType} onChange={e=>setProfile({...profile,partnerType:e.target.value})}><option value="publisher">Publisher</option><option value="distributor">Distributor</option><option value="aggregator">Aggregator</option><option value="agent">Agent</option></select></label>
      <label>Integration tier<select value={profile.integrationTier} onChange={e=>setProfile({...profile,integrationTier:e.target.value})}><option value="managed">Managed</option><option value="api">API</option><option value="sftp">SFTP</option><option value="hybrid">Hybrid</option></select></label>
      <label>Metadata standard<select value={profile.metadataStandard} onChange={e=>setProfile({...profile,metadataStandard:e.target.value})}><option value="onix_3">ONIX 3.x</option><option value="onix_2_1">ONIX 2.1 reference tags</option><option value="fore_json">Cove JSON</option></select></label>
      <label>Certification status<input value={label(profile.productionStatus)} readOnly aria-readonly="true"/><small className="muted">Controlled by Cove after sandbox/certification review; publisher admins cannot self-enable production.</small></label>
      <label>Operations email<input type="email" value={profile.operationsEmail} onChange={e=>setProfile({...profile,operationsEmail:e.target.value})}/></label><label>Technical email<input type="email" value={profile.technicalEmail} onChange={e=>setProfile({...profile,technicalEmail:e.target.value})}/></label>
      <label className="partner-wide">Acknowledgement callback URL<input type="url" placeholder="https://publisher.example.com/fore/ack" value={profile.acknowledgementsUrl} onChange={e=>setProfile({...profile,acknowledgementsUrl:e.target.value})}/><small className="muted">Cove POSTs signed receipt/application results here. HTTPS only; private/local addresses are rejected.</small></label>
      <label className="publishing-check"><input type="checkbox" checked={profile.sandboxEnabled} onChange={e=>setProfile({...profile,sandboxEnabled:e.target.checked})}/> Enable isolated sandbox ingestion</label>
      <button className="button gold" disabled={busy||profile.partnerCode.length<3} onClick={saveProfile}>Save partner profile</button>
    </div></details>
    {data?.profile&&<div className="partner-two-col">
      <div className="partner-console-card"><h3><KeyRound size={16}/> API credentials</h3><p className="muted">Secrets are shown once. Cove stores only a SHA-256 digest and key prefix. Production credentials require Cove certification.</p><div className="publishing-inline"><select value={cred.environment} onChange={e=>setCred({...cred,environment:e.target.value})}><option value="sandbox">Sandbox</option><option value="production">Production</option></select><input value={cred.label} onChange={e=>setCred({...cred,label:e.target.value})} placeholder="Credential label"/><button className="button gold compact" disabled={busy} onClick={issue}>Issue</button></div><input value={cred.ipAllowlist} onChange={e=>setCred({...cred,ipAllowlist:e.target.value})} placeholder="Optional IP/CIDR allowlist: 203.0.113.5, 198.51.100.0/24"/>
        {oneTimeSecret&&<div className="one-time-secret"><strong>Copy now — this API secret cannot be retrieved again.</strong><code>{oneTimeSecret}</code><button className="button outline compact" onClick={async()=>{await navigator.clipboard.writeText(oneTimeSecret);toast.success("Copied")}}><Clipboard size={14}/>Copy</button></div>}
        <div className="partner-table">{(data.credentials||[]).map((c:any)=><div key={c.id}><code>{c.key_prefix}</code><span>{label(c.environment)} · {label(c.status)}</span><span>{(c.scopes||[]).join(", ")}</span>{c.status==="active"&&<button className="button outline compact danger" onClick={async()=>{try{await api("/publishing/partner/credential/revoke","POST",{accountId,credentialId:c.id});await load()}catch(e){toast.error((e as Error).message)}}}>Revoke</button>}</div>)}</div>
      </div>
      <div className="partner-console-card"><h3><ShieldCheck size={16}/> Validation callbacks</h3><p className="muted">Acknowledgements can be polled with <code>feeds:read</code> or pushed to the callback URL. Push payloads use HMAC-SHA256 signatures and retry independently from catalog application.</p><button className="button outline compact" disabled={busy||!profile.acknowledgementsUrl} onClick={revealWebhookSecret}>Reveal HMAC signing secret</button>
        {webhookSecret&&<div className="one-time-secret"><strong>Store this in your receiving service's secret manager.</strong><code>{webhookSecret}</code><button className="button outline compact" onClick={async()=>{await navigator.clipboard.writeText(webhookSecret);toast.success("Copied")}}><Clipboard size={14}/>Copy</button></div>}
        <small className="muted">The secret is deterministically derived per organization from Cove's server-side master key, so it can be re-retrieved by an MFA-authenticated publisher admin without storing plaintext in the database.</small>
      </div>
      <div className="partner-console-card"><h3><ServerCog size={16}/> Ingestion channels</h3><p className="muted">SFTP credentials live in your secret manager; Cove stores only the reference and non-secret transport configuration. SFTP/object-drop gateways normalize into the same feed API and validation pipeline.</p><div className="publishing-inline"><select value={channel.environment} onChange={e=>setChannel({...channel,environment:e.target.value})}><option value="sandbox">Sandbox</option><option value="production">Production</option></select><select value={channel.channelType} onChange={e=>setChannel({...channel,channelType:e.target.value})}><option value="api">API</option><option value="sftp">SFTP gateway</option><option value="object_drop">Object drop</option></select><input value={channel.label} onChange={e=>setChannel({...channel,label:e.target.value})}/></div><input value={channel.secretReference} onChange={e=>setChannel({...channel,secretReference:e.target.value})} placeholder="secret://partners/acme/sftp (required for SFTP)"/><textarea value={channel.config} onChange={e=>setChannel({...channel,config:e.target.value})} rows={3} aria-label="Non-secret channel JSON"/><button className="button outline compact" disabled={busy} onClick={saveChannel}>Save channel</button>
        <div className="partner-table">{(data.channels||[]).map((c:any)=><div key={c.id}><strong>{c.label}</strong><span>{label(c.environment)} · {label(c.channel_type)} · {label(c.status)}</span><code>{c.secret_reference||"No secret reference"}</code></div>)}</div>
      </div>
    </div>}
    {data?.profile&&<div className="partner-two-col"><div className="partner-console-card"><h3>Feed operations</h3><p className="muted"><code>POST /api/fore/partner/v1/feeds</code> accepts ONIX reference-tag XML or Cove JSON for metadata, price, availability, territory, and asset-manifest feeds. Delta sequence cursors/checksums make retries idempotent. Full metadata replacement requires the explicit <code>X-Cove-Full-Feed-Delete-Missing: true</code> safety header.</p><p className="muted">Asset manifests may arrive before or after binaries and reconcile by SHA-256/size/MIME. Transfer gateways should send the configured <code>X-Cove-Channel-Id</code>. Bulk EPUB/cover delivery uses <code>POST /api/fore/partner/v1/assets/batch</code> with a ZIP + root <code>manifest.json</code>; individual assets may use <code>/assets</code>.</p><div className="partner-table">{(data.feeds||[]).slice(0,12).map((f:any)=><div key={f.id}><strong>{label(f.feed_type)} · {label(f.mode)}</strong><span>{label(f.environment)} · {label(f.status)} · {f.item_count} records</span><code>{f.external_feed_id||f.id}</code><span>{date(f.received_at)}</span></div>)}</div></div>
      <div className="partner-console-card"><h3>Distribution contracts</h3><p className="muted">Catalog feeds select an assigned contract/version. Territory, format, channel, DRM, delivery, returns, subscription, commission, payment, termination, and post-termination access are enforced from that immutable version—not copied into independent book flags.</p><div className="partner-table">{(data.contracts||[]).map((c:any)=><div key={c.contract_id}><strong>{c.name||c.reference_code}</strong><span>{label(c.relationship)} · {label(c.contract_status)} · v{c.version_number||"—"}</span><span>{c.retailer_commission_bps!=null?`${(Number(c.retailer_commission_bps)/100).toFixed(2)}% retailer commission`:"No active version"}</span><span>Post-term: {label(c.post_termination_access_policy||"not configured")}</span></div>)}</div></div></div>}
  </section>;
}
