import { useQuery } from "@tanstack/react-query";
import { Bell, Check, Copy, ExternalLink, Heart, Loader2, RotateCcw, ShoppingCart, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useMemo, useState } from "react";
import { api, useAccount, productPath, type CatalogBook } from "./client";
import { BookArt } from "./Store";

type Offer={id:string;currency:string;amountMinor:number;listAmountMinor:number;promotion?:null|{name:string;endsAt:string}};
type WishlistItem={book:CatalogBook;offer:Offer|null;addedAt:string;alerts:{priceDrop:boolean;sale:boolean;release:boolean;preorder:boolean};available:boolean};
type Snapshot={items:WishlistItem[];profile:{share_enabled:number;share_token:string|null;title:string};notifications:any[]};
type Cart={items:{book?:CatalogBook;offer:Offer|null;available:boolean;stalePrice:boolean}[];currency:string|null;subtotalMinor:number};
function money(v:number,c:string){try{return new Intl.NumberFormat(undefined,{style:"currency",currency:c}).format(v/100)}catch{return `${c} ${(v/100).toFixed(2)}`}}

export function WishlistPage(){
  const {data,loading,signIn}=useAccount(),[busy,setBusy]=useState("");
  const wishlist=useQuery<Snapshot>({queryKey:["commerce-wishlist",data.user?.id],queryFn:()=>api("/wishlist"),enabled:!!data.user});
  const cart=useQuery<Cart>({queryKey:["commerce-cart",data.user?.id],queryFn:()=>api("/cart"),enabled:!!data.user});
  const shareUrl=useMemo(()=>wishlist.data?.profile.share_token&&typeof window!=="undefined"?`${window.location.origin}/wishlist/shared/${wishlist.data.profile.share_token}`:"",[wishlist.data?.profile.share_token]);
  if(loading)return <div className="empty-state"><Loader2 className="spin"/></div>;
  if(!data.user)return <div className="empty-state"><Heart size={34}/><h2>Your commerce wishlist lives with your account.</h2><p>Save books without mixing them into your reading shelves, and choose which retail alerts you want.</p><button className="button gold" onClick={signIn}>Sign in</button></div>;
  if(wishlist.isLoading)return <div className="empty-state"><Loader2 className="spin"/><p>Opening your wishlist…</p></div>;
  async function saveAlerts(item:WishlistItem,next:WishlistItem["alerts"]){if(!item.book.productId)return;setBusy(item.book.productId);try{await api("/wishlist/item","POST",{productId:item.book.productId,saved:true,alerts:next,sourceSurface:"wishlist"});await wishlist.refetch();toast.success("Alert preferences saved");}catch(e){toast.error((e as Error).message)}finally{setBusy("")}}
  async function remove(item:WishlistItem){if(!item.book.productId)return;setBusy(item.book.productId);try{await api("/wishlist/item","POST",{productId:item.book.productId,saved:false,sourceSurface:"wishlist"});await wishlist.refetch();toast.success("Removed from wishlist");}catch(e){toast.error((e as Error).message)}finally{setBusy("")}}
  async function move(item:WishlistItem){if(!item.book.productId)return;setBusy(item.book.productId);try{await api("/cart/item","POST",{productId:item.book.productId,sourceSurface:"wishlist",removeFromWishlist:true});await Promise.all([wishlist.refetch(),cart.refetch()]);toast.success("Moved to cart");}catch(e){toast.error((e as Error).message)}finally{setBusy("")}}
  async function sharing(enabled:boolean,rotate=false){try{await api("/wishlist/sharing","POST",{enabled,rotate,title:wishlist.data?.profile.title||"My wishlist"});await wishlist.refetch();toast.success(enabled?rotate?"Share link rotated":"Wishlist sharing enabled":"Wishlist sharing disabled");}catch(e){toast.error((e as Error).message)}}
  return <div className="wishlist-page">
    <header className="collection-header"><div><span className="page-eyebrow">SHOPPING, NOT SHELVING</span><h1>Wishlist<span className="gold-text">.</span></h1><p>Track releases and prices without changing your reading status.</p></div></header>
    <section className="wishlist-sharing-card"><div><h2>Gift-friendly sharing</h2><p className="muted">Sharing exposes only the titles and current storefront offers on this wishlist—never your notes, reading progress, or account data.</p></div><div className="wishlist-share-actions">{wishlist.data?.profile.share_enabled&&shareUrl?<><button className="button outline" onClick={async()=>{await navigator.clipboard.writeText(shareUrl);toast.success("Share link copied")}}><Copy size={16}/> Copy link</button><button className="button outline" onClick={()=>sharing(true,true)}><RotateCcw size={16}/> Rotate link</button><button className="text-link" onClick={()=>sharing(false)}>Stop sharing</button></>:<button className="button outline" onClick={()=>sharing(true)}>Create share link</button>}</div></section>
    <div className="wishlist-grid">{wishlist.data?.items.map(item=><article className="wishlist-card" key={String(item.book.productId)}><a href={productPath(item.book)} className="wishlist-cover"><BookArt book={item.book}/></a><div className="wishlist-body"><div><a href={productPath(item.book)}><h2>{item.book.title}</h2></a><p className="muted">{item.book.authors.map(a=>a.name).join(", ")||"Unknown author"}</p></div><div className="wishlist-price">{item.offer?<>{item.offer.promotion&&item.offer.listAmountMinor>item.offer.amountMinor&&<del>{money(item.offer.listAmountMinor,item.offer.currency)}</del>}<strong>{item.offer.amountMinor===0?"Free":money(item.offer.amountMinor,item.offer.currency)}</strong>{item.offer.promotion&&<span>{item.offer.promotion.name}</span>}</>:<><strong>Unavailable</strong><span>There is no active offer in this storefront.</span></>}</div><fieldset className="wishlist-alerts"><legend><Bell size={14}/> Alerts</legend>{([['priceDrop','Price drops'],['sale','Sales'],['release','Release'],['preorder','Preorder']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={item.alerts[key]} onChange={e=>saveAlerts(item,{...item.alerts,[key]:e.target.checked})}/>{label}</label>)}</fieldset><div className="wishlist-actions">{item.offer&&item.offer.amountMinor>0&&item.available&&<button className="button gold" disabled={busy===item.book.productId} onClick={()=>move(item)}><ShoppingCart size={16}/> Move to cart</button>}<button className="button outline" disabled={busy===item.book.productId} onClick={()=>remove(item)}><Trash2 size={16}/> Remove</button></div></div></article>)}</div>
    {!wishlist.data?.items.length&&<div className="empty-state"><Heart size={32}/><h2>No wishlist titles yet.</h2><p>Use “Add to wishlist” on any product page.</p><a className="button gold" href="/">Browse books</a></div>}
    {!!cart.data?.items.length&&<section className="cart-summary"><div><span className="small-label">PRE-CHECKOUT CART</span><h2>{cart.data.items.length} title{cart.data.items.length===1?"":"s"}</h2><p className="muted">Offers and territorial rights are revalidated every time this cart is loaded. A stale price snapshot is never treated as purchasable.</p></div><strong>{cart.data.currency?money(cart.data.subtotalMinor,cart.data.currency):"—"}</strong></section>}
    {!!wishlist.data?.notifications.length&&<section className="wishlist-notifications"><h2>Wishlist alerts</h2>{wishlist.data.notifications.slice(0,10).map((n:any)=><div key={n.id}><Bell size={16}/><div><strong>{n.title}</strong><p>{n.body}</p></div></div>)}</section>}
  </div>
}

export function SharedWishlistPage({token}:{token:string}){
  const query=useQuery<any>({queryKey:["shared-wishlist",token],queryFn:()=>api(`/shared-wishlist/${encodeURIComponent(token)}`),retry:false});
  if(query.isLoading)return <div className="empty-state"><Loader2 className="spin"/></div>;
  if(!query.data)return <div className="empty-state"><h2>This wishlist link is unavailable.</h2><p>Its owner may have disabled sharing or rotated the link.</p></div>;
  return <div className="wishlist-page"><header className="collection-header"><div><span className="page-eyebrow">SHARED WISHLIST</span><h1>{query.data.title}</h1><p>Prices and availability are live; private reading data is never shared.</p></div></header><div className="wishlist-grid">{query.data.items.map((item:any)=><article className="wishlist-card" key={item.book.productId}><a href={productPath(item.book)} className="wishlist-cover"><BookArt book={item.book}/></a><div className="wishlist-body"><h2>{item.book.title}</h2><p className="muted">{item.book.authors.map((a:any)=>a.name).join(", ")}</p><div className="wishlist-price">{item.offer?<strong>{item.offer.amountMinor===0?"Free":money(item.offer.amountMinor,item.offer.currency)}</strong>:<strong>Unavailable</strong>}</div><a className="button outline" href={productPath(item.book)}>View title <ExternalLink size={15}/></a></div></article>)}</div></div>;
}
