/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// Do not hand-edit in normal development; the route plugin will regenerate it.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudiobooksRouteImport } from './routes/audiobooks'
import { Route as BestsellersRouteImport } from './routes/bestsellers'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DefinitionsRouteImport } from './routes/definitions'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as NewReleasesRouteImport } from './routes/new-releases'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as PreordersRouteImport } from './routes/preorders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShelvesRouteImport } from './routes/shelves'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StoreRouteImport } from './routes/store'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as AuthorIdRouteImport } from './routes/author/$id'
import { Route as SeriesIdRouteImport } from './routes/series/$id'
import { Route as PublisherIdRouteImport } from './routes/publisher/$id'
import { Route as ImprintIdRouteImport } from './routes/imprint/$id'
import { Route as EditionIdRouteImport } from './routes/edition/$id'
import { Route as WorkIdRouteImport } from './routes/work/$id'
import { Route as CampaignSlugRouteImport } from './routes/campaign/$slug'
import { Route as EbooksSplatRouteImport } from './routes/ebooks/$'
import { Route as ListenIdRouteImport } from './routes/listen.$id'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as ShelfIdRouteImport } from './routes/shelf.$id'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as PublishingPolicyRouteImport } from './routes/publishing-policy'
import { Route as StaffPublishingRouteImport } from './routes/staff/publishing'
import { Route as StaffSupportRouteImport } from './routes/staff/support'
import { Route as StaffStorefrontRouteImport } from './routes/staff/storefront'
import { Route as ApiPublicHooksIngestRouteImport } from './routes/api/public/hooks/ingest'
import { Route as ApiPublicBooksIdContentRouteImport } from './routes/api/public/books/$id/content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AudiobooksRoute = AudiobooksRouteImport.update({
  id: '/audiobooks',
  path: '/audiobooks',
  getParentRoute: () => rootRouteImport,
} as any)

const BestsellersRoute = BestsellersRouteImport.update({
  id: '/bestsellers',
  path: '/bestsellers',
  getParentRoute: () => rootRouteImport,
} as any)

const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)

const DefinitionsRoute = DefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => rootRouteImport,
} as any)

const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)

const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)

const NewReleasesRoute = NewReleasesRouteImport.update({
  id: '/new-releases',
  path: '/new-releases',
  getParentRoute: () => rootRouteImport,
} as any)

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)

const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)

const PreordersRoute = PreordersRouteImport.update({
  id: '/preorders',
  path: '/preorders',
  getParentRoute: () => rootRouteImport,
} as any)

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)

const ShelvesRoute = ShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => rootRouteImport,
} as any)

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)

const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthorIdRoute = AuthorIdRouteImport.update({
  id: '/author/$id',
  path: '/author/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const SeriesIdRoute = SeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const PublisherIdRoute = PublisherIdRouteImport.update({
  id: '/publisher/$id',
  path: '/publisher/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const ImprintIdRoute = ImprintIdRouteImport.update({
  id: '/imprint/$id',
  path: '/imprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const EditionIdRoute = EditionIdRouteImport.update({
  id: '/edition/$id',
  path: '/edition/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const WorkIdRoute = WorkIdRouteImport.update({
  id: '/work/$id',
  path: '/work/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const CampaignSlugRoute = CampaignSlugRouteImport.update({
  id: '/campaign/$slug',
  path: '/campaign/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const EbooksSplatRoute = EbooksSplatRouteImport.update({
  id: '/ebooks/$',
  path: '/ebooks/$',
  getParentRoute: () => rootRouteImport,
} as any)

const ListenIdRoute = ListenIdRouteImport.update({
  id: '/listen/$id',
  path: '/listen/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const ShelfIdRoute = ShelfIdRouteImport.update({
  id: '/shelf/$id',
  path: '/shelf/$id',
  getParentRoute: () => rootRouteImport,
} as any)

const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)

const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)

const PublishingPolicyRoute = PublishingPolicyRouteImport.update({
  id: '/publishing-policy',
  path: '/publishing-policy',
  getParentRoute: () => rootRouteImport,
} as any)

const StaffPublishingRoute = StaffPublishingRouteImport.update({
  id: '/staff/publishing',
  path: '/staff/publishing',
  getParentRoute: () => rootRouteImport,
} as any)

const StaffSupportRoute = StaffSupportRouteImport.update({
  id: '/staff/support',
  path: '/staff/support',
  getParentRoute: () => rootRouteImport,
} as any)

const StaffStorefrontRoute = StaffStorefrontRouteImport.update({
  id: '/staff/storefront',
  path: '/staff/storefront',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiPublicHooksIngestRoute = ApiPublicHooksIngestRouteImport.update({
  id: '/api/public/hooks/ingest',
  path: '/api/public/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiPublicBooksIdContentRoute = ApiPublicBooksIdContentRouteImport.update({
  id: '/api/public/books/$id/content',
  path: '/api/public/books/$id/content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiobooks': typeof AudiobooksRoute
  '/bestsellers': typeof BestsellersRoute
  '/deals': typeof DealsRoute
  '/definitions': typeof DefinitionsRoute
  '/downloads': typeof DownloadsRoute
  '/highlights': typeof HighlightsRoute
  '/library': typeof LibraryRoute
  '/new-releases': typeof NewReleasesRoute
  '/notifications': typeof NotificationsRoute
  '/community': typeof CommunityRoute
  '/preorders': typeof PreordersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shelves': typeof ShelvesRoute
  '/stats': typeof StatsRoute
  '/store': typeof StoreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/book/$id': typeof BookIdRoute
  '/books/$id': typeof BooksIdRoute
  '/author/$id': typeof AuthorIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/publisher/$id': typeof PublisherIdRoute
  '/imprint/$id': typeof ImprintIdRoute
  '/edition/$id': typeof EditionIdRoute
  '/work/$id': typeof WorkIdRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/ebooks/$': typeof EbooksSplatRoute
  '/listen/$id': typeof ListenIdRoute
  '/read/$id': typeof ReadIdRoute
  '/shelf/$id': typeof ShelfIdRoute
  '/publishing': typeof PublishingRoute
  '/copyright': typeof CopyrightRoute
  '/publishing-policy': typeof PublishingPolicyRoute
  '/staff/publishing': typeof StaffPublishingRoute
  '/staff/support': typeof StaffSupportRoute
  '/staff/storefront': typeof StaffStorefrontRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/books/$id/content': typeof ApiPublicBooksIdContentRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiobooks': typeof AudiobooksRoute
  '/bestsellers': typeof BestsellersRoute
  '/deals': typeof DealsRoute
  '/definitions': typeof DefinitionsRoute
  '/downloads': typeof DownloadsRoute
  '/highlights': typeof HighlightsRoute
  '/library': typeof LibraryRoute
  '/new-releases': typeof NewReleasesRoute
  '/notifications': typeof NotificationsRoute
  '/community': typeof CommunityRoute
  '/preorders': typeof PreordersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shelves': typeof ShelvesRoute
  '/stats': typeof StatsRoute
  '/store': typeof StoreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/book/$id': typeof BookIdRoute
  '/books/$id': typeof BooksIdRoute
  '/author/$id': typeof AuthorIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/publisher/$id': typeof PublisherIdRoute
  '/imprint/$id': typeof ImprintIdRoute
  '/edition/$id': typeof EditionIdRoute
  '/work/$id': typeof WorkIdRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/ebooks/$': typeof EbooksSplatRoute
  '/listen/$id': typeof ListenIdRoute
  '/read/$id': typeof ReadIdRoute
  '/shelf/$id': typeof ShelfIdRoute
  '/publishing': typeof PublishingRoute
  '/copyright': typeof CopyrightRoute
  '/publishing-policy': typeof PublishingPolicyRoute
  '/staff/publishing': typeof StaffPublishingRoute
  '/staff/support': typeof StaffSupportRoute
  '/staff/storefront': typeof StaffStorefrontRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/books/$id/content': typeof ApiPublicBooksIdContentRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiobooks': typeof AudiobooksRoute
  '/bestsellers': typeof BestsellersRoute
  '/deals': typeof DealsRoute
  '/definitions': typeof DefinitionsRoute
  '/downloads': typeof DownloadsRoute
  '/highlights': typeof HighlightsRoute
  '/library': typeof LibraryRoute
  '/new-releases': typeof NewReleasesRoute
  '/notifications': typeof NotificationsRoute
  '/community': typeof CommunityRoute
  '/preorders': typeof PreordersRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shelves': typeof ShelvesRoute
  '/stats': typeof StatsRoute
  '/store': typeof StoreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/book/$id': typeof BookIdRoute
  '/books/$id': typeof BooksIdRoute
  '/author/$id': typeof AuthorIdRoute
  '/series/$id': typeof SeriesIdRoute
  '/publisher/$id': typeof PublisherIdRoute
  '/imprint/$id': typeof ImprintIdRoute
  '/edition/$id': typeof EditionIdRoute
  '/work/$id': typeof WorkIdRoute
  '/campaign/$slug': typeof CampaignSlugRoute
  '/ebooks/$': typeof EbooksSplatRoute
  '/listen/$id': typeof ListenIdRoute
  '/read/$id': typeof ReadIdRoute
  '/shelf/$id': typeof ShelfIdRoute
  '/publishing': typeof PublishingRoute
  '/copyright': typeof CopyrightRoute
  '/publishing-policy': typeof PublishingPolicyRoute
  '/staff/publishing': typeof StaffPublishingRoute
  '/staff/support': typeof StaffSupportRoute
  '/staff/storefront': typeof StaffStorefrontRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/books/$id/content': typeof ApiPublicBooksIdContentRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiobooks'
    | '/bestsellers'
    | '/deals'
    | '/definitions'
    | '/downloads'
    | '/highlights'
    | '/library'
    | '/new-releases'
    | '/notifications'
    | '/community'
    | '/preorders'
    | '/profile'
    | '/search'
    | '/shelves'
    | '/stats'
    | '/store'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/book/$id'
    | '/books/$id'
    | '/author/$id'
    | '/series/$id'
    | '/publisher/$id'
    | '/imprint/$id'
    | '/edition/$id'
    | '/work/$id'
    | '/campaign/$slug'
    | '/ebooks/$'
    | '/listen/$id'
    | '/read/$id'
    | '/shelf/$id'
    | '/publishing'
    | '/copyright'
    | '/publishing-policy'
    | '/staff/publishing'
    | '/staff/support'
    | '/staff/storefront'
    | '/api/public/hooks/ingest'
    | '/api/public/books/$id/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiobooks'
    | '/bestsellers'
    | '/deals'
    | '/definitions'
    | '/downloads'
    | '/highlights'
    | '/library'
    | '/new-releases'
    | '/notifications'
    | '/community'
    | '/preorders'
    | '/profile'
    | '/search'
    | '/shelves'
    | '/stats'
    | '/store'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/book/$id'
    | '/books/$id'
    | '/author/$id'
    | '/series/$id'
    | '/publisher/$id'
    | '/imprint/$id'
    | '/edition/$id'
    | '/work/$id'
    | '/campaign/$slug'
    | '/ebooks/$'
    | '/listen/$id'
    | '/read/$id'
    | '/shelf/$id'
    | '/publishing'
    | '/copyright'
    | '/publishing-policy'
    | '/staff/publishing'
    | '/staff/support'
    | '/staff/storefront'
    | '/api/public/hooks/ingest'
    | '/api/public/books/$id/content'
  id:
    | '__root__'
    | '/'
    | '/audiobooks'
    | '/bestsellers'
    | '/deals'
    | '/definitions'
    | '/downloads'
    | '/highlights'
    | '/library'
    | '/new-releases'
    | '/notifications'
    | '/community'
    | '/preorders'
    | '/profile'
    | '/search'
    | '/shelves'
    | '/stats'
    | '/store'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/book/$id'
    | '/books/$id'
    | '/author/$id'
    | '/series/$id'
    | '/publisher/$id'
    | '/imprint/$id'
    | '/edition/$id'
    | '/work/$id'
    | '/campaign/$slug'
    | '/ebooks/$'
    | '/listen/$id'
    | '/read/$id'
    | '/shelf/$id'
    | '/publishing'
    | '/copyright'
    | '/publishing-policy'
    | '/staff/publishing'
    | '/staff/support'
    | '/staff/storefront'
    | '/api/public/hooks/ingest'
    | '/api/public/books/$id/content'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiobooksRoute: typeof AudiobooksRoute
  BestsellersRoute: typeof BestsellersRoute
  DealsRoute: typeof DealsRoute
  DefinitionsRoute: typeof DefinitionsRoute
  DownloadsRoute: typeof DownloadsRoute
  HighlightsRoute: typeof HighlightsRoute
  LibraryRoute: typeof LibraryRoute
  NewReleasesRoute: typeof NewReleasesRoute
  NotificationsRoute: typeof NotificationsRoute
  CommunityRoute: typeof CommunityRoute
  PreordersRoute: typeof PreordersRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  ShelvesRoute: typeof ShelvesRoute
  StatsRoute: typeof StatsRoute
  StoreRoute: typeof StoreRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRoute
  BookIdRoute: typeof BookIdRoute
  BooksIdRoute: typeof BooksIdRoute
  AuthorIdRoute: typeof AuthorIdRoute
  SeriesIdRoute: typeof SeriesIdRoute
  PublisherIdRoute: typeof PublisherIdRoute
  ImprintIdRoute: typeof ImprintIdRoute
  EditionIdRoute: typeof EditionIdRoute
  WorkIdRoute: typeof WorkIdRoute
  CampaignSlugRoute: typeof CampaignSlugRoute
  EbooksSplatRoute: typeof EbooksSplatRoute
  ListenIdRoute: typeof ListenIdRoute
  ReadIdRoute: typeof ReadIdRoute
  ShelfIdRoute: typeof ShelfIdRoute
  PublishingRoute: typeof PublishingRoute
  CopyrightRoute: typeof CopyrightRoute
  PublishingPolicyRoute: typeof PublishingPolicyRoute
  StaffPublishingRoute: typeof StaffPublishingRoute
  StaffSupportRoute: typeof StaffSupportRoute
  StaffStorefrontRoute: typeof StaffStorefrontRoute
  ApiPublicHooksIngestRoute: typeof ApiPublicHooksIngestRoute
  ApiPublicBooksIdContentRoute: typeof ApiPublicBooksIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiobooks': {
      id: '/audiobooks'
      path: '/audiobooks'
      fullPath: '/audiobooks'
      preLoaderRoute: typeof AudiobooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestsellers': {
      id: '/bestsellers'
      path: '/bestsellers'
      fullPath: '/bestsellers'
      preLoaderRoute: typeof BestsellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definitions': {
      id: '/definitions'
      path: '/definitions'
      fullPath: '/definitions'
      preLoaderRoute: typeof DefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-releases': {
      id: '/new-releases'
      path: '/new-releases'
      fullPath: '/new-releases'
      preLoaderRoute: typeof NewReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preorders': {
      id: '/preorders'
      path: '/preorders'
      fullPath: '/preorders'
      preLoaderRoute: typeof PreordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves': {
      id: '/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof ShelvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$id': {
      id: '/author/$id'
      path: '/author/$id'
      fullPath: '/author/$id'
      preLoaderRoute: typeof AuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$id': {
      id: '/series/$id'
      path: '/series/$id'
      fullPath: '/series/$id'
      preLoaderRoute: typeof SeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/$id': {
      id: '/publisher/$id'
      path: '/publisher/$id'
      fullPath: '/publisher/$id'
      preLoaderRoute: typeof PublisherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint/$id': {
      id: '/imprint/$id'
      path: '/imprint/$id'
      fullPath: '/imprint/$id'
      preLoaderRoute: typeof ImprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edition/$id': {
      id: '/edition/$id'
      path: '/edition/$id'
      fullPath: '/edition/$id'
      preLoaderRoute: typeof EditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/work/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$slug': {
      id: '/campaign/$slug'
      path: '/campaign/$slug'
      fullPath: '/campaign/$slug'
      preLoaderRoute: typeof CampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$': {
      id: '/ebooks/$'
      path: '/ebooks/$'
      fullPath: '/ebooks/$'
      preLoaderRoute: typeof EbooksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$id': {
      id: '/listen/$id'
      path: '/listen/$id'
      fullPath: '/listen/$id'
      preLoaderRoute: typeof ListenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf/$id': {
      id: '/shelf/$id'
      path: '/shelf/$id'
      fullPath: '/shelf/$id'
      preLoaderRoute: typeof ShelfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing-policy': {
      id: '/publishing-policy'
      path: '/publishing-policy'
      fullPath: '/publishing-policy'
      preLoaderRoute: typeof PublishingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/publishing': {
      id: '/staff/publishing'
      path: '/staff/publishing'
      fullPath: '/staff/publishing'
      preLoaderRoute: typeof StaffPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/support': {
      id: '/staff/support'
      path: '/staff/support'
      fullPath: '/staff/support'
      preLoaderRoute: typeof StaffSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/storefront': {
      id: '/staff/storefront'
      path: '/staff/storefront'
      fullPath: '/staff/storefront'
      preLoaderRoute: typeof StaffStorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest': {
      id: '/api/public/hooks/ingest'
      path: '/api/public/hooks/ingest'
      fullPath: '/api/public/hooks/ingest'
      preLoaderRoute: typeof ApiPublicHooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/books/$id/content': {
      id: '/api/public/books/$id/content'
      path: '/api/public/books/$id/content'
      fullPath: '/api/public/books/$id/content'
      preLoaderRoute: typeof ApiPublicBooksIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiobooksRoute: AudiobooksRoute,
  BestsellersRoute: BestsellersRoute,
  DealsRoute: DealsRoute,
  DefinitionsRoute: DefinitionsRoute,
  DownloadsRoute: DownloadsRoute,
  HighlightsRoute: HighlightsRoute,
  LibraryRoute: LibraryRoute,
  NewReleasesRoute: NewReleasesRoute,
  NotificationsRoute: NotificationsRoute,
  CommunityRoute: CommunityRoute,
  PreordersRoute: PreordersRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  ShelvesRoute: ShelvesRoute,
  StatsRoute: StatsRoute,
  StoreRoute: StoreRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRoute,
  BookIdRoute: BookIdRoute,
  BooksIdRoute: BooksIdRoute,
  AuthorIdRoute: AuthorIdRoute,
  SeriesIdRoute: SeriesIdRoute,
  PublisherIdRoute: PublisherIdRoute,
  ImprintIdRoute: ImprintIdRoute,
  EditionIdRoute: EditionIdRoute,
  WorkIdRoute: WorkIdRoute,
  CampaignSlugRoute: CampaignSlugRoute,
  EbooksSplatRoute: EbooksSplatRoute,
  ListenIdRoute: ListenIdRoute,
  ReadIdRoute: ReadIdRoute,
  ShelfIdRoute: ShelfIdRoute,
  PublishingRoute: PublishingRoute,
  CopyrightRoute: CopyrightRoute,
  PublishingPolicyRoute: PublishingPolicyRoute,
  StaffPublishingRoute: StaffPublishingRoute,
  StaffSupportRoute: StaffSupportRoute,
  StaffStorefrontRoute: StaffStorefrontRoute,
  ApiPublicHooksIngestRoute: ApiPublicHooksIngestRoute,
  ApiPublicBooksIdContentRoute: ApiPublicBooksIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
